### ISSUE TITLE
No handler found for the command: 'ForceCode.open'. Ensure there is an activation event defined, if you are an extension.

### ISSUE THREAD

**Issue by rogah** [celador/ForceCode#1]
I'm trying to use the ForceCode on both Mac OS X El Capitan and Windows 8 64 but I'm getting the following error message for all commands. 

_No handler found for the command: 'ForceCode.`CommandName`'. Ensure there is an activation event defined, if you are an extension._

I'm clearly doing something wrong here. My folder structure is the following as mentioned in readme instructions.

Directory structure:
```
app
 +--.config
      +--settings.json
```

Any ideas?

**Comment by gs-akhan** [comment]
Same issue here

**Comment by jperezq** [comment]
It started working for me once I installed the "apex" and "visualforce" extensions, which seem to be a requirement. First few hours using VSC here, I'm sure there has to be a way to represent this inter-extension dependency.

**Comment by sutur** [comment]
i had to put the settings.json into the .vscode folder. Also i needed to remove the "${  }" from the config. just the plain user login information.

one issue i found proxy settings arent considered.

**Comment by benjaminx3000** [comment]
Same here

**Comment by mgarf** [comment]
despite installing the apex and visualforce extensions I still am unable to do anything.

**Comment by celador** [comment]
@mgarf @sutur @jperezq @gs-akhan @rogah 
There was an issue with the VSCE packaging a while ago.  It is fixed now.  
Please reevaluate if the extension works and provide your feedback.  
I will be more attentive to these issues going forward.
