### ISSUE TITLE
Force: Get Class, Page or Trigger stopped working after last release

### ISSUE THREAD

**Issue by wabbott-veeva** [celador/ForceCode#101]
The command 'Force; Get Class, Page or Trigger' stopped working after the last update.

The error comes as: Running the contributed command:'ForceCode.open' failed.

**Comment by celador** [comment]
Can you provide more details?

What version of the extension, OS + version are you using?

**Comment by wabbott-veeva** [comment]
Sure.  
Windows 10, latest update
ForceCode version: 0.5.29
VSCode: 1.12.2 (latest)

Steps to Reproduce:
- Open VSCode and navigate to a Force.com project that you've already set up.  (force.json is all good.  Can save/push class and trigger updates no problem).
- Click 'View->Command Palette'
- Type in 'Force'.  One of the options that shows is 'Force: Get Class, Page or Trigger'

If you select it, you'll get the pop up message: "Error: Running the contributed command: 'ForceCode.open' failed.".  On the bottom of the screen this message shows in the status bar: "ForceCode: The requested resource does not exist"

**Comment by mgarf** [comment]
Noticing the same issue with the compile command (Same details as above): 

Running the contributed command:'ForceCode.compile' failed.

**Comment by mgarf** [comment]
Here is the debug log:

Error: ENOENT: no such file or directory, open 'C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.29\languages\apex-language-configuration.json'
(anonymous) @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Cannot read property 'index' of null: TypeError: Cannot read property 'index' of null
    at context.subscriptions.push.vscode.workspace.onDidSaveTextDocument (C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.29\out\src\extension.js:71:23)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:30934)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:34741)
    at t.$acceptModelSaved (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:297843)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:266428)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:154931)
    at h (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:155608)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Running the contributed command:'ForceCode.compile' failed.

**Comment by celador** [comment]
Do you have the Apex Language Extension installed?

**Comment by mgarf** [comment]
Yep

**Comment by wabbott-veeva** [comment]
Yes.

**Comment by celador** [comment]
I think I resolved the issue in 0.5.31. Can you check and let me know?

**Comment by mgarf** [comment]
Looks like it broke it further:

```
[Extension Host] Activating extension `JohnAaronNelson.ForceCode` failed: Cannot find module 'xml2js'.
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
mainThreadExtensionService.ts:111Activating extension `JohnAaronNelson.ForceCode` failed: Cannot find module 'xml2js'.
t.$localShowMessage @ mainThreadExtensionService.ts:111
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:285[Extension Host] Activating extension `JohnAaronNelson.ForceCode` failed:  Cannot find module 'xml2js'
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:285[Extension Host] Here is the error stack:  Error: Cannot find module 'xml2js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.Y.o._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:366382)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.31\out\src\commands\compile.js:9:21)
    at Object.<anonymous> (C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.31\out\src\commands\compile.js:557:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by doug-episource** [comment]
For me, version 0.5.31 is basically broken with no commands working.  No matter what command I choose, I get the following error (just with a different command shown):
`command 'ForceCode.showMenu' not found`

0.5.29 was working for normal development for me -- I did not try Get Class, etc...

Versions:
Mac OS, Sierra, 10.12.4
VS Code, v1.12.12
ForceCode, v0.5.31
Apex, 0.0.2
Visualforce, 1.0.2

**Comment by btamburrino** [comment]
0.5.32 is also broken for several of us with the same "command not found" error. We've had to revert internally back to 0.5.29 to be able to continue working.

**Comment by rgscherf** [comment]
Same! 0.5.32 is totally kaput on Windows 7 and VS Code version 1.12.2.

**Comment by wabbott-veeva** [comment]
0.5.32 confirmed broken on Windows 10 (latest update) and VS Code 1.12.2.  Files won't save to server.

**Comment by kbannon346** [comment]
Commands do not work on 0.5.32.

Error "command 'xxxxxxxx' not found"

MacOS: 10.12.5
VSCode: 1.12.2

**Comment by j1ynn** [comment]
Same problems -

ForceCode 0.5.32 (w/dependencies)
VSCode 1.12.2
Windows 10 Pro build 15063 (should be latest update)

**Comment by wings1801** [comment]
> 0.5.32 is also broken for several of us with the same "command not found" error. We've had to revert internally back to 0.5.29 to be able to continue working.
@btamburrino can you tell me how to revert back to 0.5.29?

**Comment by wings1801** [comment]
Here is the link for anyone who want to revert back to version 0.5.28.
https://stackoverflow.com/questions/37071388/how-to-install-vscode-extensions-offline

**Comment by wabbott-veeva** [comment]
Some odd stuff going on.  I back-leveled to 0.5.28 and now nothing works.  Even the most basic command like "ForceCode Menu" comes back with:  "ForceCode.ShowMenu not found."  All dependencies (Apex, VF) are installed.
![image](https://cloud.githubusercontent.com/assets/2293594/26817485/ce2ed478-4a64-11e7-8a30-d4e90463a08e.png)

**Comment by celador** [comment]
Just published 0.5.33

I had installed NPM 5 and it is apparently not production ready yet....

**Comment by j1ynn** [comment]
Still not working for me for some reason.
![forcecode33](https://user-images.githubusercontent.com/16748693/26843229-7f19acce-4abd-11e7-90c0-5e6fea1a9ab5.png)

**Comment by kbannon346** [comment]
Try uninstalling ForceCode and then reinstalling -- this is what worked for me, @j1ynn

**Comment by celador** [comment]
If you're still having troubles, manually remove the old versions of the extension then reinstall the extension
For Mac or Linux, run 
rm -rf ~/.vscode/extensions/JohnAaronNelson.forcecode*

for Windows, go to %HOMEPATH%\.vscode\extensions\ and delete the ForceCode extensions

**Comment by mgarf** [comment]
@celador Its functional again but still running into the menu issues earlier mentioned. With auto compile, things compile fine but accessing any menu commands fail

```
Cannot read property 'index' of null: TypeError: Cannot read property 'index' of null
    at context.subscriptions.push.vscode.workspace.onDidSaveTextDocument (C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.33\out\src\extension.js:72:23)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:30934)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:34741)
    at t.$acceptModelSaved (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:297843)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:266428)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:154931)
    at h (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:155608)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Running the contributed command:'ForceCode.compile' failed.
```

**Comment by mgarf** [comment]
any updates on fixing this?

**Comment by AdamEdmonds** [comment]
I manage to get the extension working by doing the following:
1) Update VSCode to the latest version (1.13.1)
2) Remove ForceCode extension and dependencies
3) Reload VSCode
4) Install ForceCode and dependencies
5) Reload VSCode
6) Remove ForceCode only leave dependencies
7) Reload VSCode
8) Install ForceCode
9) Reload VSCode

**Comment by ScriptMonkey00** [comment]
I"m facing the same issue... when I tried the 9 steps listed by @AdamEdmonds it changed my error from 
> Running the contributed command:'ForceCode.compile' failed.

to 

> command 'ForceCode.compile' not found

Then I manually removed the plugin and reinstalled it as suggested above as well, and that brought me back to the original error again.

I'm running VS Code 1.14.2, with plugins Apex 0.0.2, Visualforce 1.0.2, and ForceCode 0.5.33

Any updates or advice is welcome.

**Comment by tjsully** [comment]
Today I followed the same steps outlined by @AdamEdmonds and got the same results as @ScriptMonkey00 .  I have the same config as @ScriptMonkey00 .

**Comment by choose0or7** [comment]
Still get the same error.
MacOs Sierra 10.12.6
ForceCode version: 0.5.35
VSCode: 1.17.1

**Comment by dancrowdus** [comment]
ForceCode just broke for me today, uninstalled/reinstalled to try to fix the "Admin operation already in progress" bug. (If any one has a solution to that one I'd appreciate it as well).

Followed the steps @AdamEdmonds recommended but to no avail. I still only get 
`command 'ForceCode.showMenu' not found`

**Comment by WilfredoMorillo** [comment]
I'm having the same issue. tried on windows and mac and nothing works.

**Comment by sswigercs** [comment]
help us @celador, you're our only hope!

**Comment by LastWinterKin** [comment]
same error in 
Windows 10 
Force 0.5.35
VSCode 1.18.1

**Comment by sswigercs** [comment]
@LastWinterKin was able to solve this by uninstalling forcecode and dependencies, restarting VS Code, Installing Apex and Visualforce extensions, restarting VS Code, then installing forcecode again.

**Comment by LastWinterKin** [comment]
@sswigercs  Install the Apex and Visualforce extensions first? Do you mean that two dependencies?
