### ISSUE TITLE
Upgrading to 0.5.32 breaks extension

### ISSUE THREAD

**Issue by dshahin** [celador/ForceCode#102]
After upgrading using command+option+c does not show the ForceCode menu.  Instead, the following error appears:

`command 'ForceCode.showMenu' not found`

After uninstalling and installing last stable version, same error is occurring.  
I fired the latest code up in debug mode, but error does not repro that way, and that is only way to use latest version

**Comment by wings1801** [comment]
Same here.
Is there any way to downgrade to lower version?

**Comment by wings1801** [comment]
Here is the link for anyone who want to revert back to version 0.5.28.
https://stackoverflow.com/questions/37071388/how-to-install-vscode-extensions-offline

**Comment by aburdenko** [comment]
Having the same problem on both Windows 7 and Windows 10. Hope this gets fixed soon!

**Comment by ErnstEeldert** [comment]
Same here.

**Comment by GoopilHigh** [comment]
Same Problem

**Comment by aburdenko** [comment]
Here's the combination that finally got ForceCode working for me again. Version 0.5.29, Visual Studio Code March Edition. April Edition, even with 0.5.29, did not work for me.

**Comment by celador** [comment]
Just published 0.5.33

I had installed NPM 5 and it is apparently not production ready yet....

**Comment by btamburrino** [comment]
Not seeing 0.5.33 on the Visual Studio Marketplace - is it only available as a vsix in the repo right now?

**Comment by celador** [comment]
Try now.

**Comment by kbannon346** [comment]
0.5.33 didn't fix the issue for me.

**Comment by btamburrino** [comment]
I was able to successfully upgrade on both Mac and Windows to 0.5.33. Note that I had not installed anything past 0.5.29 on either machine (had already heard that 32 did not work and I have auto-updates off.)

**Comment by josiahlee21** [comment]
0.5.33 brings back the ForceCode menu, but the commands like Refresh from Org and Diff are still not working.

**Comment by dshahin** [comment]
Upgrading to 0.5.33 has solved the issue for me.  Thanks for the quick fix @celador !

ForceCode is the best Force IDE once again!

**Comment by celador** [comment]
If you're still having troubles, manually remove the old versions of the extension then reinstall the extension
For Mac or Linux, run 
rm -rf ~/.vscode/extensions/JohnAaronNelson.forcecode*

for Windows, go to %HOMEPATH%\.vscode\extensions\ and delete the ForceCode extensions

**Comment by rgscherf** [comment]
Thanks for jumping on this @celador

**Comment by dshahin** [comment]
@celador I don't have a way to contact you.  Can you email your best email address?  Have some stuff to talk to you about when you have time.

**Comment by nitronick600** [comment]
I'm seeing these issues as well.  Clean install, version 0.5.33, Mac, npm version 5.0.0.  "Running the contributed command:'ForceCode.open' failed."
