### ISSUE TITLE
Create Class fails silently

### ISSUE THREAD

**Issue by DavidCDean** [celador/ForceCode#106]
If no folder named "classes" exists, in appropriate lower case, the Create Class menu option fails silently. It does not seem to throw any errors, in the JS console or elsewhere, and doesn't display the follow-on menu.

**Comment by pauloavelar** [comment]
Can confirm. And it can happen easily if you retrieve all files from org, as at least in Windows it creates the classes directory inside unpackaged.

**Comment by celador** [comment]
Other users do not experience this issue.  Please debug the extension using
the directions at the bottom of the Readme to ascertain the real issue.  It
would be awesome if you could also submit a PR for the fix.

If you need additional help resolving the bug, please let me know so we can
resolve the issue together.
