### ISSUE TITLE
Show indication in output window when starting salesforce activities

### ISSUE THREAD

**Issue by jamietre** [celador/ForceCode#107]
First - great extension, I'm very new to salesforce and this making my life a lot easier.

This is a feature request. When running activities such as compile/deploy, run unit tests, etc, there's no indication that anything has happened until the activity completes. It's kind of disconcerting because I'm never sure if I just typed the command keys wrong, or there's a connectivity problem, or what. It would be nice if something could be emitted to the output window at the start of any activity, so I know that it's in progress.

**Comment by celador** [comment]
You're right.  I have a general spinner already in the extension, it would be great to hook that into other commands.
