### ISSUE TITLE
How to disable autoclosing of < Brackets in ForceCode

### ISSUE THREAD

**Issue by Szandor72** [celador/ForceCode#108]
Hello,

I am using a less than slash extension to autoclose tags.

This functionality gets broken by ForceCode since typing < automatically creates a > 

Can I disable this feature of ForceCode?

Thanks
Sz

**Comment by celador** [comment]
I do not believe this is a ForceCode specific issue.  I do not do anything (that I know of) to auto-close tags with this extension
