### ISSUE TITLE
Error while uploading Lightning component

### ISSUE THREAD

**Issue by maccabi32** [celador/ForceCode#110]
While uploading a lightning component, I'm receiving:
ForceCode: Metadata Describe error. Please try Again.

**Comment by ihandley** [comment]
@maccabi32 Did you ever figure this out? I'm seeing the same thing trying to save/deploy an xml metadata file.

**Comment by toadgeek** [comment]
Same error here when trying to update a class API Version:

<apiVersion>40.0</apiVersion>

_ForceCode: Metadata Describe error. Please try Again._

**Comment by celador** [comment]
Have you tried setting your apiVersion in the ForceCode configuration?

**Comment by toadgeek** [comment]
Hi @celador ! Yes, my ForceCode configuration files shows the apiVersion equals to 40. 

`"apiVersion": "40.0",`

Quick explanation: I'm trying to add the IsParallel notation to a test class. This notation is only available for classes with API version equal or greater than 40.0. 

But the class -meta.XML file shows 36.0

`<apiVersion>36.0</apiVersion>`

If i try to add the notation to the Test Class without updating the -meta.XML version, I get this error: 
`'Annotation property, isParallel on IsTest, must be in version 40 or higher'`

If I try to change the version, it saves the -meta.XML locally, but it doesn't deploy it to the server (contrary to what happens the regular classes, that are deployed when saved). 

If I try to use deploy the -meta.XML file using Force: Save/Deploy/Compile, I get that error I mentioned before: 

_ForceCode: Metadata Describe error. Please try Again._

Please let me know if you understand the issue or if you have any questions.

**Comment by vegad** [comment]
@vegad having a similar error when saving a static resource (json) file.

**Comment by agoganian** [comment]
Getting "Metadata Describe Error" when saving a .object file. Only edits were field labels (no API version changes)
