### ISSUE TITLE
Errors when saving Lightning Components should be more descriptive

### ISSUE THREAD

**Issue by jwalke** [celador/ForceCode#111]
When attempting to save a Lightning Component that has a syntax or other error, ForceCode displays an error on the first line of the file that states `:Unknown error`.

When attempting the same save in Developer Console an error such as: `Failed to save undefined: No COMPONENT named markup://aura:attribute2 found` is displayed. This error message is helpful in troubleshooting the issue.

**Comment by celador** [comment]
I would love it if you could help implement this feature.  

The code responsible for displaying the error is [here](https://github.com/celador/ForceCode/blob/de3e17917a4d9fb813c39e98022ad95fc30da716/src/commands/compile.ts#L168) . As you can see, the response must not have any errors... perhaps it has some other property which is listing the error.  

I, sadly, cannot reproduce your error without your code that caused the issue.  It would be incredible if you could debug the issue yourself using the directions at the bottom of the Readme and report back here with a specific suggestion.  Better yet, make a Pull Request for a fix and I'll gladly review it.
