### ISSUE TITLE
:Unknown error when saving file

### ISSUE THREAD

**Issue by PhilippOrtnerUp2Go** [celador/ForceCode#113]
Sometimes getting an :Unkown error when saving a file, works fine and suddenly on the next save it won't deploy to the server anymore, even if it worked fine and I just add a random whitespace or delete an empty line.

Underlining the first line(even if just whitespaces) red. 
Other files seem to work fine while another has the error.

**Comment by celador** [comment]
Please provide more information about your situation.

What exactly causes the problem?

Can you provide some sample data so I can replicate the issue? A repository with only enough files to cause the issue would be ideal.

What have you done in an attempt to resolve the issue? Does the same .resource file upload to SF via other means or other IDEs? Does the extension work with other static resource assets? May you possibly be trying to upload a file that shouldn't be uploaded?

I also encourage you to explore the possibility of debugging the extension yourself and contributing back to the community with a Pull Request for the fix. There are directions at the bottom of the Readme that provide an overview on how to get started. If you need further assistance, please ask.
