### ISSUE TITLE
Cannot deploy static resources (css/js)

### ISSUE THREAD

**Issue by mpongo12** [celador/ForceCode#115]
Switching from Eclipse to Visual Studio Force I found many benefits but a big downside which might be related to some settings: I cannot deploy static resources. Each time I try I get a Non-whitespace before first tag error.
I checked the file start of the file and the metadata file but couldn't resolve this.

Thanks for help
mpongo

**Comment by roddrsw** [comment]
@mpongo12 you have some news? i'm stopped in this same problem..

**Comment by celador** [comment]
Please provide more information about your situation.  

What exactly causes the problem?  

Can you provide some sample data so I can replicate the issue? A repository with only enough files to cause the issue would be ideal.

What have you done in an attempt to resolve the issue?  Does the same .resource file upload to SF via other means or other IDEs?  Does the extension work with other static resource assets? May you possibly be trying to upload a file that shouldn't be uploaded?

I also encourage you to explore the possibility of debugging the extension yourself and contributing back to the community with a Pull Request for the fix.  There are directions at the bottom of the Readme that provide an overview on how to get started.  If you need further assistance, please ask.

**Comment by roddrsw** [comment]
@celador Hello! Thank you for attention.
So, i tried save the ".resource" file using "CTRL+S" and using the command on ForceCode Menu: "Compile/Deploy" and give this error:
![image](https://user-images.githubusercontent.com/26532300/31144482-4050566c-a857-11e7-9df4-ae37250ad7cb.png)

And this file are on correctly directory,  "/src/staticresources/"...

**Comment by vegad** [comment]
I ran into this error today as well.  I have tried saving / deploy / deploy all static resources.  Nothing makes the static resource deploy and I get the same error message as @mpongo12 stated above.

So far, and in the meantime,  it seems that I'll need to use eclipse (Force.IDE) to save these to the server.
