### ISSUE TITLE
Running the contributed command:'ForceCode.compile' failed.

### ISSUE THREAD

**Issue by ScriptMonkey00** [celador/ForceCode#116]
I don't know if my usecase is unique but I'm having an issue with deploying code as I would like to.

Our shared environment uses git to collaborate, and we each work in our own development environments.  When I pull from git, to get the newest changes, I'd like to run a compile just to take everything on my local drive and push to salesforce without needing to pick each file one by one.

I had assumed that this was what "Force: Save/Deploy/Compile" did, but when I run that from the menu, no matter if I have a file loaded or not, it just tells me:

> Running the contributed command:'ForceCode.compile' failed.

I would welcome some advice, I'm hoping that this is just a misuse or mistake I'm making, rather than a bug, and someone could just set me straight.  Thanks.

For formal details:
Running VS Code 1.14.2
Shell 1.6.6
Node 7.4.0
and VisualCode 0.5.33

**Comment by ihavenoidea14** [comment]
Having the same issue. If I click the ForceCode menu item in the bottom status bar, it pulls up the ForceCode menu. If I click on Compile/Deploy from that it works every time though.

**Comment by ScriptMonkey00** [comment]
Actually I found a workaround that works great for me too.  If I use "Deploy Package" from the ForceCode Menu then it works great.

**Comment by celador** [comment]
Can you provide more information about this issue?  Does it happen with all files, all the time, or only a specific one?

Can you also provide more information about your "workaround" ?

**Comment by ScriptMonkey00** [comment]
@celador Sorry about the delay, been buried in other things.
The Compile command I was using, I believe, is folder-wide, not file based, and I did it with no files open so it's not related to a certain file, I wanted to compile everything.

My workaround was simply to use the "Deploy Package" option from inside the forcecode menu rather than the Force: Save/Deploy/Compile from the command pallet.
