### ISSUE TITLE
Not working straight out of the box

### ISSUE THREAD

**Issue by ihandley** [celador/ForceCode#117]
I did a fresh install of ForceCode v0.5.33, and when I hit ctrl + shift + c, I get a command prompt. When I hit ctrl + shift + p, I see an option for ForceCode Menu, but when I select it, nothing happens. What am I missing?

I apologize in advance if this has been covered elsewhere - I was unable to find any relevant threads.

**Comment by ScriptMonkey00** [comment]
I'm not sure but I think the "cmd-shift-c" is mac only, so the control replacement for cmd doesn't work.  As far as your forcecode menu, when I first installed and hit the menu, the display changed and it was very subtly asking me for username/password/etc in the same place the command palette had been a moment before, I almost missed it.

**Comment by ihandley** [comment]
@ScriptMonkey00, thanks for the quick response. If you take a look at the following screenshot, it shows what I see after pressing ctrl + shift + p. Youll notice the ForceCode Menu selector associated with ctrl + shift + c. However, I am still not able to get any further than the command palette. I looked for a login option as best I could - no joy.

![image](https://user-images.githubusercontent.com/5502631/29134824-47c57630-7cf5-11e7-84c8-68aeb76d0983.png)

**Comment by ScriptMonkey00** [comment]
What happens when you press enter, or click, on the ForceCode Menu bar?

**Comment by ihandley** [comment]
Nothing that I can see.

**Comment by walters954** [comment]
@ihandley Open up a folder where you want to save the Salesforce files locally. Then press ctrl + shift + c. 
Also if that command may be bound already in you PC. File > Preferences > Keyboard shortcuts search for ForceCode Menu and rebind the keys to something else. The key though is making sure you are already in a project folder.

**Comment by ScriptMonkey00** [comment]
@walters954 Nice!  I forgot that it won't save settings unless you began by opening a folder.

**Comment by ihandley** [comment]
@walters954 That did it. I'm back in business. Thanks!

**Comment by celador** [comment]
Thanks for the assistance, Ian.
