### ISSUE TITLE
Retrieve by package.xml saves files in src/unpackaged.

### ISSUE THREAD

**Issue by julianACL** [celador/ForceCode#118]
Is this a bug or a misconfiguration of my workspace? Seems to be happening on a fresh install.

Visual Studio Code: 1.14.2
ForceCode: 0.5.33

**Comment by jmrjulian** [comment]
Only seems to happen in Windows.

**Comment by julianACL** [comment]
Only happens in windows.

**Comment by pauloavelar** [comment]
It happens to me as well, and last time I tried I wasn't able to auto compile classes from unpackaged. I had to move all directories out of it into src.

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by celador** [comment]
There was a new version released on August 29th to resolve this issue specifically.  I am closing this issue for now.
