### ISSUE TITLE
Error when trying to save: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by barak-11** [celador/ForceCode#121]
I just downloaded ForceCode for the first time, cloned my git project and modified a file and saved it to SF server, It looked good.
I then modified that file once more, saved it and got this error:

```
================================     ERROR     ================================

getaddrinfo ENOTFOUND cs89.salesforce.com cs89.salesforce.com:443
```

I tried to restart VS Code and save the file again, the slash icon kept spinning for 5 minutes and eventually didn't save it to the server.
![image](https://user-images.githubusercontent.com/9203492/29487358-427b3a1c-8500-11e7-99cf-8e1bbf734930.png)

I'm using VS Code 1.15.1 and FroceCode 0.5.33

**Comment by celador** [comment]
Have you tried troubleshooting the issue further?  Do all files save once, then not again?

**Comment by Panks1** [comment]
Make sure that you have closed all your files in the text editor and have saved them.
The error will be resolved.

**Comment by 09archanakumari** [comment]
@daishi4u did it got resolved as i am facing the same issue and its occurring again and again.
Please  help.

**Comment by shuklaatul99** [comment]
i opened the file in wordpad and replace with the give text. it did not work. again i open the file in notepad and replace existing code with the given one and saved it. after that i tried push command and it worked. so i recomand to use notepad instead of wordpad if you have used it.
