### ISSUE TITLE
After running tests there is no output and cannot see code coverage

### ISSUE THREAD

**Issue by fifepepperdine** [celador/ForceCode#125]
After running test methods in a test class, I can see on the bottom left if any failed or if all tests passed, but there is nothing displayed in the output.  Also, pressing the code coverage button for the associated class does not show any code coverage highlighting.

VSCode - 1.16.1
ForceCode - 0.5.35

**Comment by celador** [comment]
Please refer to the [configuration](https://github.com/celador/ForceCode#configuration) section of the Readme.  Make sure you have the `showTestCoverage` option set to true.

If you do, then something else is wrong.

**Comment by jasminengn** [comment]
Hi @celador, I am having the same issue, I checked the config and could see that the showTestCoverage was to true but it's not working. Any suggestions? Thank you

**Comment by AferraroMezrah** [comment]
Yeah I don't know why it wont show me code coverage. When I click the toggle button nothing happens. I've never changed my configuration but when I open the file it does say that showTestCoverage is set to true.
