### ISSUE TITLE
Ignores "http.proxyStrictSSL": false

### ISSUE THREAD

**Issue by harrymendez23** [celador/ForceCode#129]
Hi,

It seems this setting is being ignored in order to use a corporate proxy with self signed certificate. This is a must for us under the corporate bureaucracy.\

Thanks,
Harry

**Comment by vjogani** [comment]
I am affected by this issue too.

**Comment by arturjsfCGI** [comment]
Did someone could make it with "proxyUrl" config?
![sf](https://user-images.githubusercontent.com/35462687/35404051-899e03c2-01f9-11e8-867b-7d54f273f318.jpg)
