### ISSUE TITLE
Feature: Compile More Metadata Types

### ISSUE THREAD

**Issue by mgarf** [celador/ForceCode#13]
_Currently Working On_
- [x] Permission Sets
- [ ] Objects
- [ ] Profiles
- [ ] Layouts
- [x] Labels
- [ ] Custom Metadata

**Comment by mgarf** [comment]
*Currently working on it* Waiting for the fixes to the path in order for proper testing.

* Currently Working On *

- [ ] Permission Sets
- [ ] Objects
- [ ] Profiles
- [ ] Layouts
- [ ] labels
- [ ] Custom Metadata
- [ ] Static Resources

*Future State*

- [ ] Autocompile React into Static Resources
- [ ] Autocompile Angular into Static Resources

**Comment by celador** [comment]
What is meant by "Autocompile"?  Should we package and update the entire static resource whenever a file in a resource-bundles is updated?  I don't know of a way to update a single file in a static resource on the server, just the whole thing.  

We already have the build resource bundle command.  Should this be automatically executed on any change?

**Comment by mgarf** [comment]
I didn't realize we already have static resources working. 

The autocompile React & Angular was more along the lines of allowing someone to wire in their webpack config and post webpack compile, push that static resource into salesforce. But i haven't really sat down to figure it out just a roadmap idea for down the line.

**Comment by celador** [comment]
The tactic for building with Webpack/Gulp is to direct your build/dist folder to a resource-bundles folder named the way you want your static resource named.
  
Have Webpack/Gulp watch for changes and automatically build your JS project to the resource bundles folder.  Then, when you're in a state where you're ready to test on SFDC, you can run the compile/deploy command.

Using an offline development process helps out a lot with this as you can live-develop your code on your own computer and only deploy to SFDC when you need to test the integration between your SPA and SFDC.  

Using a tool like [JSR Mocks](https://github.com/dshahin/jsr-mocks) helps out a lot in this process.
Stub out a modal class and some sample data, and controller class on SFDC.  Use JSR-mocks on the front end to test out the call once.  Grab the json from the call and convert that into a mock for JSR-Mocks.  You can then develop offline with jsr-mocks and deploy only when necessary.

**Comment by celador** [comment]
There's also the [webpack-salesforce-deploy-plugin](https://www.npmjs.com/package/webpack-salesforce-deploy-plugin) that's available for Webpack that will automatically build and deploy your static resource.  I've used that plugin in the past to develop apps in near realtime.  The auto deploy really only works well on very fast internet connections, as I'm sure you're aware sending 5mb of data, each time you type a keystroke eats up bandwidth fast.

**Comment by mgarf** [comment]
agreed. Makes sense - Currently I have a webpack build that autocompiles the code and drops them into static resources. I typically develop offline with using storybook for testing and mocking. 

I was thinking compiling on running the production compile. But I'm still not sure what type of implementation would exist for js apps. I'll remove them from the list.

**Comment by celador** [comment]
The most recent version now saves any metadata type.  You can right-click a file and save or refresh and save the file when editing using the force compile command.
