### ISSUE TITLE
Don't stop the project!

### ISSUE THREAD

**Issue by renatoliveira** [celador/ForceCode#130]
I think this project should continue together with Salesforce's own extension, because that one is DX-exclusive. So it won't work properly with non-DX projects, which will likely include lots of big projects that are impractical to port to DX, and projects that are open-sourced (meaning that they are hosted in Developer Edition environments, which do not have access to DX permanently, just a 30-day trial). 😞 

Salesforce's extension is pretty much useless for some workflows right now, but extensions like this one and MavensMate still can help lots of people like me (consultants that don't need/want to use DX). 👍

**Comment by hugocharbonneau** [comment]
I second! Using the SF DX API with very large orgs is difficult. Doing the mdapi export/import is longer and not as intuitive. Plus our code is in git in old structure and we have over 6 years history. This means that converting to new format will required a lot of work to keep history.

**Comment by hwong103** [comment]
I just wanted to add this extension has really helped me in my workflow as our team/org is not that big so SFDX doesn't make much sense for us (and we're not professional developers). ForceCode adds a lot of value to my work especially compared to other free alternatives I've tried.

Many thanks for creating this anyway!

**Comment by HazardDev** [comment]
@celador This is definitely something you should keep working on (in my opinion). I'm a student worker and there's zero chance our organization will be moving to Salesforce DX soon. This is the only extension I've found that still supports the workflow the university uses.

**Comment by matthewpomar** [comment]
In my short experience with Salesforce DX, I can attest that it does not (at least today) replace Metadata based development tools, like ForceCode. It is geared primary for those with multiple developers, using VCS as the version of truth. It also requires a heavy investment in setup, learning, and porting over all your existing source.

IMHO, it will be a long while before Salesforce DX is easy to use and robust enough to be the one-tool-fits-all solution for Salesforce development. Until then, I hope ForceCode will continue to be maintained and supported, as I know of no better tool for my smaller clients who don't have a development team.

**Comment by renatoliveira** [comment]
Salesforce intends to make the VS Code extension to be usable for non-DX projects as well, but there's no ETA for a release.

I'll close the issue because of this announcement and because there's no response from the project's owner in here.

Sources:

* https://twitter.com/WadeWegner/status/965932714107985922
* https://github.com/forcedotcom/salesforcedx-vscode/issues/123
* https://developer.salesforce.com/blogs/2018/02/salesforce-extensions-vs-code.html
