### ISSUE TITLE
Running the contributed command:'ForceCode.open' failed.

### ISSUE THREAD

**Issue by LastWinterKin** [celador/ForceCode#133]
VS Code says ForceCode 0.5.35 is Active.

I can login in and create the force.json 

but when I press F1 and choose 'Force: Get Class, Page or Trigger' (exactly, when I press any command start with the 'Force:')

there is an error just like the title.

Anybody could resolve this problem?

**Comment by pankajmauryam** [comment]
I got Solution 
You need to add token with password at the time of ForceCode Menu in salesforce.
Thank you
