### ISSUE TITLE
Did I read ForceCode is no longer being maintained?

### ISSUE THREAD

**Issue by matthewpomar** [celador/ForceCode#135]
Did I read that ForceCode will no longer be maintained because of Salesforce DX? In my short experience with Salesforce DX, I can attest that it does not (at least today) replace Metadata based development tools, like ForceCode. It is geared primary for those with multiple developers, using VCS as the version of truth. It also requires a [heavy investment in setup, learning, and porting over all your existing source](https://salesforce.stackexchange.com/questions/202983/create-a-scratch-org-that-mimics-production-environment).

IMHO, it will be a long while before Salesforce DX is easy to use and robust enough to be the one-tool-fits-all solution for Salesforce development. Until then, I hope ForceCode will continue to be maintained and supported, as I know of no better tool for my smaller clients who don't have a development team.

Is ForceCode still being maintained, or was this just a really bad dream?

**Comment by daishi4u** [comment]
I have forked this repo and have made a lot of improvements/changes which you can find at [http://github.com/daishi4u/ForceCode](http://github.com/daishi4u/ForceCode). I do not have my version published on the marketplace, but you're more than welcome to download the source and build it. If it's ok with @celador I would like to publish what I have in the marketplace eventually, as I think many people would enjoy what I've got so far.
