### ISSUE TITLE
Does ForceCode not support pulling changes on standard objects from our org?

### ISSUE THREAD

**Issue by rmcfarland** [celador/ForceCode#139]
We are using a package.xml file which works just fine in Workbench, with the XML for pulling object data formatted as so:
<types>
        <members>Account</members>
         <members>MyCustomObject__c</members>
.... etc. etc for all objects in my org
        <name>CustomObject</name>
    </types>

However, when we try to refresh our objects folder from the server, it only pulls custom objects. It changes the package xml to 
<types>
        <members>*</members>
        <name>CustomObject</name>
    </types>

Is there a way to keep it from modifying our package.xml so we can pull changes to standard objects?

It looks like MavensMate-SublimeText had a similar issue that was possibly addressed?
https://github.com/joeferraro/MavensMate-SublimeText/issues/75

**Comment by lifewithryan** [comment]
I have this problem too...
