### ISSUE TITLE
not seeing test coverage

### ISSUE THREAD

**Issue by leftpropeller** [celador/ForceCode#141]
I'm clicking the colorful button and my force.json file includes     

"showTestCoverage": true

but, I'm not seeing any indication of test coverage.  what else should I be doing?

thanks...

steve

**Comment by julesx** [comment]
same issue here

**Comment by tggagne** [comment]
What is the correct way to indicate "me too" without having to leave a comment?

**Comment by mpaler** [comment]
Also following this closely. Very interested to see this feature come back online as presently, the only way to get a test coverage report for a specific test is to use the [Force CLI](https://github.com/ForceCLI/force) in the window of VC. Not ideal, but doable. For example, you can run:

`force test -v [YourTestName]`

do `force test --help` for more information. 

Fwiw, it also appears there may be something on the horizon for the ForceCode module if you were to follow along on this somewhat cryptic [pull request](https://github.com/celador/ForceCode/pull/158).
