### ISSUE TITLE
Get all files from org - working in Sandbox but not in Production

### ISSUE THREAD

**Issue by devAdri** [celador/ForceCode#150]
I just started using ForceCode VS Code, and I'm able to retrieve all files from Training Sandbox with no issues, but when I tried it in Production, I am getting the Retrieve Errors with thumbdown and it doesn't really specify what the error is.  Am I missing something here?

**Comment by rjankathi** [comment]
@devAdri For the sandbox how did you managed to get all files? I am able to load only a single file from Open Sales force File using ForceCode Command

**Comment by daishi4u** [comment]
Is this still the case for the newest version?
