### ISSUE TITLE
How can I get my Report Fields downloaded?

### ISSUE THREAD

**Issue by Andonon** [celador/ForceCode#152]
Hi, 

Thanks for your solution. Awesome. 

I would like to download my reports using an XML. I can get close, but I need the fields. 

1) It won't let me get all reports using the wildcard ("...members>*</members..."). So I use this... 

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>AccountManagementGeneral</members>
        <name>Report</name>
    </types>
    <version>43.0</version>
</Package>
```

All I get is Share Information. Is there a way to get the Fields used in the reports?

```
?xml version="1.0" encoding="UTF-8"?>
 <ReportFolder xmlns="http://soap.sforce.com/2006/04/metadata">
     <folderShares>
         <accessLevel>View</accessLevel>
         <sharedTo>me@somewhere.com</sharedTo>
         <sharedToType>User</sharedToType>
     </folderShares>
     <folderShares>
         <accessLevel>View</accessLevel>
         <sharedTo>ITSupportSpecialist</sharedTo>
         <sharedToType>Role</sharedToType>
     </folderShares>
 </ReportFolder>
```

Thanks.

**Comment by mnunezdm** [comment]
Foldered items like Dashboards, Reports, Documents and EmailTempaltes as well as StandardObjects, StandardValueSets and other MetadataTypes cannot be retrieved using wildcards, you have to mannualy specify them in the package xml

Also, when retrieving these foldered items you have to specify the fullname  folder/report, i.e. AccountManagementGeneral/Report1, if you only specify the folder, you only download the xml for the folder

For downloading this information you can use the REST API/Tooling API (depending on the metadata type) to query all the Folder/Name and then concat them to build up your package. Other solution is to use the Force.com IDE (eclipse) to build/download your Foldered Items

Maybe it could be a great idea to implement this? I don't know if SFDX CLI has this functionality

**Comment by daishi4u** [comment]
@mnunezdm you can already download all standard objects in Forcecode via the retrieve package menu item. I will look into ways to implement the others. Thanks for the input.

**Comment by daishi4u** [comment]
Reports, documents, dashboards, and email templates can now be retrieved via the retrieve menu option.
