### ISSUE TITLE
Not work with VsCode 1.25

### ISSUE THREAD

**Issue by colin-julien** [celador/ForceCode#155]
I don't find ForceCode menu.

Error message : command 'ForceCode.showMenu' not found

**Comment by MehdiRah** [comment]
I also have the same issue

**Comment by bucholcm** [comment]
same here :(

**Comment by MehdiRah** [comment]
Im new to using VSCode... Stuck with Sublime as long as i could. Can you roll back versions of VSCode. 
Im trying to uninstall/re-install the plugin to see if that works as well?

**Comment by MehdiRah** [comment]
Install/re-installin the plugin doesnt work.

**Comment by MehdiRah** [comment]
Re-downloaded v1.24 the project and all extensions loaded as normal. 

https://code.visualstudio.com/updates/v1_24

Easy work-around until a fix is out.

**Comment by mrmaramreddy** [comment]
I reinstalled VS code 1.24, seems that is the only way to get this plug-in working for now.

**Comment by hwong103** [comment]
felt like I was going crazy. Feels like every update kills this extension :(

**Comment by julesx** [comment]
https://github.com/daishi4u/ForceCode

fork here but unfortunately it has other issues...really don't want to be stuck with 1.24 forever

**Comment by mimica** [comment]
Same issue here with 1.25 VSCode. Tried installing VSCode and ForceCode from scratch without success.
Tried with 1.24 and it worked.

**Comment by danbenge** [comment]
Same issue here with 1.25.  Using the vsix files in the current build didn't fix it.

**Comment by AferraroMezrah** [comment]
julesx, I tried that repo, but it fails to install. When I check the log it shows that it finds other versions of regular visual studio, but can't find the folder for vs code. Would be nice to specify it.. For now I can't install it.

**Comment by JimCotter** [comment]
This doesn't work for me either. I tried 1.25 with the .vsix installation and it will not work for me.

**Comment by julesx** [comment]
You have to use the “install from visx” option within vs code.

**Comment by brandonrwind** [comment]
I'm having this issue as well. Tried with 1.25 and 1.24 and the visx install and can't get this to work.

**Comment by julesx** [comment]
My previous comment about installing visx from vs code was referring to the daishi4u fork I mentioned above which is currently working great. This extension is deprecated and likely won’t ever be fixed. A lot of it didn’t work anyways.

**Comment by svinuesa** [comment]
same issue here.

**Comment by Ouninpohja** [comment]
and here too.

**Comment by AndreyMargalik** [comment]
You can try to do such thing:
There is a parameter in Settings, named 'salesforcedx-vscode-apex.java.home'.
By default it's set to 'null'. Set it to your actual Java Home Path. 
This helped me to solve this issue.
ex. for Windows:  "salesforcedx-vscode-apex.java.home": "c:\\\Program Files\\\Java\\\jdk1.8.0_172"

**Comment by rock-pile** [comment]
@AndreyMargalik  is your comment for fixing ForceCode with VS 1.25 or for the daishU fork?

**Comment by AndreyMargalik** [comment]
@rock-pile In my case its solved the problem on both of the forks.

**Comment by j-la** [comment]
I tried the other solutions above concerning the settings and installing the fork of ForceCode but same error.  Only working solution was going to 1.24.

**Comment by rock-pile** [comment]
@AndreyMargalik that works for the daish4u branch but that definitely does not fix ''ForceCode.showMenu' not found' error for ForceCode with VSCode 1.25.1

**Comment by daishi4u** [comment]
@rock-pile Make sure that you have Java 8 installed for this to work. Any other issues you can leave on my fork issue page. https://github.com/daishi4u/ForceCode/issues

**Comment by AferraroMezrah** [comment]
@rock-pile when you run tests with ctrl-t do you get actual code coverage highlights? Mine don't show up. I've tried adding show test coverage to true in my force.json, I've added "salesforcedx-vscode-core.retrieve-test-code-coverage": true,
    "salesforcedx-vscode-apex.java.home": 
    "/Program Files/Java/jdk1.8.0_171" 
to my settings file just in case. It's technically in an sfdx project. But that doesn't work either. And I'm using forcecode to deploy and test in my sandbox.

**Comment by rock-pile** [comment]
@AferraroMezrah  you need to have the Test class file open and selected, then hit  Ctrl-Shift-T and the tests in that file will run.  Well they do for me, I didnt have to make any changes to my force.json.

**Comment by doug-episource** [comment]
Not that this much helps, but the upgrade of VSCode to 1.25 introduced a new NodeJS version that does not support Natives. One of the zip packages in one of the dependencies uses Natives and that is one of the things what breaks it. I rebuilt that dependency removing Natives. I would like to upload the version I built and you can use it at your own risk. I have been using it for quite some time with no issues. However, on v1.26.1 the problems panel does not clear. I have opened a ticket with VSCode, but that team feels it is extension related, so it was closed.
