### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by maccabi32** [celador/ForceCode#159]
Hi All,

It isn't really an issue, but I don't manage to find any clear instruction on how to install the plugin.
Can you help me please?

Thanks!

**Comment by Jody-CS** [comment]
This is an extension for Visual Studio Code and can be installed via the marketplace - https://marketplace.visualstudio.com/items?itemName=JohnAaronNelson.ForceCode

*Note the current release of ForceCode only works with VSCode 1.24 (but word on the street is there's an update in the works for 1.25)
