### ISSUE TITLE
The readme says code coverage. But I find that not to be the case.

### ISSUE THREAD

**Issue by AferraroMezrah** [celador/ForceCode#160]
since the whole thing doesn't work in VSCODE 1.25, I am currently running 1.24. I've used the menu to enter my credentials for sandbox. I navigate to my test class and I can run a test. Nothing _really_ happens. It tells me in the status bar, "test complete" I don't get numbers I don't get line coverage. And I don't see the point of testing without line coverage. I hit the toggle button at the top of the screen. Nothing. I've set show coverage in the force.json to be true, nothing. It's been months. And I find it so frustrating that the read me says specifically

> Run Unit Tests
Code coverage highlighting in the editor
Coverage warnings and percents
Errors in the editor on test failures
Auto-open test log
Easy to run a single tests, multiple tests, or all tests in a Class

**Comment by Xspirits** [comment]
Same here, I really tried but couldn't figure out a simple way to have either a lcov file generated or any built-in coverage showing up. 

Readme is misleading and there is no codecoverage so far I think.
