### ISSUE TITLE
Consider to unpublish or add "deprecated" to marketplace extension

### ISSUE THREAD

**Issue by auchenberg** [celador/ForceCode#162]
Hi 👋

It's Kenneth from the VS Code team. Given that this extension is officially deprecated per https://github.com/celador/ForceCode#deprecation, please consider to unpublish or add "deprecated" to marketplace extension, so your users will know.

/k

**Comment by daishi4u** [comment]
I have taken over as the maintainer, this extension is no longer deprecated
