### ISSUE TITLE
Cannot read property 'getWsMember' of undefined

### ISSUE THREAD

**Issue by trentchilders** [celador/ForceCode#167]
I recently was upgraded to version 3.9.2 and ever since then I've been getting this error message on compile 'Cannot read property 'getWsMember' of undefined'. I notice in the release notes that the wsMembers.json file is no longer necessary, however it looks like it's still looking for something there?

**Comment by daishi4u** [comment]
For now you can upgrade to 3.9.4 on the daishi4u fork and you shouldn't face this issue anymore. I will push the changes up to the main repo soon

**Comment by daishi4u** [comment]
Update was just pushed. Should solve your problem.

**Comment by mnunezdm** [comment]
This seems to be fixed in lightning components, but I'm still getting the error in Lightning Apps

**Comment by chasd00** [comment]
I'm seeing this in v3.10.3 with VSCode v1.29.0

<img width="1436" alt="screen shot 2018-11-15 at 1 52 49 pm" src="https://user-images.githubusercontent.com/1261284/48577919-f7f14200-e8dd-11e8-8ec8-860d8e547657.png">

**Comment by chasd00** [comment]
saving a lightning component, I restarted vscode and the error hasn't come back. If i get it again i'll update and try to be more specific
