### ISSUE TITLE
Bug, force.json config update scenario not contemplated.

### ISSUE THREAD

**Issue by mlattuada** [celador/ForceCode#17]
There is no way I can update force.json file contents, and see the changes reflected on ForceService.

Would this help? **On line 47, inside save text document handler.**

`    // It should update config property on service`
`textDocument.fileName.match(/force\.json/) && vscode.window.forceCode.getConfig();`

~~I did not research about how to compile and install extensions from code, so I did not test it.~~

**Update: Tested, and working fine.**

P.D: getToolingData.ts line 30, should evaluate to:

`isAuraDefinition instanceof Array && isAuraDefinition.length` or `isAuraDefinition != null && isAuraDefinition.length` or simple `isAuraDefinition`

**Comment by celador** [comment]
@mlattuada new version 0.2.10 has been released with this change.  Please reevaluate.  I am closing this issue for now.
