### ISSUE TITLE
Can not do anything with Forcecode 3.9.6 & VS 1.27.2

### ISSUE THREAD

**Issue by MickeyRoger** [celador/ForceCode#172]
I can not save code to SF or retrieve any code from SF into my local repo. Before I was using v3.6.3, everything seems to be working fine. However, now the only thing I can do is open the ForceCode menu. Click any option from the menu do nothing.

I'm using VS 1.27.2 and ForceCode 3.9.6 on Mac OS 10.13.6

**Comment by daishi4u** [comment]
Are you using any of the Salesforce extensions, such as the apex language server extension? If so, what version of that are you on?

**Comment by oriolete** [comment]
In my case I'm using VS 1.28, FC 3.9.6 and Apex extension on 43.19.0 and I can't not save code to SF.

**Comment by MickeyRoger** [comment]
These are the extensions that I use: 

![screen shot 2018-10-09 at 17 47 44](https://user-images.githubusercontent.com/31848021/46677564-90afe600-cbeb-11e8-83ca-5d5a675e75a4.png)

**Comment by daishi4u** [comment]
@MickeyRoger please uninstall the apex and visualforce extensions by JohnAaronNelson as I'm sure they are conflicting with the salesforce extensions that you have installed that do a better job at code completion. 

@oriolete can you still save through the compile menu option?

**Comment by oriolete** [comment]
@daishi4u from compile/deploy menu option is saving

**Comment by MickeyRoger** [comment]
@daishi4u : I uninstall those and reinstall ForceCode but it still do nothing. No code saved to SF and all option on the menu do nothing.

I'm using VS 1.28.0, ForceCode 3.9.3 and MacOS 10.13.6

Here's how my extensions looks like: 

![screen shot 2018-10-10 at 11 56 39](https://user-images.githubusercontent.com/31848021/46725321-9b6a8980-cc84-11e8-8413-b09ea9022065.png)

**Comment by MickeyRoger** [comment]
@daishi4u : I check the log:

![screen shot 2018-10-10 at 15 14 52](https://user-images.githubusercontent.com/31848021/46735669-92d37c80-cc9f-11e8-922d-8d150a6cea2c.png)


And then when I disabled all SF extensions: 

![screen shot 2018-10-10 at 15 08 04](https://user-images.githubusercontent.com/31848021/46735737-cb735600-cc9f-11e8-9808-b3b30f27fbec.png)

![screen shot 2018-10-10 at 15 08 29](https://user-images.githubusercontent.com/31848021/46735763-db8b3580-cc9f-11e8-96da-aa30dd7d2d94.png)


In both case, still can not save code or do anything with the Forcecode Menu option

**Comment by daishi4u** [comment]
@MickeyRoger I noticed something in your log. Are you getting notifications that files have been changed on the server from forcecode? If not, could you edit your settings. json file and set the option checkForFileChanges to false and save that file. Then restart vscode and let me know if stuff still doesn't work please

**Comment by daishi4u** [comment]
@MickeyRoger so setting checkForFileChanges to false is what made it work? If so, do you have notifications disabled or something in vscode? I'd like to know if that's what it was to see if I fixed it or if I still need to. Thanks

**Comment by MickeyRoger** [comment]
@daishi4u : No I didn't have notification disabled. Before setting checkForFileChanges to false, I got lots of notification in VS about some changes made by another developer.

**Comment by daishi4u** [comment]
OK, thanks. Did it seem to go away then when you updated to 3.9.7?
