### ISSUE TITLE
Extensions Stop Working when moving workspace

### ISSUE THREAD

**Issue by mnunezdm** [celador/ForceCode#176]
**Describe the bug**
After moving the workspace folder, ForceCode refuses to open

**To Reproduce**
1. Initialize a new Workspace
2. Move the folder
3. Open a new VSCode into the new location
4. Force Code will not open

**Expected behavior**
It should continue working seamlessly

**Desktop (please complete the following information):**
 - OS: macOS
 - VSCode Version: 1.28
 - Version: 3.9.7

**Additional context**
I have Force Code activated by workspace

**Comment by daishi4u** [comment]
I have confirmed the issue and will look more into it this weekend.

**Comment by daishi4u** [comment]
This will be fixed in v3.9.8

**Comment by daishi4u** [comment]
This is now fixed in v3.9.9
