### ISSUE TITLE
Error deploying sfdx created lightning components

### ISSUE THREAD

**Issue by mnunezdm** [celador/ForceCode#177]
**Describe the bug**

When trying to deploy a just created lightning component the following error appears

`The design file contains attribute 'label' but the component doen't`

The following deploys fail with the getWsMember error (#167)

Refreshing from server seems to fix it

**To Reproduce**
1. Create a component with the sfdx cli/plugin
2. Try to deploy it

**Expected behavior**

**Screenshots**

![ezgif com-optimize 1](https://user-images.githubusercontent.com/10410852/46885589-b68df280-ce58-11e8-842f-e780df11bfea.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - VSCode Version: 1.28
 - Version: 3.9.7

**Comment by daishi4u** [comment]
This will be fixed it 3.9.8

**Comment by daishi4u** [comment]
This is now fixed in v3.9.9

**Comment by mnunezdm** [comment]
Still facing this issue in 3.9.9

**Comment by daishi4u** [comment]
@mnunezdm The label part of the error or the getWSMember part? The first error seems to be coming from the SFDX extension, as I had the same issue when I tested, but I fixed the getWSMember piece
