### ISSUE TITLE
ForceCode Menu Commands - "Cannot read property 'tooling' of undefined"

### ISSUE THREAD

**Issue by JA3N** [celador/ForceCode#178]
1.Installed ForceCode on VSCode
2.Created Folder in VSCode
3.Selected ForceCode Menu in Command Palette
4.Logged into sandbox environment
5.Settings filed generated in folder
6.Force Code Menu -> Open Salesforce File (Or Get Logs)
Error pops up in bottom right corner "Cannot read property 'tooling' of undefined"

If i try Force Code Menu -> Retrieve Package / Metadata 
it gives me the error message "Cannot read property 'metadata' of undefined"

Any ideas?

**Comment by IIvanov8888** [comment]
I am getting the same error , any suggestions ?

**Comment by daishi4u** [comment]
Can you try and log out through the menu then back in?

**Comment by JA3N** [comment]
@daishi4u Yes, the error message appears again after logging out through the menu

Is there a list of dependencies somewhere? I might have missed it and couldn't find it in the readme

If i have all dependencies i could try to debug the lines where "vscode.window.forceCode.conn.tooling" are called, though i'm not too familiar with how to edit extensions and test it

**Comment by daishi4u** [comment]
@JA3N it's alright, somehow the connection isn't getting set then while logging in. It should set everytime you log in or switch users, so somehow the connection must be failing. I will dig into it more tonight and see what I can find.

**Comment by daishi4u** [comment]
This should now be fixed in v3.9.9
