### ISSUE TITLE
Package.xml generator

### ISSUE THREAD

**Issue by oriolete** [celador/ForceCode#180]
It will be very usefull a package.xml generator with all possible type of objects (classes, pages, tiggers,aura,...) to deploy when you create a new blank project.

For example:

`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>*</members>
        <name>AuraDefinitionBundle</name>
    </types>
    <version>43.0</version>
</Package>
`

**Comment by daishi4u** [comment]
This is now implemented in v3.9.9

**Comment by oriolete** [comment]
@daishi4u your are like god!!! Thanks a lot, this change save's me a lot of time.
