### ISSUE TITLE
settings file never saved and menu not responding

### ISSUE THREAD

**Issue by KevinGossentCap** [celador/ForceCode#182]
**Describe the bug**
Setting file is overridden over and over.
makes the menu not really working (can't add any other connexion or visually edit setting file etc.)

**To Reproduce**
on a computer that had the previous 3.9.4 version installed we : 
- uninstalled it
- closed VSCode
- move old settings
- launch VSCode
- installed from market
- make parameters (even change the file to set checkForFileChanges to false)
- reload VSCode or close and launch it
- you'll see VSCode ask you again if you want to auto compile or not
- you'll see the autocheck files even if you forced save the parameter at false

**Expected behavior**
normal behaviour (parameters saved, setting file not overridden, able to use the menu)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version 3.9.9 from market

**Comment by daishi4u** [comment]
@KevinGossentCap @cgb-76  Did 3.9.11 resolve this issue for you?

**Comment by KevinGossentCap** [comment]
It solved part of it only.
the "setting file overriden" is solved
the "menu option not working" not fully working (edit settings is ok but can't logging into new org)

**Comment by KevinGossentCap** [comment]
We could put it in a new bug to make things clear

**Comment by daishi4u** [comment]
I'm going to close as it relates to #188
