### ISSUE TITLE
3.9.10 is broken. Cannot read property 'storageRoot' of undefined

### ISSUE THREAD

**Issue by daishi4u** [celador/ForceCode#185]
3.9.10 won't start. There is an emergency fix in place via PR #184 

Sorry for the inconvenience everyone. We will get this issue solved ASAP

For the time being, you can download the new release by clicking the link below and installing in the extension menu via "Install from VSIX..."
[Download 3.9.11](https://drive.google.com/file/d/1RH2vcNfurI12PF6rHWfyaps7Luf2oD86/view?usp=sharing)

**Comment by mnunezdm** [comment]
It gets stuck on loading on new projects (initializing a project in a new folder)

**Comment by daishi4u** [comment]
@mnunezdm 3.9.11 does?

**Comment by mnunezdm** [comment]
Seems to be fixed now, Thank you Brett!!
