### ISSUE TITLE
Ability to abort Forcecode task

### ISSUE THREAD

**Issue by tomas-migra** [celador/ForceCode#186]
Sometimes ForceCode stucks or I changed my mind to run some long running task.

In ForceCode it would be nice to be able to go to Running Tasks and right click to task will give me option to abort such task to empty a queue.

**Comment by no-stack-dub-sack** [comment]
@tomas-migra I second the motion - this thought has crossed my mind several times as tasks have hung and my only option has been to restart VS Code. Great call!

**Comment by daishi4u** [comment]
Implemented in 3.17.0
