### ISSUE TITLE
Unable to log out from current account or log in to new sandbox when I've already logged in with one account

### ISSUE THREAD

**Issue by narekharutyunyan** [celador/ForceCode#188]
**Describe the bug**
It doesn't allow me to log out from the current account or log in with the new one.

**To Reproduce**
1. Open Visual Code and log in with the first account
2. Log out from the menu or task panel doesn't do anything. Same happens if you try to log in with a new account. 

**Expected behavior**
The extension should allow me to log out from the account or log in with multiple accounts. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 3.9.11

**Comment by daishi4u** [comment]
This will be fixed in 3.9.12
