### ISSUE TITLE
Formating apex

### ISSUE THREAD

**Issue by SergioXp** [celador/ForceCode#191]
Hi!

Thanks for bringing all updates to the marketplace!

Could you add a new feature to format apex code?

**Comment by mnunezdm** [comment]
Ì think this should be proposed in vscode-salesforcedx repo

Look, it's already open https://github.com/forcedotcom/salesforcedx-vscode/issues/95

**Comment by daishi4u** [comment]
I would agree, as it would need to be in the language server
