### ISSUE TITLE
Once you add new env, menu not working

### ISSUE THREAD

**Issue by KevinGossentCap** [celador/ForceCode#192]
**Describe the bug**
if you have 1 connection and add a second one, the menu and any log-out or log-in feature doesn't work anymore before you reload VSCode.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version latest 3.9.12

**Additional context**

**Comment by KevinGossentCap** [comment]
In fact, launching a VSCode reload, it seem to remove the first present login info from the in VSCode list

**Comment by KevinGossentCap** [comment]
It seems to be related to the "check file updates" when the process itself identifies more than 15 files.
In such cases, the whole plugin goes nuts.

**Comment by daishi4u** [comment]
There's a new beta release that addresses this issue. It can be downloaded in the beta-testing forcecode slack channel if you want to test it out.

**Comment by KevinGossentCap** [comment]
I confirm it seems to be solved in 3.10.0-2
But from time to time the plug-in isn't able to finish it's loading

**Comment by daishi4u** [comment]
When it doesn't load, are there any errors in the vscode developer tools console?

**Comment by KevinGossentCap** [comment]
I did not check at the time, but will do next time it happens.
But trying to reload VSCode a few times got me a "socket hang up" pop-up error" by forcecode
