### ISSUE TITLE
Not able to login to Salesforce Org on company proxy 

### ISSUE THREAD

**Issue by ayushthakkur1701** [celador/ForceCode#196]
Trying to connect login.salesfoce.com via forceCode but facing  following issue:
![capture](https://user-images.githubusercontent.com/25404161/47720189-562dec00-dc73-11e8-8651-751ebc5242f7.PNG)

I have added proxy authentication to settings.json already but still facing the same.
Need help on this please.

**Comment by daishi4u** [comment]
Please read the second part in the readme under the FAQ section
