### ISSUE TITLE
Slack Invite Link

### ISSUE THREAD

**Issue by dmgerow** [celador/ForceCode#203]
**Describe the bug**
The Slack Invite is out of date in the README so others cannot join the Slack.

**To Reproduce**
1. Go to README
2. Click Slack Invite

**Expected behavior**
Enter Slack Workspace

**Screenshots**
![image](https://user-images.githubusercontent.com/8942891/48219781-10e47b00-e353-11e8-87a4-831ed65a58e8.png)

**Comment by celador** [comment]
Fixed in 70ea81bd56a67d5a32bbfcb38eae37f7ede1c59a
