### ISSUE TITLE
Execute Anonymous option in new Tab (Untitled window) 

### ISSUE THREAD

**Issue by naveenila1221** [celador/ForceCode#204]
**Describe the solution you'd like**
Open new Tab 
Write some code 
In right would like to have Execute Anonymous feature. 
Any keyboard short cut is also preferable (Alt + Ctrl + E) 

**Describe alternatives you've considered**
Open new Tab 
Write some code 
Open Force Code Menu
Select Execute Anonymous

**Comment by daishi4u** [comment]
You can already run execute anonymous code in an untitled window. 
1. Open a new file (Untitled window)
2. Write some code
3. Select all the code that you wrote
4. Open the ForceCode menu and select Execute Anonymous

The keyboard shortcut is alt-cmd-e on Mac and ctrl-shift-e on Windows
