### ISSUE TITLE
Non-whitespace error while deploying static resource

### ISSUE THREAD

**Issue by Oren-Perion** [celador/ForceCode#207]
Hi,

When I save a static resource file I get an error about whitespaces in the file
"Non-whitespace before first tag. Line: 0 Column: 1 Char: {"

![non-whitespace](https://user-images.githubusercontent.com/45172182/48711213-4de22480-ec13-11e8-9a97-3b23a421bafc.PNG)

There is no white space in the start of the file..

Iv'e seen a same issue in this link from 2016 but it has no answer to this issue
https://github.com/celador/ForceCode/issues/115

Is there a solution for this error or it's not possible to deploy static resources with ForceCode?

Thanks,
Oren

**Comment by daishi4u** [comment]
What kind of a static resource are you trying to deploy? Is your folder structure correct? In order to tell this you can retrieve a static resource with the same mime type and look at how the structure is.

**Comment by Oren-Perion** [comment]
Hi,

I don't think I understand what your asking exactly
 
The resource is of type 'text/plain'

How do I know if the folder structure is correct? Iv'e retrieved the resources through the ForceCode retrieve option (like any other type I retrieved)

Thanks,
Oren

**Comment by daishi4u** [comment]
OK, that answers my questions. I'll try it out on my work computer, but I won't be able to look into it further until I get home later tonight

**Comment by daishi4u** [comment]
When you download a static resource, you have to edit the files contained in the "resource-bundles" folder. Editing the files in the "staticresources" folder will give you the error you described.
