### ISSUE TITLE
Forcecode is reporting bad "Someone has changed this file!" for Aura files

### ISSUE THREAD

**Issue by alex9138** [celador/ForceCode#209]
**Describe the bug**
Forcecode is reporting "Someone has changed this file!" even if it's me the last owner of the modifications.
By comparing saveAura.ts and saveApex.ts I can see that the aura one is not doing the same thing, and during my test I haven't got the problem for Apex saving.

**To Reproduce**
1. Go to a Lightning controller
2. Add something to the file
3. Try to save and automatically deploy to org

**Expected behavior**
It should save the file and nothing else/not notify about someone else has changed the file.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.29.1
 - ForceCode Version 3.11.0

**Comment by daishi4u** [comment]
saveAura and saveApex don't do the same thing because lightning components come in bundles. I haven't found a way to individually check for each file in the bundle being changed. Have you tried resetting vscode and seeing if the issue persists?
