### ISSUE TITLE
ForceCode.showMenu produces an error method in Visual Studio Code v1.29.1

### ISSUE THREAD

**Issue by ImonFyre** [celador/ForceCode#211]
**Describe the bug**
ForceCode.showmenu in Visual Studio Code v1.29.1 produces a VS error popup when invoked.
`command 'ForceCode.showMenu' not found`
ForceCode was working prior to a VSCode update.

**Comment by daishi4u** [comment]
Do you have a folder open?

**Comment by ImonFyre** [comment]
I am new to using VSCode, but I have tried opening my workspace, which has open folders in it, and have tried straight up just opening a folder with my SF code in it from the menu, both have the same result. I get the error message.
