### ISSUE TITLE
I can't retreive my developer edition's metadata

### ISSUE THREAD

**Issue by k010c1232** [celador/ForceCode#213]
Now, I logged into my developer edition with forcecode extension and then I tried to retrieve my dev org's metada. But, I got this error "Either the file/metadata type doesn't exist in the current org or you're trying to retrieve outside of ". It's forcecode bug?

**Comment by daishi4u** [comment]
How are you going about retrieving the metadata? Using the retrieve option in the menu then selecting retrieve all? If you are right clicking on a file or folder outside of your src folder and trying to retrieve then you will see this message

**Comment by k010c1232** [comment]
That error is no longer displayed, but the other error is showed.
"Cannot read property 'manageableState' of undefined"

**Comment by daishi4u** [comment]
@mnunezdm the latest commit to dev-next should fix that issue
