### ISSUE TITLE
Retrieve Standard Value Sets in the retrieve all option

### ISSUE THREAD

**Issue by mnunezdm** [celador/ForceCode#214]
**Is your feature request related to a problem? Please describe.**
Currently, the retrieve all does not retrieve the standard value sets

**Describe the solution you'd like**
Retrieve standard value sets

**Describe alternatives you've considered**
N/A

**Additional context**
I have no idea if this content can be accessed through any API, i have always added all the elements that appear in this [table](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/standardvalueset_names.htm) into my package xml, and download them using ant migration tool

Also, I think that GlobalValueSets should also be considered

**Comment by daishi4u** [comment]
GlobalValueSets can already be retrieved through the retrieve option. Currently working on testing standard value sets
