### ISSUE TITLE
Expired access/refresh token

### ISSUE THREAD

**Issue by RandallFlagg** [celador/ForceCode#216]
**Describe the bug**
When trying to perform an action a message is shown: "expired access/refresh token"

**To Reproduce**
1. Log into the ORG using the browser
2. Close the browser
3. Leave the computer for a period of time(I bet it is 4 hours)
3.1 I think it happens also if you work after 4 hours

**Expected behavior**
Everything just works

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home x64
 - VSCode version: 1.28.2
 - ForceCode Version: ~3.11.1~   3.11.3

**Additional context**
I think it has something to do with the OAuth mechanism. The refresh token should be called and ask for a new token instead of using the current access token.
The status is shown as logged in.

**Comment by julesx** [comment]
this was an issue with previous releases, but the latest couple releases at least have completely resolved this for me

**Comment by daishi4u** [comment]
If you're receiving this error with the newest release then this would usually mean your refresh token has expired and can depend on the settings in the org. The access token is auto refreshed from the refresh token currently

**Comment by RandallFlagg** [comment]
Thanks @daishi4u.
How did the refresh token expired? Can I prevent that? If yes, how? Am I using the latest release? Can I provide any more information? If yes, what and from where?

**Comment by daishi4u** [comment]
@RandallFlagg do you have more than 5 sessions active at a time? It seems 5 is the limit, so if you use more than that via connected apps and web sessions then it may be booting you. See the following: https://salesforce.stackexchange.com/questions/65590/what-causes-a-connected-apps-refresh-token-to-expire 

You can also try to install the Global Connected App in Manage Apps -> Connected Apps OAuth Usage and grant the token to never expire

**Comment by RandallFlagg** [comment]
Thanks for your help @daishi4u.

Not using more than 5 sessions.
Didn't try the second suggestion.

I have noticed that it doesn't happen all the time. Sometimes it works even after a day.
In the meantime I have updated to 3.11.3 so will update in a few days what is the status of the problem.

**Comment by RandallFlagg** [comment]
The issue doesn't seem to continue or at least it happens less times than before. I will continue monitoring and update if it returns.

**Comment by RandallFlagg** [comment]
@daishi4u `3.14.1` Solved this issue completely.
THANKS!
