### ISSUE TITLE
Login redirect to localhost:1717

### ISSUE THREAD

**Issue by harim1993** [celador/ForceCode#218]
When we give the custom URL and it asked for login in the Browser after logged in it redirect to http://localhost:1717/OauthRedirect?code=** and in the VS Code status is like Loading ForceCode extension.

**Comment by anupam081** [comment]
Hi

I am using forceCode with VSCode on my company laptop without proxy at my home but still i get redirect to http://localhost:1717/OauthRedirect?code=** and in the VS Code status is like Loading ForceCode extension.

**Comment by daishi4u** [comment]
@anupam081 are you using a vpn? If so, the same will apply in this issue and you should follow the same guide to get you set up

**Comment by grsamuels** [comment]
@anupam081 did you ever resolve this issue? I am experiencing the same issue. I was able to successfully connect to one sandbox, then when trying to establish connection to another sandbox, I received the localhost:1717 error.  @daishi4u

**Comment by daishi4u** [comment]
@anupam081 did you follow the instructions in the FAQ section of the readme?
