### ISSUE TITLE
Retrieve Package not getting list of Unmanaged Packages

### ISSUE THREAD

**Issue by btamburrino** [celador/ForceCode#222]
**Describe the bug**
When I go to ForceCode Menu->Retrieve Package/Metadata, I only get the standard options (package.xml, specific types) but it does not pull any of the Unmanaged Packages that are in my org. This occurs in both Production and Sandbox instances at API 44.0.

**To Reproduce**
1. Have an org that has an Unmanaged Package with code in it
2. Connect it to ForceCode
3. Go to ForceCode Menu->Retrieve Package/Metadata
4. Notice that no packages are listed

**Expected behavior**
I should see my Unmanaged Packages

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.30.1
 - ForceCode Version 3.11.3

**Additional context**
I'm guessing for some reason retrieve.ts getPackages() is returning nothing for some reason.

**Comment by daishi4u** [comment]
This is fixed in 3.12.0
