### ISSUE TITLE
Impossible to connect to trailhead org

### ISSUE THREAD

**Issue by Bartheleway** [celador/ForceCode#225]
**Describe the bug**
I did setup a trailhead org to store some code that I'm developping to keep it aside from the main project. I tried to connect that trailhead org to VS Code but I get a ERR_EMPTY_RESPONSE when the login process finish : http://localhost:1717/OauthRedirect?code=....

**To Reproduce**
1. Create a trailhead org (change your password)
2. Initialize a new project in VS Code
3. Use custom URL (take the url of the trailhead)
4. Enter your username and password
5. Accept the permissions
6. Crash ...
7. ForceCode stays in "loading..." state but finish the login task

**Expected behavior**
Initialization of ForceCode extension

**Desktop (please complete the following information):**
 - OS: Win 10
 - VSCode version : 1.30.2
 - ForceCode Version : 3.11.3

**Comment by mnunezdm** [comment]
Hi

To fix this error, remove all the content in the .sfdx folder in your home folder and also in your workspace

That should fix the issue

PD: the ERR_EMPTY_RESPONSE if I remember correctly has nothing to do with this error and is associated with a problem with the official extension.

For further help, check the official slack channel!

Regards

**Comment by Bartheleway** [comment]
I found the solution :
1. Go to Dev Hub in the trailhead org
2. Activate the Dev Hub
3. Login again using VS Code => works

P.S : I was seeing `grant type not supported` in the sfdx.log which is in `[Home folder]/.sfdx`

Thanks for your help.
