### ISSUE TITLE
Provide the ability to create lightning components

### ISSUE THREAD

**Issue by nadeemat** [celador/ForceCode#229]
The plugin does not support the creation of lightning components which where the platform is moving. This is a major limitation of the plugin at the moment. It would be great if the plugin provided native support for creating aura bundles/lightning components.

**Comment by daishi4u** [comment]
Lightning components can be created manually or through the salesforce plugins. Support has also been added for lightning web components in an upcoming release.

**Comment by daishi4u** [comment]
The create class menu is currently being reworked. Soon you will be able to create classes, visualforce pages and components, lwc components, aura components, and apex triggers through the menu

**Comment by daishi4u** [comment]
This is implemented in 3.13.0
