### ISSUE TITLE
Switch statements not recognized by compiler

### ISSUE THREAD

**Issue by MowAlon** [celador/ForceCode#230]
Switch statements were introduced in 2018, but ForceCode doesn't recognize them and reports problems despite successfully saving on the SFDC servers.

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_switch.htm

Problem reported: "no viable alternative at input 'switchon'"

**Comment by daishi4u** [comment]
Do you get the error while typing or after saving? If it's before you save then this would be an issue with another plugin you are using.

**Comment by MowAlon** [comment]
Yeah, you're right... it's before I save. Guess I don't know enough about VS Code to realize this isn't a ForceCode thing. Sorry :(
