### ISSUE TITLE
EmailTemplate metadata type not found in org

### ISSUE THREAD

**Issue by bmuniswamy** [celador/ForceCode#232]
When I try to edit an existing email template that is in the salesforce sandbox I keep getting this error message "EmailTemplate metadata type not found in org".  The package.xml file has the metadata type and also has the folder specified.
**To Reproduce**
1. Go to a salesforce sandbox and pull down email templates
2. try to make any small change and try to save the template
3. See error

**Expected behavior**
Should be able to save the file without any issues
**Screenshots**
![screen shot 2019-01-25 at 3 29 23 pm](https://user-images.githubusercontent.com/34690264/51771159-1762d300-20b6-11e9-883b-0ea0ae64fce3.png)

**Additional context**
Was able to deploy the code through ANT deployment tool without any issues.

**Comment by daishi4u** [comment]
Forcecode currently doesn't support saving email templates. Some do save, but others will not.
