### ISSUE TITLE
Cannot open the forcecode menu

### ISSUE THREAD

**Issue by tur676** [celador/ForceCode#233]
**Describe the bug**
I opened ForceCode menu and logged into my org and after then I am not able to see any forceCode options.
I am using 
VS code v1.26.1
ForceCode 3.11.0 
(Windows 7)

**Comment by daishi4u** [comment]
@tur676 I would suggest updating vscode and Forcecode and see if your problem still persists since you are on old versions of each

**Comment by daishi4u** [comment]
Closing, as there is a duplicate here on issue #234
