### ISSUE TITLE
Cannot open ForceCode Menu

### ISSUE THREAD

**Issue by nereag2612** [celador/ForceCode#234]
After installing VS Code and Force Code extension, the corresponding menu is not getting opened.

<img width="271" alt="vscode 1" src="https://user-images.githubusercontent.com/10272446/51972435-a63b6b00-247b-11e9-9267-bad9fbaf8a3a.png">

I'm not able to work with any of the offered features. I tried to logging in an org but the loading message is frozen.

<img width="270" alt="vscode 2" src="https://user-images.githubusercontent.com/10272446/51972436-a63b6b00-247b-11e9-83b8-5e0d3e04fb24.png">

VS Code: 1.30.2
Force Code: 3.12.0
Windows 10 Pro

**Comment by IIvanov8888** [comment]
same issue for me , latest **vscode** and **ForceCode**

**Comment by jgallagants** [comment]
When I had this issue, before using the ForceCode extension I created the Project with "SFDX:Create Project". This method creates a bunch of folders and one in particular, "config", contained configuration files for an Scratch Org. After deleting this folder and refreshing the login attemp, ForceCode was able to log in.

Don't know much abount this Scratch ORGs, but it seems a feature not every instance can have and maybe ForceCode struggles with this extra files?

**Comment by nereag2612** [comment]
Finally I delete all the elements created automatically in local project folder and try to login again with ForceCode Menu. It worked.
