### ISSUE TITLE
Error opening VS Code

### ISSUE THREAD

**Issue by oriolete** [celador/ForceCode#235]
**Summary**
Everty time VS Code is opened appears this message:
Request initialize failed with message: LWC Language Server initialization unsuccessful. Error message: Cannot read property 'forEach' of undefined

**Steps To Reproduce:**
Open VS-Code

**Expected result**
N/A

**Actual result**
N/A

**Additional information**
Developer Tools extracted:
notificationsAlerts.ts:40 Request initialize failed with message: LWC Language Server initialization unsuccessful. Error message: Cannot read property 'forEach' of undefined
t.onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
e.fire @ event.ts:228
t.notify @ notifications.ts:113
t.notify @ notificationService.ts:52
e._showMessage @ mainThreadMessageService.ts:83
e._showMessage @ mainThreadMessageService.ts:44
e.$showMessage @ mainThreadMessageService.ts:38
t._doInvokeHandler @ rpcProtocol.ts:461
t._invokeHandler @ rpcProtocol.ts:446
t._receiveRequest @ rpcProtocol.ts:366
t._receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:171
e.fire @ event.ts:228
a @ ipc.net.ts:103
n._socketDataListener @ ipc.net.ts:132
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
console.ts:134 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:134
t._logExtensionHostMessage @ extensionHost.ts:453
(anonymous) @ extensionHost.ts:244
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
mainThreadExtensionService.ts:42 [salesforce.salesforcedx-vscode-lwc]Request initialize failed with message: LWC Language Server initialization unsuccessful. Error message: Cannot read property 'forEach' of undefined
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:42
t._doInvokeHandler @ rpcProtocol.ts:461
t._invokeHandler @ rpcProtocol.ts:446
t._receiveRequest @ rpcProtocol.ts:366
t._receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:171
e.fire @ event.ts:228
a @ ipc.net.ts:103
n._socketDataListener @ ipc.net.ts:132
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
mainThreadExtensionService.ts:43 Error: Request initialize failed with message: LWC Language Server initialization unsuccessful. Error message: Cannot read property 'forEach' of undefined
	at new ResponseError (/Users/ofarras/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-44.17.0/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
	at handleResponse (/Users/ofarras/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-44.17.0/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:430:48)
	at processMessageQueue (/Users/ofarras/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-44.17.0/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:258:17)
	at Immediate._onImmediate (/Users/ofarras/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-44.17.0/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:242:13)
	at runCallback (timers.js:789:20)
	at tryOnImmediate (timers.js:751:5)
	at processImmediate [as _immediateCallback] (timers.js:722:5)

![image](https://user-images.githubusercontent.com/6986296/52065613-2c88a780-2577-11e9-9609-85347fc2aaf9.png)

**ForceCode version**: 3.12.0

**VS Code Version**: 1.30.2

**SFDX CLI Version**:6.50.0-9817aece8a

**OS and version**: Mac OSX 10.14.2

**Comment by daishi4u** [comment]
This isn't related to Forcecode. Please report the issue here https://github.com/forcedotcom/salesforcedx-vscode/issues
