### ISSUE TITLE
ForceCode Issue : Unknown view ForceCode.treeDataProvider

### ISSUE THREAD

**Issue by shikhss** [celador/ForceCode#239]
When I use Force Code Menu command, i am getting "Unknown view ForceCode.treeDataProvider" error in the taskbar notification. I am getting only org text box name, but not after that. after this I am getting this error. Please help me out from this issue.

**Comment by daishi4u** [comment]
Could you give a little more details? Do you have a folder open first? Can I get exact steps to replicate and VSCode version/OS that you are running? I put the bug templates in for a reason...lol

**Comment by shikhss** [comment]
Yes i have opened a new folder. I followed these steps from this blog:
https://codecracksblog.wordpress.com/2017/10/30/use-visual-studio-code-for-salesforce-developmentide/

Go to File >> Open >> “Create New Folder” in your local drive.
Go to “View” >> Command Palette >> Type “>ForceCode Menu”

**Comment by elD1eg0** [comment]
how did you solve it?

**Comment by krazykat5440** [comment]
I am also having the same issue.  Can you please give details on solution.

**Comment by daishi4u** [comment]
I'm not quite understanding how you guys are receiving this error. Can you give me exact steps and refer to the screenshot in my comment above to make sure you are selecting the proper command...

**Comment by elD1eg0** [comment]
currently I cannot get the screenshot because I installed an older version (3.11.3) to fix the problem on a Windows 8 notebook.
