### ISSUE TITLE
Provide option to Overwrite Server copy in the Diff window

### ISSUE THREAD

**Issue by sfdcnoob** [celador/ForceCode#242]
Lets say someone changed Apex Class on the server and I am working on old copy of Apex class in vscode and trying to save the file. Then it opens the below screen alerting that we are trying to override server changes.
![selection_288](https://user-images.githubusercontent.com/11079913/52599042-5e69fb80-2e0c-11e9-8ad3-5ebe644d537a.jpg)

If I choose 'Diff' option then it opens the below screen, showing the differences between local copy and Server copy.

![selection_289](https://user-images.githubusercontent.com/11079913/52599347-3cbd4400-2e0d-11e9-9627-1fb63ba359d4.jpg)

In the above screen, can we have the option to **Overwrite Server copy**?

Thanks

**Comment by daishi4u** [comment]
This has been implemented in 3.14.1
