### ISSUE TITLE
No indication of save time out

### ISSUE THREAD

**Issue by jgallagants** [celador/ForceCode#243]
Sometimes when saving I do not see an indication that the file did compile properly or not to Salesforce. In this situations I try to deploy it again and I notice that the save attemp just ends the moment is executed.

In older versions that happened this I could see a message about a deplaoyment still in process in a pop up. Now the task just dissapears with no further notifications or information.

Also sometimes while working I press deploy and continue to work, by the time I remember to check if the deploy went Ok, the checkmark that is shown at the ForeceCode extension already dissapeared.

Is it possible to have a log of tasks executed at the ForceCode Running task window? I could come handy to check there is every task went Ok or if any had any issue.

**To Reproduce**
1. Deploy a modified file to Salesforce
2. Hope to get a time out receiving the situation of deployment
3. Try to deploy again while still deploying the previous save

**Desktop (please complete the following information):**
 - OS: [Windows 10 ]
 - VSCode version [e.g. 1.31.1]
 - ForceCode Version [e.g. 3.13.0]

**Comment by daishi4u** [comment]
Please update to 3.14.0, as this is fixed in that version.
