### ISSUE TITLE
Cannot 'Refresh From Server' due to 'Invalid Regular Expression'

### ISSUE THREAD

**Issue by mpschawkfan** [celador/ForceCode#244]
**Describe the bug**
After installing v3.14.0, I am unable to pull any object out of a sandbox using the 'ForceCode: Refresh From Server' feature

**To Reproduce**
1. Update extension to v3.14.0
2. Connect to any Salesforce sandbox
3. Right-click on any metadata file previously pulled from Salesforce org
4. Select 'ForceCode: Refresh From Server'
5. See error 'Invalid regular expression: /c:\[path]\[to]\[directory]\/: \ at end of pattern'

**Expected behavior**
I expect that the file would be refreshed from Salesforce and pulled into my local folder

**Screenshots**
![image](https://user-images.githubusercontent.com/22648127/52727532-6bf5c180-2f83-11e9-8df8-d872315b6c86.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - VSCode version 1.29.1 (though I saw the error in v1.30 and 1.31 as well)
 - ForceCode Version 3.14.0

**Comment by daishi4u** [comment]
This is fixed in 3.14.1
