### ISSUE TITLE
Issue-#226 is still occurring for me.

### ISSUE THREAD

**Issue by SilverMagnum** [celador/ForceCode#245]
I have provided pre-requisite information in issue-#226 along with additional information which directly points at the bug.

**Comment by daishi4u** [comment]
Please read the comment I left on the closed issue, then let me know if that solves the issue. If so, please go ahead and close this issue as well.

**Comment by SilverMagnum** [comment]
Although it was a good consideration (something I probably should have done before but hadn't), it didn't resolve the issue unfortunately.

**Comment by daishi4u** [comment]
Can you open the settings.json file in the .forceCode/USERNAME/ folder and paste the contents here. You can take out your username. Better yet, to avoid github messing stuff up, just temporarily remove your username from the file and take a screenshot and post it here please

**Comment by SilverMagnum** [comment]
Here's the one that doesn't work:
![image](https://user-images.githubusercontent.com/20430939/53057156-031ab780-3463-11e9-8326-451c0cd34f8e.png)

Here's the one that works:
![image](https://user-images.githubusercontent.com/20430939/53057183-22b1e000-3463-11e9-8980-0e1f69a09231.png)

They looks identical to me other than the "src" line. Hopefully this is helpful.

**Comment by SilverMagnum** [comment]
I opened VSCode in my directory1 folder to verify everything is matching and it was suddenly working as expected. I tried to reproduce this working version on my boss's sandbox. However, despite fully closing and reopening VSCode with the correct settings, he kept getting the initial error with lightning component files (.cmp). On top of this, we tried it with a javascript controller and got this (similar) error:
```
{
    "resource": "/c:/src/get/sf/src/aura/posCourseTab/posCourseTabController.js",
    "owner": "fcDiagCol",
    "severity": 8,
    "message": "Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: (",
    "startLineNumber": 1,
    "startColumn": 1,
    "endLineNumber": 1,
    "endColumn": 3
}
```
I feel I should also note that before I changed the "src" setting to be an Windows appropriate "directory2\\src" in the settings.json (when it was still "directory2/src") I was able to deploy apex (.cls) and visualforce (.page) files as expected.

**Comment by daishi4u** [comment]
Were you starting with a component made from scratch via just making files and not through the Forcecode menu by chance?

**Comment by SilverMagnum** [comment]
For the components I've made, yes, I made them from scratch or I've copied from pre-existing ones.

**Comment by KevinGossentCap** [comment]
A pretty stupid idea but proves to sometimes to be a problem : could you verify the encoding of your files ? and make sure there is no BOM caracter at the begining (really utf8 and definitly never utf8bom)

**Comment by SilverMagnum** [comment]
@KevinGossentCap It appears the files are encoded in plain utf-8.
![image](https://user-images.githubusercontent.com/20430939/54463816-89a87900-4731-11e9-8e79-b302c42c9e92.png)

I think the error was associated with us having "src":"directory/src" instead of "src":"directory\\src". Now that the issue is fixed for most of my co-workers (those I could verify it with) and I think this issue has been resolved. (The person who seems to still have the issue simply deploys the package.xml.)
