### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MathNerdzRule** [celador/ForceCode#248]
- Issue Type: `Performance`
- Extension Name: `forcecode`
- Extension Version: `3.14.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Stephen.Craig\JohnAaronNelson.forcecode-unresponsive.cpuprofile.txt
[JohnAaronNelson.forcecode-unresponsive.cpuprofile.txt](https://github.com/celador/ForceCode/files/2880106/JohnAaronNelson.forcecode-unresponsive.cpuprofile.txt)
` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by daishi4u** [comment]
I haven't seen Forcecode using high CPU. Even running an intensive command like the code completion refresh the CPU doesn't get above 25 percent, then goes back down to 0 while idle. Please upgrade to 3.14.1 and see if your issue still exists
