### ISSUE TITLE
Execute Anonymous not respecting debugOnly flag set to true

### ISSUE THREAD

**Issue by hasmanytrees** [celador/ForceCode#25]
Although I changed my debugOnly flag to true when I Execute Anonymous I get the full report from Salesforce output to the console.  I tried closing and restarting VS Code, but it still did not respect the debugOnly flag being set to true.

**Comment by celador** [comment]
Thanks for the heads up.  Working on this.

**Comment by celador** [comment]
@hasmanytrees this should be resolved in 0.2.13

**Comment by hasmanytrees** [comment]
I've confirmed that this is fixes in 0.2.13.  Thanks!
