### ISSUE TITLE
ForceCode Loading...

### ISSUE THREAD

**Issue by SergiyKolochun** [celador/ForceCode#252]
- Created folder
- Opened VS Code there
- Opened `ForceCode: Menu`
![image](https://user-images.githubusercontent.com/26417553/53178795-3c862b00-35fb-11e9-950d-53443ee743e9.png)
- `src` folder, `sfdx-project.json` file created automatically
- Filled `sfdx-project.json` from prompt
![image](https://user-images.githubusercontent.com/26417553/53175690-2e351080-35f5-11e9-98ff-24ebc955a2ab.png)
- ForceCode still Loading....

- Extension Version: `3.14.1`
- OS Version: `Windows_NT x64 10.0.14393`
- VSCode version: `1.31.1`

**Comment by daishi4u** [comment]
I see in your top screenshot it's asking you to create a new org...did you. Click on that and log in?

**Comment by SergiyKolochun** [comment]
> I see in your top screenshot it's asking you to create a new org...did you click on that and log in?

Yeah, but it didn't open browser to log in, just created sfdx-project.json file with values I choose...

**Comment by daishi4u** [comment]
Are you on a vpn or using a proxy?

**Comment by SergiyKolochun** [comment]
> Are you on a vpn or using a proxy?

no..., tried to use home network but result remains the same

**Comment by daishi4u** [comment]
If you would like, you can join the beta-testing channel on the Forcecode slack and test version 3.15.0-2 the Forcecode menu command has been replaced with Forcecode create project. Try that and see if everything loads correctly

**Comment by daishi4u** [comment]
Version 3.15.0 should fix this issue for you
