### ISSUE TITLE
Lightning component code overriding alert not working

### ISSUE THREAD

**Issue by KevinGossentCap** [celador/ForceCode#254]
**Describe the bug**
I found a way to trick the actual overriding alert on lightning components.
In such case, you can have bad team code overriding.

**To Reproduce**
1. Create a simple lightning component having a cmp and a controller and have 2 users
2. Have it in both VSCode (or one VSCode and the other with SFDC dev console)
3. With user2, edit the cmp, save and compile it
4. With user1, edit the controller save and compile it
5. With user1, edit (or not) the cmp, save and compile
6. Compilation done
7. Look the code in Salesforce and see the cmp code from user1 have overriden the one from user2

**Expected behavior**
having an alert as we can have if both users edit, save and compile the same file of the lightning component

**Desktop (please complete the following information):**
 - OS: Windows
 - VSCode version 1.31.1
 - ForceCode Version 3.14.1

**Comment by KevinGossentCap** [comment]
Just right now, I also tested with ForceCode version 3.15.0-5 and the behavior is the same.

**Comment by daishi4u** [comment]
There is currently already a check in place, but if the save is within 10 seconds of the other then no notification will be shown. The reason for this is there were issues with time differences on the server vs local so I had to put a ten second leniency in place.

**Comment by KevinGossentCap** [comment]
I've just tested the 10 seconds scenario and I still see the wrong behavior.
The thing really is to have 2 people changing a different subfile of a component, save/compile (you can add a 30 seconds pause in between) and then on of the users save/compile the file edited/saved/compiles by the other one.
It result to all modifications done by the other user been overriden.

**Comment by daishi4u** [comment]
This is fixed in 3.15.1
