### ISSUE TITLE
When creating new lwc, it shows file changed dialog

### ISSUE THREAD

**Issue by sfdcnoob** [celador/ForceCode#259]
When trying to save a new LWC, it shows a dialog saying someone changed the file on server.

![Peek 2019-03-12 08-42](https://user-images.githubusercontent.com/11079913/54217787-856a2a80-44a9-11e9-9c70-8e834ec27cc0.gif)

**Comment by daishi4u** [comment]
Looks like this happens with aura components as well. Thanks for reporting!
