### ISSUE TITLE
Error while saving lwc

### ISSUE THREAD

**Issue by Marcin1112** [celador/ForceCode#263]
**Describe the bug**
I cannot deploy LWC named Testing_lwc - an error "The requested resource does not exist"

**To Reproduce**
1. Create LWC
2. Try to deploy

**Screenshots**
![image](https://user-images.githubusercontent.com/17988376/55012118-3662e000-4fe7-11e9-8b24-8ef78edd675c.png)

**Comment by daishi4u** [comment]
If this is on version 3.15.1 then upgrade to 3.15.2, as this was fixed in that version
