### ISSUE TITLE
Error when saving Apex Class

### ISSUE THREAD

**Issue by mdorus** [celador/ForceCode#264]
When I try to save an Apex class, I receive the following error. 
 s.saveApex(...).then(...).then(...).catch(...).finally is not a function

It appears that most of the time the Save still goes through to my sandbox, but sometimes it does not.

I am on 3.15.2

**Comment by daishi4u** [comment]
Could you provide any more details? Anything specific you were doing..was it a new class not in the org, or an existing one? Etc..

**Comment by mdorus** [comment]
Hello,

It occurs both for new Apex and for existing classes.  As far as additional details go, I am using a pretty vanilla VSCode setup, i haven't changed any settings beyond what's come out of the box.

**Comment by daishi4u** [comment]
What OS are you on?

**Comment by jlopezmanrique** [comment]
Hi, I have the same problem, is an existing ApexClass, the issue occurs after update to the last version.
The Developer Tools Console show this:
![image](https://user-images.githubusercontent.com/13135871/55149327-434c1480-514a-11e9-9d6a-c67546bf495d.png)

**Comment by mdorus** [comment]
Hello,

VSCode: 1.30
ForceCode 3.15.2
Mac High Sierra 10.13.6

**Comment by daishi4u** [comment]
Can one of you join the beta-testing channel and test 3.16.0-1 and let me know if that fixes it?

**Comment by mdorus** [comment]
will do, thanks!

**Comment by jlopezmanrique** [comment]
I see same error with version 3.16.0-1 from slack

**Comment by mdorus** [comment]
I also see the same error in 3.16.0-1.

**Comment by daishi4u** [comment]
Can anyone test if 3.16.0-2 fixes this issue? If not, you will at least receive a more detailed error message...

**Comment by jlopezmanrique** [comment]
Hi, same behavior with 3.16.0-2
The class is already saved on the server but an error is shown
Notification:
![image](https://user-images.githubusercontent.com/13135871/55276460-3b2fd880-52f4-11e9-8df3-510d948d3c5d.png)

Developer Tools:
![image](https://user-images.githubusercontent.com/13135871/55276457-2fdcad00-52f4-11e9-87e4-dfbf0e9e090a.png)

ForceCode output panel is empty

**Comment by mdorus** [comment]
3.16.0-3 has resolved this issue for me.  Thanks!

**Comment by daishi4u** [comment]
Good to hear! I'm going to reopen this for now until the marketplace version is released so others don't create duplicate issues.

**Comment by jlopezmanrique** [comment]
solved for me too, Thanks!
