### ISSUE TITLE
Setting org src as root causes `AuraDefinitionBundle metadata type not found in org`

### ISSUE THREAD

**Issue by vasquezstephen** [celador/ForceCode#265]
**Describe the bug**
When attempting to set the project source as a root directory I am able to retrieve metadata and deploy, however, I cannot compile and deploy specific lightning components as I receive `AuraDefinitionBundle metadata Type not found in org` error.

**To Reproduce**
1. Set src in Org settings to `.` or `../root`
2. Attempt to autocompile and save changes to any lightning component
3. Receive `AuraDefinitionBundle metadata type not found in org`

**Expected behavior**
Auto compiles on save should still work. I have tested with multiple different ways to write root and got the same result. The only way to deploy my work is manually. Which still works for some reason.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac 10.12.6 Sierra
 - VSCode version 1.32.3
 - ForceCode Version 3.15.2

**Additional context**
N/A

**Comment by daishi4u** [comment]
What reason would you have to set the src folder to '.'? I wouldn't recommend doing so for reasons that you described and because the configuration files are in this folder as well...

**Comment by vasquezstephen** [comment]
The main reason is a selfish one. My companies automated deployments look at root for the package.xml so when I have everything in `src` the deployment won't run. I ended up doing a workaround where I made my git root the package name and wrapped the forcecode project around that.

**Comment by daishi4u** [comment]
Alright guys, I have fixed the issue. If you would like to test then you can either join the #beta-testing channel on slack or download here: https://drive.google.com/open?id=1afFre2VLk0dIxl3TucVBT7oThFQHzMi_
