### ISSUE TITLE
Deploy to server (production) runs all tests - even for static resources / visual force pages

### ISSUE THREAD

**Issue by vegad** [celador/ForceCode#266]
**Describe the bug**
When deploying to production (using deploy from package.xml file) , I would like to be able to deploy without running all of the tests when just deploying a static resource or visual force page update.  Currently, all tests are run, even when they are not required by salesforce.
 
**To Reproduce**
1. Add a single page to the package.xml file.
2. use the forcecode deploy using package.xml command to deploy to a production environment
3. In the deploy status page, you can watch all of the tests run for the deploy.

**Expected behavior**
In step 3, above, the tests should be skipped as they are not required for a visual force page change.

**Desktop (please complete the following information):**
 - OS: Win 10 64 bit
 - VSCode version 1.32.3
 - ForceCode Version 3.15.2

**Additional context**
I tried setting the test settings to all of the different options and no other setup would deploy to prod but the run local tests.  This is the setting that should ignore tests on a visual force or static resource (or lightning bundle) deploy.

**Comment by daishi4u** [comment]
All you need to do is get the name of a single test class, doesn't matter which one, and put the name in the runTests input box in the org options. Then it will only run the single test when deploying. When deploying to production, running tests is required, even when just removing a component, but I believe this is on the jsforce side of things as I was never able to change this behavior

**Comment by vegad** [comment]
When using Eclipse before I switched to VSCode, I was (am still am) able to deploy visualforce pages or static resources without running the tests.  This was a big time saver.
