### ISSUE TITLE
Always prompt for overwrite on save

### ISSUE THREAD

**Issue by jgallagants** [celador/ForceCode#267]
**Describe the bug**
Since the last version of the extension I am having an "issue" while saving changes of cls and page files, do not know if it happens with other files. The prompt to overwrite the changes appears everytime, does not matter if I refreshed the files before starting to work with them. It even appears when I send the file to compile without changes. 

I am the only developer at this instance, so there is no other user messing with the files.

**To Reproduce**
1. Open a class file
2. Make changes (or not)
3. Save the file to Salesforce
4. See prompt window

**Expected behavior**
It should not appear if the one doing the changes on that file is the same user?

**Screenshots**
![image](https://user-images.githubusercontent.com/44016735/55458988-b2b08100-55ee-11e9-9d3f-ede0bd4d4e92.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.32.3
 - ForceCode Version 3.15.2

**Additional context**
It may have happened with previous version of the extension too, but as it does not prevent from working, I did not gave it too much of a thought.

**Comment by daishi4u** [comment]
The newest beta release includes a possible fix for this. You can either join the #beta-testing channel on slack or download here: https://drive.google.com/open?id=1DfX2HZRFmZ3d7fSdVZmScCUqXUx9pleE

**Comment by jgallagants** [comment]
Outstanding job. With this version the prompt seems to be fixed. Thank you very much!
