### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nikhilshringarpure** [celador/ForceCode#268]
- Issue Type: `Performance`
- Extension Name: `forcecode`
- Extension Version: `3.15.2`
- OS Version: `Windows_NT x64 10.0.10240`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\nikhil.shringarpure\JohnAaronNelson.forcecode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by nikhilshringarpure** [comment]
[JohnAaronNelson.forcecode-unresponsive.cpuprofile.txt](https://github.com/celador/ForceCode/files/3062406/JohnAaronNelson.forcecode-unresponsive.cpuprofile.txt)

Need to uninstall and re-install plug-in multiple times to get it to work. It's awesome once started, but just painful to get it to activate the plug-in after you start VS Code. Hope to have a solution soon as I do love to work with ForceCode tools within VS Code. Thanks!

**Comment by daishi4u** [comment]
Do you also have the Salesforce extensions installed? E.G. the Apex extension? I know that they can make it take FOREVER for Forcecode to start the first time...

**Comment by nikhilshringarpure** [comment]
Yes, I had. But even after uninstalling, it's the same issue. :(

**Comment by nikhilshringarpure** [comment]
I just tried removing all other extensions (Salesforce Extenstion Pack as well as Salesforce CLI Integration) that I had installed manually before installing Forcecode. But no luck.

**Comment by AntunBartonicek** [comment]
Why is this closed? Is there a know solution I'm missing because this is really making ForceCode unusable.
