### ISSUE TITLE
Search something in the entire org or retrieve all file

### ISSUE THREAD

**Issue by lioram** [celador/ForceCode#27]
Hi,

I'm testing this plugin and I would like if it's possible to retrieve All the package to do some audit stuff or if it's possible to search in the entire org with this plugin.

Regards

**Comment by lioram** [comment]
Wrong section sorry

**Comment by celador** [comment]
The plugin works best with unmanaged packages.  Create a package in your org, add what items you want to be in it, then use the Retrieve Package command to pull the unmanaged package down in its entirety.  

If you do not want to create a package, the plugin can currently open individual files, such as Classes, Triggers, Components, and Pages.  I intend to add more metadata types to the Open command in the near future.

If you want to interactively build an arbitrary package.xml file and not do it from your org, your current best bet is to use MavensMate.  I will be adding the ability to retrieve based on your local package.xml in the near future, but I don't anticipate building an interactive UI for that as Salesforce and MavensMate have that pretty much nailed down.
