### ISSUE TITLE
Expired access/refresh token when Diff command is used

### ISSUE THREAD

**Issue by RandallFlagg** [celador/ForceCode#270]
**Describe the bug**
Every day when I come to start working on the org If the first thing I do is save to the ORG then a login is performed and everything works great.

If the first thing I try to do is Diff then I get the "Expired access/refresh token" message

**To Reproduce**
In the description

**Expected behavior**
The org will log in automatically

**Desktop (please complete the following information):**
 - OS: [Windows 10 x64 17134.677]
 - VSCode version [1.33.0]
 - ForceCode Version [3.15.2]

**Comment by daishi4u** [comment]
This is fixed in version 3.16.0-7 and can be downloaded via the beta-testing channel in the ForceCode slack group.

**Comment by RandallFlagg** [comment]
This release solved this issue but after connecting and showing the diff a message is shown saying: 

> Illegal value for `line`

Will test with 3.16.0-8 and update

**Comment by RandallFlagg** [comment]
@daishi4u @celador  Thanks for fixing
