### ISSUE TITLE
Issue in Connection to salesforce org

### ISSUE THREAD

**Issue by sparshgarg174** [celador/ForceCode#271]
Hi ,
post recent updates in march the Forcecode isn't able to launch the window to make a connection to any org. Previously that use to be the first step in using forcecode. Now i am trying to create a a project then it is expected to launch the org connection menu but it doesn't seem to launch either.
i even tried log in to org option but that's throwing an error too.
I did check the description of extension and followed the same steps. getting the same issue. Either i am doing something wrong, not sure.

Hope you can help on this.

**Comment by daishi4u** [comment]
Can I get some screenshots and exact steps you are taking please?

**Comment by sparshgarg174** [comment]
Hi,
Thanks for replying. The issue right now is when i create project using force code it generates 2 files and a folder named src. the rest of the folders (.vscode, .sfdx) takes a lot of time to generate if at all. Then the subsequent step is to get a popup to connect to your org. but that doesn't seem to appear at all. i tried hitting the same commands around 10 times and it sort of worked only 1 randomly for me.
i don't know what went wrong either updating the forcecode extension in march or updating my VSCode from 1.31 to 1.33.Its just that i heavily relied on forcecode for my project work as i don't want to migrate to sfdx yet.
Regards,Sparsh
    On Thursday, 18 April, 2019, 4:04:07 AM IST, Brett Wagner <notifications@github.com> wrote:  
 
 
Can I get some screenshots and exact steps you are taking please?

**Comment by daishi4u** [comment]
The reason it takes so long to generate the vscode and .sfdx folders is because they are generated via the salesforce extensions and sometimes those extensions will slow down the initial start of Forcecode. If you wait, the process is automatic once the folder opens after running the create project command. Like I stated, it can take a while with the salesforce extensions installed.

**Comment by sparshgarg174** [comment]
I was doing my own hit and trials.. the problem isn't the creation of the 2 new folder its that post creating them it doesn't display the option to connect to desired org/sandbox any more. I am finding this problem more to be due to the latest update of vscode(1.33). As i tried running it on (1.31) yesterday and though it took some time it sort of worked as expected.On 19-Apr-2019 08:04, Brett Wagner <notifications@github.com> wrote:The reason it takes so long to generate the vscode and .sfdx folders is because they are generated via the salesforce extensions and sometimes those extensions will slow down the initial start of Forcecode. If you wait, the process is automatic once the folder opens after running the create project command. Like I stated, it can take a while with the salesforce extensions installed.

**Comment by daishi4u** [comment]
Strange, I can't seem to reproduce this, even with vscode 1.33.1. What Os are you on?

**Comment by sparshgarg174** [comment]
I am currently using windows 10. I took the org files that got generated when my org got connected in 1.31 and pasted them in 1.33 folder to get a temporary fix. It is sort of a temporary fix for me but my team mates aren't so lucky to get their desired org connected through force code. They have the same specifications as me. Hope we get a fix in the next update.On 20-Apr-2019 08:45, Brett Wagner <notifications@github.com> wrote:Strange, I can't seem to reproduce this, even with vscode 1.33.1. What Os are you on?

**Comment by daishi4u** [comment]
Please refer to issue #279
