### ISSUE TITLE
Code Coverage not Updating after Testing Apex Classes

### ISSUE THREAD

**Issue by stephendevelops** [celador/ForceCode#272]
**Describe the bug**
After running all Apex Tests, followed by checking the updated code coverage, does not update the overall code coverage and still shows classes not covered.

I was able to find a way to make it work but I feel like it is not the intended result.
Steps to workaround:
1. On the Apex Tab Click Run Tests.
2. Go to the Salesforce Developer Console and find the test package that just ran.
3. Select test package that was run. Click Test > ReRun.
4. Go Back to VSCode > ForceMenu > Get current overall code coverage.

**To Reproduce**
1. Run Tests in VSCode
2. Click  ForceMenu > Get current overall code coverage.
3. Code coverage is not updated

**Expected behavior**
I would like to be able to just click run tests in VSCode then Get Code Coverage and get the updated code coverage.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Mac 10.12.6 Sierra
- VSCode version 1.32.3
- ForceCode Version 3.15.2

**Additional context**
N/A

**Comment by daishi4u** [comment]
What are you using to run tests? This sounds like you're using the salesforce extension to run tests and not Forcecode... To run a test class in Forcecode, hover over an @isTest or testMethod word in the class and you'll see a pop up from Forcecode allowing you to run the tests for that class

**Comment by stephendevelops** [comment]
You're right. I was not using force code to Run all my test. 
However, When I go and click Run All Tests which on the Test Class, and then click Get Overall Code Coverage again. The coverage does not update but the tests pass. 
I also get the following error after Get Overall Code Coverage:
![Screen Shot 2019-04-17 at 10 21 53 AM](https://user-images.githubusercontent.com/9055351/56300223-28424400-60fb-11e9-8758-4a9dc48de0c3.png)

**Comment by daishi4u** [comment]
Did you click run all tests... Or did you hover over an @isTest, then click run tests in the hover that is presented? The links included in the classes... Run all tests and run test that are above the methods are from the salesforce extension as well

**Comment by stephendevelops** [comment]
Yes. I tried both clicking the hover prompt for Run Test and Run All Tests.

**Comment by daishi4u** [comment]
So when a test class is run, test coverage for that class that the test class is testing is updated automatically. If you click the cloud icon on the left sidebar, then you will see the coverage info split into different sections (Sufficient, Not Sufficient, etc). Getting the overall coverage is supposed to download a file with coverage information for all classes in the org. Not sure at the moment why you get the error with that, but that's a separate issue. Can you verify you see the coverage in the Forcecode view (described above)?

**Comment by stephendevelops** [comment]
I repeated the steps you described. 
I have a class that is listed as `No Coverage Data` 
But I have two tests that directly relate to it. I did the forcecode test run and the code coverage did not update, and when I did get overall coverage I got the same error and no file downloaded

**Comment by stephendevelops** [comment]
I also just tested the same class doing the work around I described above and now it shows the Code Coverage.
Idk what's causing the issue.

**Comment by daishi4u** [comment]
Please make sure your src option in the org settings is pointing to the directory with your classes as well

**Comment by stephendevelops** [comment]
Yes that's pointing at the correct src.
To confirm, When I click the hover prompt for `Run All Tests` it kicks off Salesforce CLI and saves to results in `.sfdx/tools/testresults/apex`
The tests are running and passing and failing fine. Just the code coverage does not update

**Comment by daishi4u** [comment]
If you are getting results in that folder then you're not using the Forcecode way of testing. Give me about ten minutes and I'll get a few screenshots upload for you 😁

**Comment by daishi4u** [comment]
![image](https://user-images.githubusercontent.com/6629523/56325366-9278da00-6137-11e9-9505-a89820afc6b0.png)
![image](https://user-images.githubusercontent.com/6629523/56325383-a3c1e680-6137-11e9-9a43-3454407309c2.png)

**Comment by stephendevelops** [comment]
I think I figured it out. 
I had an additional salesforce extension that was giving me a similar hover prompt to run all tests.
But now that I've ran both I can see that I was NOT running the ForceCode version before.
Thanks for helping me debug this!

**Comment by daishi4u** [comment]
You're welcome! Happy to help

**Comment by stephendevelops** [comment]
For reference I was clicking this Run All Tests
![Screen Shot 2019-04-17 at 5 40 33 PM](https://user-images.githubusercontent.com/9055351/56325480-f8656180-6137-11e9-8aae-273323c09d9b.png)

Instead of this one
![Screen Shot 2019-04-17 at 5 40 39 PM](https://user-images.githubusercontent.com/9055351/56325489-01eec980-6138-11e9-9eea-6a2fdc9a9e51.png)
