### ISSUE TITLE
ForceCodePreview Visualforce Page Not Operational

### ISSUE THREAD

**Issue by cmeflygtp** [celador/ForceCode#273]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - VSCode version [e.g. 1.29.0]
 - ForceCode Version [e.g. 3.10.3]

**Additional context**

**Comment by cmeflygtp** [comment]
**Bug Description**
ForceCodePreview Visualforce Page Not Operational

**To Reproduce**
Open a VF Page and either click the preview icon in the top right OR right-click and then select the ForceCode Preview Visualforce Page

**Expected Behavior**
To open a preview of the VF page you are working on.

**Screenshots**
Not Relevant

**Desktop**

- OS - Windows 10 Pro Build 17134.706

- VSCode version  1.33.1

- ForceCode Version 3.15.2

**Comment by daishi4u** [comment]
Is your src setting configured to the folder where your source files are located?

**Comment by cmeflygtp** [comment]
So, I will be honest here; I am really new to using VS Code and ForceCode. I used to just use the CLI and a text editor to do development (because I was used to developing this way). When I began this particular project I created the project using ForceCode which created the file structure. When I look at the settings.json file for this project this is what the setting looks like; "src": "src"
When I decided to change it to "src": "D:\\repo\\**this project folder**" ForceCode failed to load so, I put this back to "src": "src"
Maybe, I am missing something. Thanks for your help. It has worked in the past without me changing any of the json.

**Comment by daishi4u** [comment]
It is a relative path, that's why the default is src. So to see it in action, click the Forcecode menu on the bottom left, then go to Open and select some files. They will download into that directory. Only files in that directory will work with Forcecode commands

**Comment by daishi4u** [comment]
And you don't need to open the settings.json file, there is an editor built in. Go to the Forcecode menu, then Org Settings...

**Comment by cmeflygtp** [comment]
then, yes the file is in the correct folder.
