### ISSUE TITLE
Extension causes high cpu load + can't use extension

### ISSUE THREAD

**Issue by chamartt** [celador/ForceCode#274]
- Issue Type: `Performance`
- Extension Name: `forcecode`
- Extension Version: `3.15.2`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Tom\JohnAaronNelson.forcecode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

-----------------
I have only Compile & Create projet fonctionnality and they doesn't works.... : command not found

**Comment by daishi4u** [comment]
Start with the create project command. If you have official salesforce extensions installed then it can take quite a while to start the first time, just be patient and let it go and you'll see a box pop up asking to either log into an existing org or a new one

**Comment by chamartt** [comment]
Thank you, it's work now.

**Comment by chamartt** [comment]
It's is not possible to use the extension for past project from another older version ? It is necessary to create project only to use the extension ?

**Comment by chamartt** [comment]
When I create project on existing folder like git repositery, i can't connect it with a Salesforce org : command Force login not found

**Comment by chamartt** [comment]
A file force.json have been created but i can't use any command of the extension

**Comment by daishi4u** [comment]
If you have an existing project that was used before with Forcecode and it has the force.json file in the folder then it will auto load Forcecode when you open that folder

**Comment by chamartt** [comment]
Yes, sometimes the ask for log with new or old org don't appear fastely, but it's work; thank you for your help again !
