### ISSUE TITLE
Forcecode hangs when there is a failed login attempt.

### ISSUE THREAD

**Issue by mikeflemingcfs** [celador/ForceCode#275]
**Description**
When logging in to an org, if there is a problem with the OAuth login, you cannot abort the executing task in VSC.
**To Reproduce**
1. Go to 'VSC'
2. Click on 'ForceCode login'
3. Scroll down to 'Login to an Org'
4. On the Salesforce login screen, do not complete the process
5. Return to VSC and try to abort the Executing Task

**Expected behavior**
In this particular scenario I had password login problems, so wanted to switch to a different sandbox.  However, as a Logging In running task was executing I lose the ability to do anything else.

**Screenshots**
![Screen Shot 2019-04-23 at 16 58 18](https://user-images.githubusercontent.com/45431594/56597170-d19ca480-65e9-11e9-8975-c06da9860a65.png)

**Desktop (please complete the following information):**
 - OS: MacOS Sierra 10.13.5
 - VSCode version 1.33.1
 - ForceCode Version 3.15.2

**Additional context**

**Comment by daishi4u** [comment]
This goes along with adding cancellation to tasks #186 This will actually be 'fixed' in the 3.17.0-3 beta release

**Comment by daishi4u** [comment]
Fixed in 3.17.0
