### ISSUE TITLE
Automatic upgrade to lastest version

### ISSUE THREAD

**Issue by rendall** [celador/ForceCode#278]
**Describe the bug**
The extension appears to upgrade itself automatically, irrespective of the wishes of the user.

**To Reproduce**
1. Install ForceCode extension
1. Click the 'manage' icon in the extensions window
1. Select `Install another version` 
1. Select any other version, e.g. `3.15`
1. After install, extension will upgrade to latest

**Expected behavior**
The installation should stay at the requested version

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 10 x64
 - VSCode version [e.g. 1.29.0] 1.33.1
 - ForceCode Version [e.g. 3.10.3] 3.16

**Comment by daishi4u** [comment]
This isn't an issue on my end... Would be on vscode
