### ISSUE TITLE
ForceCode extension hangs at 'Forcecode loading...' message

### ISSUE THREAD

**Issue by rendall** [celador/ForceCode#279]
**Describe the bug**
The 'ForceCode loading...' message shows and does not progress.

**To Reproduce**
This happens in all projects, new and old, whether other extensions are installed or not, but this will give a bare-bones view:
1. Open new project in VSCode
1. Select command 'ForceCode: Create Project'
1. Select the project's folder
1. Observe that this is the project structure:
  * force.json
  * sfdx-project.json
  * src/ {empty}
1. Nothing else happens, so restart VSCode
1. Select 'New Org'
1. Select anything from the next dropdown (e.g. 'Sandbox / Test')
1. Select either 'Yes' or 'No' (to 'automatically deploy code...')
1. Nothing else.  'Forcecode loading...'

**Expected behavior**
My colleague expects a browser window to open at 'New Org', and the 'ForceCode loading...' message to be replaced by a menu button.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] `Windows 10 x64 (10.0.17763)`
 - VSCode version [e.g. 1.29.0] `1.33.1`
 - ForceCode Version [e.g. 3.10.3] `3.16.0`

**Additional context**

**Comment by rendall** [comment]
It is very similar to Issue #252

**Comment by rendall** [comment]
I cloned the ForceCode repo and ran the extension in debug mode.  This exception appears:

```
Exception has occurred: Error
Error: listen EACCES 127.0.0.1:1717
	at Server.setupListenHandle [as _listen2] (net.js:1313:19)
	at listenInCluster (net.js:1378:12)
	at GetAddrInfoReqWrap.doListen [as callback] (net.js:1492:7)
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:55:10)
```

Does anyone know what ForceCode or its dependency is looking for at that local address?

**Comment by rendall** [comment]
I also get various debug messages, such as the following:
```
{"message":"No org configuration found for name rendall-username","status":1,"stack":"NoOrgFound: No org configuration found for name rendall-username\n\tat _buildNoOrgError (c:\\workspace\\projects\\ForceCode\\node_modules\\salesforce-alm\\dist\\lib\\scratchOrgApi.js:103:27)\n\tat getConfig.resolveDefaultName.then.then.srcDevUtil.getGlobalConfig.then.then.catch (c:\\workspace\\projects\\ForceCode\\node_modules\\salesforce-alm\\dist\\lib\\scratchOrgApi.js:509:39)\n\tat tryCatcher (c:\\workspace\\projects\\ForceCode\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n\tat Promise.module.exports.Promise._settlePromiseFromHandler (c:\\workspace\\projects\\ForceCode\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n\tat Promise.module.exports.Promise._settlePromise (c:\\workspace\\projects\\ForceCode\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n\tat Promise.module.exports.Promise._settlePromise0 (c:\\workspace\\projects\\ForceCode\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n\tat Promise.module.exports.Promise._settlePromises (c:\\workspace\\projects\\ForceCode\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n\tat Async._drainQueue (c:\\workspace\\projects\\ForceCode\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n\tat Async._drainQueues (c:\\workspace\\projects\\ForceCode\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n\tat Immediate.Async.drainQueues [as _onImmediate] (c:\\workspace\\projects\\ForceCode\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n\tat runCallback (timers.js:696:18)\n\tat tryOnImmediate (timers.js:667:5)\n\tat processImmediate (timers.js:649:5)","name":"NoOrgFound","warnings":[],"action":"Run the \"sfdx force:auth\" commands with --setdefaultusername to connect to an org and set it as your default org.\nRun \"force:org:create\" with --setdefaultusername to create a scratch org and set it as your default org.\nRun \"sfdx force:config:set defaultusername=<username>\" to set your default username."}
dxService.js:105
```

**Comment by daishi4u** [comment]
Are you using a proxy or anything?

**Comment by rendall** [comment]
No.

I think some service that serves from localhost:1717 isn't starting. I'm
trying to find out more about that service.

**Comment by rendall** [comment]
I am actively tracking down this bug. When I find the answer, I'll let you know here and we can discuss a PR if that makes sense to you.

**Comment by daishi4u** [comment]
The service at localhost:1717 is from SFDX, it's what is used to log in and run DX based commands through Forcecode...

**Comment by daishi4u** [comment]
You can change the port number in the sfdx-project.json file via the oauthLocalPort property. To learn more: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm 

Let me know if that works, as something else on your computer may be trying to use port 1717

**Comment by rendall** [comment]
Thanks, Brett.

I did try that, and it fails no matter which port, and I double-checked
that 1717 is not being used for anything. It's definitely that the service
is not starting.

**Comment by rendall** [comment]
That said, if you want to close this off your issues list, I understand.
It's not a ForceCode issue. When I learn more I'll add my conclusions here
even if it's closed, so that it will help the next person.

**Comment by rendall** [comment]
Hi @daishi4u 

OK, a workaround has been discovered, thanks to one @DFKA at forcedotcom/salesforcedx-vscode#1296

With respect to this ForceCode extension, perhaps a timeout error would help?  Anyway, thank you for your patience.

**Comment by rendall** [comment]
To help anyone referencing this issue,  he are the important bits for the workaround:

type `netsh interface ip show excludedportrange protocol=tcp` into your terminal which lists a series of port ranges. Find a port _not_ in the list, and add it as the value to a `oauthLocalPort` field on the root level object of `sfdx-project.json`

**Comment by EdgarsEv** [comment]
Hi, 

I have similar issue, but it's a bit challenging to work-around it.
when new Project in VS Code with ForceCode, the following error:
{
	status: 1,
	name: PortInUse,
	message: Cannot start the OAuth redirect server on port PortInUseAction.,
	exitCode: 1,
	actions: 
	{
		0: Kill the process running on port 1717 or use a custom connected app and update OauthLocalPort in the sfdx-project.json file.,
	},
	commandName: AuthWebLoginCommand,
	stack: PortInUse: Cannot start the OAuth redirect server on port PortInUseAction.
    at Function.create (C:\Users\edgars\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\@salesforce\core\lib\sfdxError.js:141:16)
    at Object.startOauth (C:\Users\edgarss\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\auth\webAuthListener.js:186:44)
    at process._tickCallback (internal/process/next_tick.js:68:7),
	warnings: 
	{
	},
}
Cannot start the OAuth redirect server on port PortInUseAction.

<img width="722" alt="portInUse_IssueForNewProject" src="https://user-images.githubusercontent.com/36496889/72977254-cd9ded00-3ddc-11ea-82e6-b5bb0ae67c37.png">


netsh interface ip show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port      
----------    --------      
        80          80      
      5357        5357      
      5985        5985      
      8000        8000      
     47001       47001      

* - Administered port exclusions.

so 1717 is not used, or is eligeble to be used.?

if NewProject has no file: sfdx-project.json
Find a port not in the list, and add it as the value to a oauthLocalPort field on the root level object of sfdx-project.json

it's not clear what keys : values should be added, as it is not enough to add only : oauthLocalPort : <some no 1717 port number?>

Tried to kill node.js process ( which was identified as portInUse root cause ) several times, but once NewProject action re-started, that node.js process again was in place.

There was a workaround for colleagues: 
authorization was done on different PC, and then connections .json files copied to this "problematic" pc
place sanbox.connection.json file under /user/sfdx folder?
and another .json ( I can't recall it now) 

Just wanted to find out is the connection copy the right solution!
As it is working and now colleagues can at least retrieve changed meta-data from the Sandbox ( server ), then it seems to be a working solution.

Do you have another comment on this?
Looking forward your response.

Kind regards

**Comment by EdgarsEv** [comment]
@rendall 
Just FYI: I gave up killing port for 1717, and I red some other issue, that user did change default app browser to smth like MS Edge.
Unbelievable, but it solved this issue: Cannot start the OAuth redirect server on port PortInUseAction.
GoogleChrome didn't start, but Edge did. 
Weird issue.
Sorry for too many words.
Kind regards
