### ISSUE TITLE
Never prompts for diff/overwrite on save for Lightning Web Components

### ISSUE THREAD

**Issue by jotraverso** [celador/ForceCode#280]
**Describe the bug**
Never prompts for overwrite on Lightning Web Components, it always overwrite the JS, HTML or CSS file.

The Diff option from ForceCode Menu may be used as WA in the meanwhile.

**To Reproduce**
1. Take two different users; user1 and user2
2. With user1, open a Lightning Web Component JS file
3. Type some comments
4. Right button -> ForceCode: Save/Compile/Deploy
5. With user2, different folder or different workstation
6. With user2, open the same Lightning Web Componen JS file
7. Type some comments
8. Right button -> ForceCode: Save/Compile/Deploy

It should prompts for differences between server and local, as it does with Apex

**Expected behavior**
1. Take two different users; user1 and user2
2. With user1, open a Lightning Web Component JS file
3. Type some comments
4. Right button -> ForceCode: Save/Compile/Deploy
5. With user2, different folder or different workstation
6. With user2, open the same Lightning Web Componen JS file
7. Type some other comments
8. Right button -> ForceCode: Save/Compile/Deploy
9. Prompts for see Diff or Ovewrite

**Screenshots**
Do not have screenshots

**Desktop:**
 - OS: Windows
 - VSCode version 1.33.1
 - ForceCode Version 3.15.2, 3.16.0 at least

**Additional context**
No addition context

**Comment by daishi4u** [comment]
Fixed in 3.17.0
