### ISSUE TITLE
"The current file could NOT be found in the org" error

### ISSUE THREAD

**Issue by RandallFlagg** [celador/ForceCode#281]
**Describe the bug**
I open a folder I didn't use for a while and wanted to do a diff with the org. The compare view opened but on the left window(i.e. the REMOTE) I see the message 

> The current file could NOT be found in the org

**To Reproduce**
1. Not sure yet. Will update if I will find

**Expected behavior**
The Left window shows me what is in the ORG

**Screenshots**
![image](https://user-images.githubusercontent.com/434681/57230623-70c98f00-7021-11e9-88ff-f6c7725fb90f.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 x64 Build 1803]
 - VSCode version [1.33.1]
 - ForceCode Version [3.16.0]

**Additional context**
**Update1:**
I tried to logout and log in. I got the following message in the browser after the login: 

> We can't authorize you because of an OAuth error. For more information, contact your Salesforce administrator.
> 
> OAUTH_APPROVAL_ERROR_GENERIC : An unexpected error has occured during authentication. Please try again.

**Update 2:**
I wasn't able to try and log again as the sub menu "log in" was showing but it didn't launch my browser. I reloaded the window. logged in. diffed the file. it worked.

**Comment by daishi4u** [comment]
Have you been able to reproduce this?
