### ISSUE TITLE
Default Test Execution in Production

### ISSUE THREAD

**Issue by trujillh** [celador/ForceCode#283]
**Describe the bug**
The Test options for production don't allow us to deploy Non-Apex changes without running tests. As stated in the Metadata API Developer Guide [Here](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy_running_tests.htm) the default behavior is to not have test run for non-Apex classes.

**To Reproduce**
Deploy a single staticresource, visualforce page, or other Non-Apex code change to Production.

**Expected behavior**
It should validate the deployment without needing to run all of the tests. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.34.0
 - ForceCode Version: 3.16.0

**Additional context**
I believe their should be a "Default" option to select from the testLevel option.

**Comment by daishi4u** [comment]
Please reference my comment here #266
