### ISSUE TITLE
Forcecode fails to login to the Org if we login flows

### ISSUE THREAD

**Issue by naveenila1221** [celador/ForceCode#286]
**Describe the bug**
Forcecode fails to login to the Org if we login flows

**To Reproduce**
1. Setup login flows in the org for your profile
2. Go to 'ForceCode Menu'
3. Click on 'New Org'
4. You will be navigated to login page
5. Login with your credentials
6. Complete the login flow
7. See error

**Expected behavior**
Force code should establish a session with Salesforce Org to work with.  

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.26.1
 - ForceCode Version v3.16.0

**Additional context**

**Comment by daishi4u** [comment]
Do you also use the salesforce cli? If so, are you able to authenticate an org via the cli login?

**Comment by bmenendezaMinsait** [comment]
Hi,

I have the same issue, when I try to login using force code the browser login window opens but an ERR_EMPTY_RESPONSE error appears.
I have CLI installed on my local, even when I try to login via CLI I get an error: 'ERROR running force:auth:weblogin: read  ECONNRESET'

Version used:
VS Code: 1.35.1
ForceCode: v3.17.1

The issue started when the force code updated to the current version, previously it was working correctly.

thanks in advance,
Beatriz

**Comment by daishi4u** [comment]
@bmenendezaMinsait can you please file the issue with the salesforce cli? The cli handles the login side of Forcecode.

**Comment by bmenendezaMinsait** [comment]
Thanks, I will
