### ISSUE TITLE
When creating a new project in an already open folder, the extension doesn't load

### ISSUE THREAD

**Issue by RandallFlagg** [celador/ForceCode#287]
**Describe the bug**
When creating a new project a restart of the window is required otherwise the extension doesn't load

**To Reproduce**
1. Create a new force code project

**Expected behavior**
Prompt to connect to a new or existing ORG

**Desktop
 - OS: [Windows 10 x64]
 - VSCode version [1.35.0]
 - ForceCode Version [3.16.0]

**Comment by daishi4u** [comment]
Does the extension not auto restart the window after you create a project?

**Comment by RandallFlagg** [comment]
@daishi4u please reopen.
I would prefer the extension won't restart the window.
I would like it to connect me to the relevant ORG and to setup the _**.forceCode**_ directory.

What actually happens is nothing. I need to go to the command palette and choose **_Developer: Reload Window_** and then everything works like expected(Choosing the ORG and creating the .forceCode directory)

**Comment by daishi4u** [comment]
When you use the Forcecode create project command, the extension will reload vscode by itself, or at least that is the intended functionality.

**Comment by daishi4u** [comment]
The folder you select as your project folder cannot be one that you already have open with vscode, otherwise I bet I leads to the issue you are facing

**Comment by daishi4u** [comment]
I believe I know of a way to fix it. Going to change the title of the issue and reopen. Thank you

**Comment by daishi4u** [comment]
Fixed in 3.18.0
