### ISSUE TITLE
Exactly how does "Retrieve Package" work?

### ISSUE THREAD

**Issue by indyHarcourt** [celador/ForceCode#29]
How does "Retrieve Package" work?  What format is the package? Naming standard? How does one create a Package?  Can you automate the creation of a package ("Create Package" menu option?)  If I retrieve a package, can I then save a package?

Documentation would be somewhat helpful.

Thanks!

**Comment by celador** [comment]
@indyHarcourt Retrieve Package first requests the package names from your org using a non-standard SF endpoint.  It then uses the names to prompt you for which package you'd like to retrieve.  The extension then uses the metadata api and retrieves the package by name, without using a package.xml file.  The package is defined in your org, not your machine.
