### ISSUE TITLE
Error start : nothing happens

### ISSUE THREAD

**Issue by chamartt** [celador/ForceCode#292]
Hello,
Since last week, I can't use the extension because it doesn't start.
Nothing is present in the bottom bar, next to Live Share or other things like this.

**To Reproduce**
1. Ctrl + Maj + P --> ForceCode: ForceCode Menu
2. ForceCode: Executing 1 Task(s) appears
3. Select existing org that worked 
4. ForceCode: Executing 1 Task(s) disappears
5. Nothing happens more

**Desktop :**
 - OS: Win 10
 - VSCode version 1.32.3
 - ForceCode Version 3.17.1

Thank you for your help

![image](https://user-images.githubusercontent.com/15814545/60436071-8b784880-9c0b-11e9-9328-c931e60e4636.png)

**Comment by daishi4u** [comment]
Do you have the sfdx cli installed?

**Comment by chamartt** [comment]
This one : Salesforce CLI Integration by Salesforce ? No.

**Comment by chamartt** [comment]
I've just seen your note in the Readme, just tell me if it's Salesforce's extension or James Boggs's one !
Thank you

**Comment by daishi4u** [comment]
You need to install the cli from https://developer.salesforce.com/tools/sfdxcli

**Comment by chamartt** [comment]
Thank a lot !

**Comment by daishi4u** [comment]
You're welcome 😀

**Comment by chamartt** [comment]
The problem is still present....
![image](https://user-images.githubusercontent.com/15814545/60445793-385cc080-9c20-11e9-8172-727171c16900.png)

**Comment by daishi4u** [comment]
Please verify that you can run the command sfdx force:auth:web:login -r https://test.salesforce.com in a command prompt

**Comment by rajavardhan2geek** [comment]
@daishi4u 
Same issue is happening with me. I had SFDX CLI Installed 
VS CODE Version 1.35.1
ForceCode 3.17.1

**Comment by daishi4u** [comment]
@rajavardhan2geek can you verify you can run the command I showed above?

**Comment by rajavardhan2geek** [comment]
Hi,

Got it First we need to login to Sfdx then use force code right

**Comment by daishi4u** [comment]
Shouldn't have to use the command first, that is just the exact command Forcecode uses to login, so if that works then there shouldn't be any reason Forcecode wouldn't

**Comment by rajavardhan2geek** [comment]
So You're saying that we should not use SFDX command for using ForceCode.
But In above comments You said Force Code should be installed along with
sfdx cli .

**Comment by chamartt** [comment]
Hi @daishi4u ,

Where I have to run this command : force:auth:web:login -r https://test.salesforce.com ?
![image](https://user-images.githubusercontent.com/15814545/60496351-e7e27300-9cb2-11e9-8e7a-26910e985b57.png)

Thank you for your help

**Comment by daishi4u** [comment]
@chamartt you need to put sfdx before force:

@rajavardhan2geek no you need to have the cli installed. All I'm saying is you shouldn't need to manually run the command before starting the extension because Forcecode runs the same command when it starts

**Comment by rajavardhan2geek** [comment]
Then forcecode is not activating properly on loading of project

**Comment by daishi4u** [comment]
It activates properly on both my windows 10 machines. Is it doing it for you when opening an existing project or creating a new one?

**Comment by rajavardhan2geek** [comment]
on creating new project

**Comment by chamartt** [comment]
@daishi4u , same issue : command sfdx is not recognize
![image](https://user-images.githubusercontent.com/15814545/60511833-3869c880-9cd3-11e9-9ee8-ef3e8a1d092c.png)

Thank again for your help

**Comment by daishi4u** [comment]
@chamartt then you need to install the cli from the link I provided before. After installing, you need to restart vscode as well. 

@rajavardhan2geek I created a fresh a couple of fresh projects and didn't run into any issues. Is the browser being open to ask you to login, or are you selecting an org you're already logged into?

**Comment by rajavardhan2geek** [comment]
Browser is not open for login . Its new org to login  .if I login with SFDX
, then ForceCode shows connected with new org .

**Comment by daishi4u** [comment]
@rajavardhan2geek so Forcecode doesn't open a browser, but if you run the command manually then it does?

**Comment by rajavardhan2geek** [comment]
I had installed Sfdx extension on Vscode
So I run Sfdx extension on  Vscode then forcecode activates

**Comment by manthrayilsubin** [comment]
same issue here..It used to work..Installed CLI from sf and then clicking on force code and org nothing happens.No browser window opens and the force code menu at the bottom disappears..trying to figure out for hours now :(

**Comment by daishi4u** [comment]
@manthrayilsubin sounds like that could be a cli issue. Run the command sfdx update to update the cli and see if the issue persists

**Comment by daishi4u** [comment]
Also, @chamartt @manthrayilsubin @rajavardhan2geek make sure that the salesforce cli is in your windows path variable. Here is some info https://salesforce.stackexchange.com/questions/163795/sfdx-is-not-recognized-as-an-internal-or-external-command

**Comment by manthrayilsubin** [comment]
Hi thank you for the reply.. I have installed the latest version of cli and
code.. While installing cli integration extension  it was stuck at
installing.. That can be an issue?

Thank you
Subin Babu

**Comment by rajavardhan2geek** [comment]
Sfdx is already in windows path

**Comment by manthrayilsubin** [comment]
Hi
I uninstalled CLI and reinstalled CLI to fix this issue..Thank you for the
help

Appreciate your help.

Thank you
Subin Babu
Phone +91 828 1430 114
manthrayilsubin@gmail.com
EWT - OurCompany
Tie Line  280 / 281
'Perfect Customer Experience Every Time'

**Comment by frizz2310** [comment]
Having the same problem with 3.17.2 in vscode 1.36.0 on MacOS 10.14.5.  The extension never loads no matter the project used.  Reinstalled the extension and the CLI with no success.  Installed version 3.17.1 and it corrected the issue.
