### ISSUE TITLE
Components not retrieved using package.xml

### ISSUE THREAD

**Issue by junaidpkhader** [celador/ForceCode#293]
When I am trying to retrieve components using package.xml, Nothing is getting retrieved. I am storing package.xml inside the src folder

**Comment by daishi4u** [comment]
You most likely are trying to retrieve too much. If the package is over a certain size or 10,000 components it will fail. Do a quick test in the workbench and see if it succeeds and let me know. Haven't found a super reliable way to retrieve. Another question, are you letting it sit for a while? Retrieves can take upwards of 5 or 10 minutes sometimes
