### ISSUE TITLE
updated VSCode to version 1.36 and the forceCode stopper working

### ISSUE THREAD

**Issue by abdokhaire** [celador/ForceCode#297]
I get this error when trying to create a new project after updating VS Code to 1.36
command 'ForceCode.createProject' not found
To Reproduce :
Upgrade CSCode to v1.36
Ctrl + Shift + P --> ForceCode: Create Project
Error command 'ForceCode.createProject' not found

Desktop :
OS: Win 10
VSCode version: 1.36
ForceCode Version: 3.17.2
SDFX Version: sfdx-cli/7.14.0-bd96f098e0 win32-x64 node-v10.15.3

**Comment by abdokhaire** [comment]
This issue related to sfdx not able to login using the port 1717

**Comment by abdokhaire** [comment]
Downgrading to VSCode v1.35 fixed the problem

**Comment by steinwinde** [comment]
Whereas the 3.17.1 has a directory .vscode\extensions\johnaaronnelson.forcecode-3.17.1\dist , the dist directory is missing in 3.17.2 - and so is dist\src\extension.js . Adding the missing extension.js and the missing directory makes the 3.17.2 work (although I got exceptions in the Developer Tools).

**Comment by steals** [comment]
@abdokhaire Is there an easy way to downgrade plugin to 3.17.1 ?

**Comment by steals** [comment]
Ok, figured it out. Looks like 3.17.1 and VSCode v 1.36 works fine.

**Comment by daishi4u** [comment]
Thanks for reporting this. 3.17.3 is on the way very soon with a fix for this issue

**Comment by abdokhaire** [comment]
@steals your solution is easier than downgrading VS Code and it worked for me as well.

**Comment by daishi4u** [comment]
@abdokhaire @steals @steinwinde upgrading to 3.17.4 will fix the issue. You may need to restart vscode to see the update and will need to restart it once the update has been installed
