### ISSUE TITLE
not working on retrieving the code from org

### ISSUE THREAD

**Issue by iamnicwu** [celador/ForceCode#3]
Hi,
just want to try VS code for salesforce developing, but when downloaded the forcecode plugin, I cannot retrieve the code from org. below is the error message it shown.
 
No handler found for the command: 'ForceCode.exportPackage'. An extension might be missing an activation event.

**Comment by celador** [comment]
@iamnicwu  Are you using Windows?

**Comment by celador** [comment]
@iamnicwu Please update the extension and try again.  I have recently updated the extension for better behavior in Windows.
