### ISSUE TITLE
Not able to configure New Org

### ISSUE THREAD

**Issue by pothukuchiaditya** [celador/ForceCode#300]
**Describe the bug**
Tried to configure new org but it is not opening the new org in the browser to login like how it has to do. I added orgs earlier without any issue. But when i tried to configure a new org when the browser opened automatically i closed that browser. After that the browser never opened/opening when i try to configure new org.

**To Reproduce**
1. Run >ForceCode:ForceCode Menu
2. Select "New Org"
3. Select Sandbox/Production option
4. Select "Yes" Deploy/compile code through the force menu
5. When the browser opens to login to org close the browser.
6. Repeat the above steps again and browser never opens.

**Expected behavior**
It should open the browser to login to org.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCode version 1.36.
 - ForceCode Version 3.17.4

**Additional context**

**Comment by daishi4u** [comment]
Did you cancel the login task before trying to login again?

**Comment by mzanini** [comment]
Why was this issue closed? I have the exact same problem. @daishi4u I don't know what you are referring to when you say `login task` but I have restarted VS code multiple times and the browser does not open anymore to allow to login. 
There are no tasks running in VS code. 

OS: ArchLinux
VSCode version 1.37.
ForceCode Version 3.18.1

**Comment by mzanini** [comment]
Ok I figured out. The issue happens because ForceCode now uses SFDX CLI for the login procedure and the cli gets stuck if you don't complete authentication after it started. 

To reset and make it work again, kill the CLI process on port `1717`.

1. Find the PID of the process listening on `1717`:
`netstat -tulpn | grep 1717`
2. Kill the process:
`kill -SIGTERM <PID>

Now login works again

**Comment by 09archanakumari** [comment]
For windows system    use below worked for me
1>find the PID of process listening to 1717
netstat -ano | findstr :1717
![image](https://user-images.githubusercontent.com/23060599/80306460-2799be80-87e1-11ea-86c9-2b4a9129462c.png)

2>kill the process
taskkill /PID PORT_NUMBER /F
![image](https://user-images.githubusercontent.com/23060599/80306482-41d39c80-87e1-11ea-8fa4-e6200f724c4a.png)


Happy Learning :)
