### ISSUE TITLE
Execute Anonymous not working

### ISSUE THREAD

**Issue by rakshak4** [celador/ForceCode#301]
**Description**
Task keeps running when using execute anonymous and code is not run
![image](https://user-images.githubusercontent.com/17859129/61353240-57925980-a880-11e9-9910-dec0f0dea328.png)

**To Reproduce**
1. Go to any Apex Class in src directory
2. Write "System.debug("execute anon");
3. highlight code and right click
4. Select "Force Code: Execute Anonymous"
![image](https://user-images.githubusercontent.com/17859129/61353417-db4c4600-a880-11e9-9099-4ea7418b078c.png)
5. See task is running in menu
![image](https://user-images.githubusercontent.com/17859129/61353447-f028d980-a880-11e9-939a-9d27b01828c2.png)

**Expected behavior**
Anonymous code should run and a debug log should be shown

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.36
 - ForceCode Version 3.17.4

**Comment by satveerbhantoo** [comment]
I'm having the same issue with the following error message:
![image](https://user-images.githubusercontent.com/19855322/61366660-12c7ec00-a89b-11e9-8867-d2cd1923770b.png)

**Comment by daishi4u** [comment]
If anyone is part of the beta testing channel on the Forcecode slack, can you test 3.18.0-2 and verify the issue has been fixed?

**Comment by daishi4u** [comment]
Fixed in 3.18.0
