### ISSUE TITLE
Change Log Level for DebugLog.log

### ISSUE THREAD

**Issue by cgb-76** [celador/ForceCode#302]
It'd be great to be able to specify the log level for the logs that automatically download whenever you run a unit test. Specifically, so I could change them to those required by the APEX replay debugger. 

The process would be:
1. Run test.
2. Right-click log and launch replay debugger.
3. Step through code.

The current process is:
1. "SFDX: Authorize an Org"
2. "SFDX: Turn On Apex Debug Log for Replay Debugger" 
3. "SFDX: Get APEX Debug Logs..."
4. Right-click log and launch replay debugger.
5. Step through code.

**Comment by daishi4u** [comment]
You can... You need to go to the settings for Forcecode via vscode settings. Either change the filter for debug logs or uncheck debug only... Then you get everything back

**Comment by cgb-76** [comment]
Get's me most of the way there.
Still need to "SFDX: Turn On Apex Debug Log for Replay Debugger" to get the log levels right.
The DebugLog.log file that ForceCode produces is read only and not in the project root (AFAIK) so replay debugger can't find it. However, I can keep a temp file in the project root and copy the ForceCode log contents into it, save, then run the replay debugger on that.

**Comment by daishi4u** [comment]
You should just be able to save a copy of the log once it opens....kinda like what you've got going on
