### ISSUE TITLE
Relationship fields not displayed

### ISSUE THREAD

**Issue by Kshitiz-1989** [celador/ForceCode#306]
**Describe the bug**
While querying something like Select Id, Product2.Name From OrderItem Where Id = '<someid>' the table does not show the name of the product2 record attached instead show [object Object]. How can we enable this view?

**To Reproduce**
Use ForceCode Query Editor and run the query 

**Expected behavior**
Product2.Name should be a column rather than Product2 being the column

**Screenshots**
Screenshots
![Screen Shot 2019-08-01 at 12 43 17 PM](https://user-images.githubusercontent.com/20334769/62272975-fbbbf900-b459-11e9-95aa-58b7057186e9.png)

**Desktop (please complete the following information):**
 - OS: iOS Sierra
 - VSCode version -- 1.36.1
 - ForceCode Version -- 3.18

**Comment by daishi4u** [comment]
Fixed in 3.18.2
