### ISSUE TITLE
e.split is not a function

### ISSUE THREAD

**Issue by steals** [celador/ForceCode#307]
**Describe the bug**
When I try to save an apex class that has compilation issues I got the following error message in the "Problems" panel of VSCode
`e.split is not a function [1,1]`

**To Reproduce**
1. Open any Apex class
2. Add syntax error
3. Save to server

**Expected behavior**
Problems panel should outline the actual compilation issue

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - VSCode version 1.36.1
 - ForceCode Version 3.18.1

**Comment by jgallagants** [comment]
I did notice this too.

The couple of times I got this error I had also listed the actual problem, seems somehow the actual error and the e.split are being notified for the same error detected?

**Comment by daishi4u** [comment]
@jgallagants does the e.split error appear before you save in the problems panel or does the actual error appear before then the e.split after? If it's before then it's not coming from Forcecode but from the apex extension

**Comment by steals** [comment]
For me, this error appears after the actual deploy to server.

**Comment by daishi4u** [comment]
Do you have sample Apex code that gives this error when you save it?

**Comment by daishi4u** [comment]
If either of you are members of the Forcecode slack workspace then I need someone to test the 3.18.2-1 release for a possible fix for this issue by joining the #beta-testing channel and downloading please. Thanks

**Comment by jgallagants** [comment]
Unfortunately, I've been unable to recrete the bug since my post, therefore I can't lend any example code or test the new version. I apologize.

I will continue with 3.18.1 just in case it appears again.

Sorry for the late reply.

**Comment by jgallagants** [comment]
The moment I say that...

I found an easy example code that will trigger this message. Can't try in the next beta version yet:


```
try {

} catch (Exception e);  {

}
```
And this is how they will appear at VS Code

![Code_2019-08-20_12-41-01](https://user-images.githubusercontent.com/44016735/63340698-f1e63100-c347-11e9-98bd-7228fe31643e.png)

**Comment by daishi4u** [comment]
Fixed in 3.18.2
