### ISSUE TITLE
The diff command doesn't show on VFComponent files

### ISSUE THREAD

**Issue by RandallFlagg** [celador/ForceCode#308]
**Describe the bug**
When a component file is open the diff command doesn't show in the palette menu only in the FC menu

**To Reproduce**
1. Open a component file
2. in the command palette write diff

**Expected behavior**
The command is shown

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 1903
 - VSCode version 1.37.0
 - ForceCode Version 3.18.1

**Additional context**

**Comment by daishi4u** [comment]
I don't seem to face the same issue 
![image](https://user-images.githubusercontent.com/6629523/63477203-b03daf00-c449-11e9-8327-fc42af8bb0ec.png)
