### ISSUE TITLE
Unable to deploy destructive changes.

### ISSUE THREAD

**Issue by toohey37** [celador/ForceCode#310]
**Describe the bug**
When attempting to save/deploy a destructiveChanges.xml file, a non-descriptive error is returned; 'Metadata Describe Error. Please try again'. Apex classes in the destructive changes are not deleted from sandbox environment.
Appears to be an error returned during compile from src/commands/compile.ts file https://github.com/celador/ForceCode/blob/master/src/commands/compile.ts line 163

**To Reproduce**
1. Create destructiveChanges.xml and package.xml as per info on https://developer.salesforce.com/docs/atlas.en-us.daas.meta/daas/daas_destructive_changes.htm
2. Clear all types, name, members from the package.xml
3. Add single ApexClass member to destructiveChanges.xml.
4. Attempt to Deploy to Server.
5. View error.

**Expected behavior**
Destructive changes should delete Apex class from Sandbox Environment. Using the same package.xml and destructiveChanges.xml through workbench.developerforce.com results in Apex Classes being deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/22074033/63306500-2816b700-c32e-11e9-88a6-4373db610826.png)

**Desktop (please complete the following information):**
- VS Code Version: 1.37.1 (user setup)
- Node.js: 10.11.0
- OS: Windows_NT x64 10.0.17763
- ForceCode version: 3.18.1

**Comment by daishi4u** [comment]
Could you post the contents of your destructiveChanges.xml and package.xml?

**Comment by daishi4u** [comment]
And how are you deploying it? You should be using the deploy package option in the Forcecode menu

**Comment by toohey37** [comment]
Thanks for the reply. I'm using the ForceCode: Save/Deploy/Compile option as you suggested. 
The files attached are the same ones that have been used in Workbench for destructive changes in a Production environment. Thanks!

[package.zip](https://github.com/celador/ForceCode/files/3527657/package.zip)

**Comment by daishi4u** [comment]
Yeah you are deploying the package.xml the wrong way and that's why you're receiving the error. Use the Deploy Package option in the Forcecode menu and it will resolve your issue

**Comment by toohey37** [comment]
Thanks for your help

**Comment by daishi4u** [comment]
You're welcome 😁
