### ISSUE TITLE
Sometimes, unable to save file changes to ORG

### ISSUE THREAD

**Issue by jgallagants** [celador/ForceCode#318]
Sometimes when saving I receive the following error message:

`insufficient access rights on cross-reference id: [Some ID]`

After this message, I can't save this file anymore until I restart Visual Studio Code. Other files seems to save without problems for now, for now it only happenes in .cls files

This error happens with no particular reason as I checked. Suddenly... the error.

Not sure if it's Force Code, or Visual Studio Code or the Org itself... or me!

**To Reproduce**
1. Modify a file
2. Save
3. ...
4. Profit!

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.38.0
 - ForceCode Version 3.18.6

**Additional context**
There is another user working at the Sandbox. The same error appears now and then, we login with different users. We are not working on the same files. We tried reinstalling the extension and updating SFDX.

![image](https://user-images.githubusercontent.com/44016735/64676162-44150080-d475-11e9-9e71-9988f8232ca3.png)

**Comment by somuchdependsupon** [comment]
My team and I are encountering the same"insuficient access rights" exceptions.  Interestingly, if we run the  SFDX: Deploy This Source To Org it works.

**Comment by fcorvelo** [comment]
The same issue is happening for me and my team. It started to happen since the Salesforce release preview upgrade on September 7th, so it might be related with the preview release.

There is a workaround which is to log out and log in again in FroceCode.
