### ISSUE TITLE
Metadata Describe Error. Please try again.

### ISSUE THREAD

**Issue by kennetharmond** [celador/ForceCode#327]
I've recently refreshed my developer sandbox (yesterday). Now, the ForceCode extension (v3.18.10) in VS Code (v1.38.1) is pretty much unusable due to multiple errors. I reconnected to my fresh sandbox org via my existing code project.
Now, if I try to push any class to the sandbox org using the ForceCode: Save/Compile/Deploy menu option, I get a popup at the bottom that says "Metadata Describe Error. Please try again." Once that happens, the associated cls-meta.xml file associated with my class is removed (not just from the project but the file appears to get deleted entirely).
If I try ForceCode: Refresh from server, I get another popup that says "Either the file/metadata type doesn't exist in the current org or you're trying to save/retrieve outside of <my_file_path>.

I tried wiping out the .forceCode and .sfdx folders and the force.json and sfdx-project.json files in order to start over. Then I created a new ForceCode project through the menu. This all seems to finish successfully but when I try those same operations again I get the same error messages. 

While troubleshooting, I opened a completely separate project that ties to a completely different Salesforce sandbox org (was not refreshed recently) and everything seems to work fine.

This appears to only be an issue when creating a new project from an existing org or trying to tie my existing project to a newly refreshed sandbox.

Any help would be much appreciated in resolving this.

Thanks,
Ken

**Comment by daishi4u** [comment]
Do you have the salesforce apex extension installed by chance? If so, and while you're logged into that sandbox then can you try opening their org explorer and see if it gets populated with metadata types? Just wanting to see if it's an issue with just that sandbox

**Comment by daishi4u** [comment]
@kennetharmond this almost sounds like an authentication issue, since you stated it only happens with a newly refreshed org...test out some of the SFDX CLI commands and let me know if any of them work.

**Comment by kennetharmond** [comment]
Brett,

My current project structure is rootDirectory/src which holds the classes and a sub-folder for triggers. When I run SFDX: Retrieve source from org, it pulls all the code from my sandbox and puts it in a new main/default/classes folder structure.
First, it looks like I should probably change my project’s folder structure to be like this since I think SFDX is informing me that this is the standard folder structure.
Unfortunately, if I try to run the ForceCode commands on those freshly pulls files (that include the metadata files), I still get the same errors.

Thanks,
Ken

**Comment by daishi4u** [comment]
Your source is retrieved into main/default/classes because the SFDX extensions use the newer "Source" format. You can retrieve code via the Forcecode menu by either going to Open or Retrieve
