### ISSUE TITLE
Show test classes covering my class.

### ISSUE THREAD

**Issue by Caio-Carvalho** [celador/ForceCode#329]
On Developer Console, I can run all tests in org and after that when I go to a class, there is a picklist informing me which classes are coverign that class and the percentage.
Do I have a similar way to get this result on VSCode?
![image](https://user-images.githubusercontent.com/46748699/67013505-99be7780-f0c9-11e9-9b4b-0f8a5ab3f5a4.png)

**Comment by daishi4u** [comment]
This functionality is currently not available in Forcecode, however, there is a setting that will automatically open the TESTED class (one that is covered the most when a test is ran) once you run a test class. This would be in the Forcecode settings that are found via the vscode settings menu.

**Comment by daishi4u** [comment]
This request has been added to version 3.20.0. You can find information about each test class/method that covers your class by doing the following:
![image](https://user-images.githubusercontent.com/6629523/69904180-51050a00-1369-11ea-87a1-d659c815e9ab.png)
![image](https://user-images.githubusercontent.com/6629523/69904193-709c3280-1369-11ea-8e7f-11a090fd6c10.png)

Once you are here, if you click on each class/method that tests your class, the line decorations for the file will be updated:
![image](https://user-images.githubusercontent.com/6629523/69904223-b527ce00-1369-11ea-9e08-8bb993cf27ba.png)
![image](https://user-images.githubusercontent.com/6629523/69904233-cec91580-1369-11ea-8baa-c86065941357.png)

**Comment by Caio-Carvalho** [comment]
Awsome! This was exactly what I was looking for. Now I do not need to open Developer Console anymore.
Thank you so much!!!
