### ISSUE TITLE
Don't force name convention when creating non-standard classes.

### ISSUE THREAD

**Issue by DougJod** [celador/ForceCode#33]
Allow a class to be created without having a name convention forced on it.

**Comment by DougJod** [comment]
I have a solution for this in my own branch that I would like to submit as a pull request, but I am not authorized to contribute to this repo.

**Comment by celador** [comment]
Not to this repo. You are more than welcome to fork this repo and create a pull request from yours to mine. It's pretty much the same thing as branching and contributing,  just a bit safer. 😀. I would greatly appreciate it if you would fork and create a pr!

**Comment by DougJod** [comment]
@celador 
As per your recommendation, I've forked and created a pull request from there.

**Comment by DougJod** [comment]
Any progress of reviewing/approving the outstanding pull request for this issue?
https://github.com/celador/ForceCode/pull/34

**Comment by celador** [comment]
@DougJod Thanks a bunch!  Version 0.2.21 has been published which should include this change.  Thanks for the PR!  The help is greatly appreciated.
