### ISSUE TITLE
Package.xml not used to "Refresh From Server"

### ISSUE THREAD

**Issue by yuri-1218inc** [celador/ForceCode#331]
In VSCode with the ForceCode Extension, on an existing project, there are two problems:

1> Usability Issue: Cannot "right click" on /src folder and choose **Refresh From Server**.  Must select each subfolder _(i.e. classes, components, etc.)_ and then right click and select Refresh From Server to get the latest. _Is there a better way?_

2> Potential Bug: When using the method above to Refresh From Server, the **package.xml** is seemingly ignored. For example, the package.xml has an explicit CustomObject defined, and not asterisk, and yet **EVERY single Object definition is returned**. _Is this a bug, or another usability issue? What am I doing wrong?_

 - OS: macOS
 - VSCode version: 1.39.2
 - ForceCode Version: 3.18.11

The purpose of using VSCode and ForceCode is to avoid having to migrate to the new Source Format for now. Your extension is a God-send.

**Comment by daishi4u** [comment]
Right clicking on a folder will refresh all metadata of that type. The best, and only way at the moment, to refresh via the package.xml is to go to the Retrieve Package/Metadata menu option in the Forcecode menu and choose the refresh via package.xml option

**Comment by yuri-1218inc** [comment]
Perfect, thanks. That's what I needed.
