### ISSUE TITLE
Save/Deploy/Compile Check for Diffs

### ISSUE THREAD

**Issue by ryanmugan** [celador/ForceCode#334]
I am using ForeCode on a Macbook and notice when I right click a file >> ForceCode: Save/Deploy/Compile that the file is saved up to my org without doing any kind of difference check.

My teammates on Windows machines get a warning that they might be overwriting someone else's code. I would like to have the same feature to prevent overwriting new code in the same file I am working on.

Is this a setting I can enable? I looked through the documentation and didn't really find anything related. 

Thanks!

**Comment by daishi4u** [comment]
This is always enabled. If you are referring to the check when you start Forcecode, you can enable it in the Forcecode settings located in Vscode's settings 
![image](https://user-images.githubusercontent.com/6629523/68347524-d7a52f00-00bc-11ea-8c37-627ea1d173ee.png)
![image](https://user-images.githubusercontent.com/6629523/68347673-59955800-00bd-11ea-9c63-92d26ee1853f.png)

**Comment by ryanmugan** [comment]
Good to know about startup check, but I am referring to checking for file difference on save. It sounds like it should always be checking for a diff when I run ForceCode: Save/Deploy/Compile, but it is not for me.

I have overwritten files that someone else is actively working and now have to manually run a Forcecode diff before saving out of fear of overwriting someone's code. Any ideas on how to troubleshoot? 

Appreciate the help.

**Comment by ryanmugan** [comment]
@daishi4u Not sure if you were notified of my response after closing the issue. Anything I can try? Can re-install VSCode & ForceCode when I have some time.

**Comment by daishi4u** [comment]
I figured this out. You must have been saving either via right clicking or using ctr+cmd+s. I found an issue with Forcecode not checking while saving in one of these two ways. The issues is fixed in 3.21.1.
