### ISSUE TITLE
LightningMessageChannel not supported

### ISSUE THREAD

**Issue by SirMaeXchen** [celador/ForceCode#336]
Hey, I am just experiencing some errors in VSCode with ForceCode. I installed everything but always receive the following error when I want to retrieve classes:
`"NamespacePrefix, Description FROM LightningMessageChannel WHERE NamespacePrefix ^ ERROR at Row:1:Column:61 sObject type 'LightningMessageChannel' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names." `
Any ideas?

**Comment by skeshetty** [comment]
I am also facing the same issue when retrieving files.

**Comment by herimanalina** [comment]
Same problem here!!

NamespacePrefix, Description FROM LightningMessageChannel WHERE NamespacePrefix
                                  ^
ERROR at Row:1:Column:61
sObject type 'LightningMessageChannel' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.

**Comment by wabbott-veeva** [comment]
Reporting the same

**Comment by wwarobert** [comment]
Reporting the same, blocking one - I can't get latest source from org

**Comment by yohanim** [comment]
A quick question for those having the problem : Could you verify you are using at least API version 47 ?
Should be present in your different sfdx-project.json files and settings.json files

**Comment by skeshetty** [comment]
Yes, it is 47

**Comment by herimanalina** [comment]
All API version on 47...

**Comment by daishi4u** [comment]
For everyone facing this issue, change your api version to 46.0 in the org settings (Forcecode Menu => Org Settings). This is a per-org setting. I will release a fix soon.

**Comment by daishi4u** [comment]
Fixed in 3.19.2. If you are using LightningMessageChannel in a dev org, please read the changelog for instructions to re-enable opening LMCs
