### ISSUE TITLE
Not able to open SF Org fpr authorization while creating project

### ISSUE THREAD

**Issue by Raghav0099** [celador/ForceCode#339]
Steps:

1. Open ForceCode Menu
2. Select newOrg
3. Select type as Developer Sandbox
4. Select Yes (Automatically deploy changes)

Expected result - Should open SF org where I can enter my credentials and verify
Actual - Nothing happens

VS Code - latest
Force code - 3.20

**Comment by daishi4u** [comment]
Open a terminal, either in vscode or in windows and run the following command:

sfdx force:auth:web:login

Does your browser open or do you get any error messages?

**Comment by Raghav0099** [comment]
Thanks for your concern. Here is the error I am getting

![image](https://user-images.githubusercontent.com/51886471/70024999-0ae3bc80-159c-11ea-827c-3cf04478081b.png)


Even though I have SF extension pack including CLI installed. Do you think I am missing anything

Also, I tried using Forcecode and SF ext pack few months back in another system where it was quite easy and I didn't get any such issues.

**Comment by nellus** [comment]
To resolve this issue look at Salesforce DX Developer Guide.
[Link](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_troubleshoot_cancel_auth.htm)

**Comment by daishi4u** [comment]
Thanks @nellus
