### ISSUE TITLE
Only have 2 commands on the command line of VS Code

### ISSUE THREAD

**Issue by PeterRodriguezRios** [celador/ForceCode#340]
**Describe the bug**
When typing ForceCode in the command Line of VS Code, I only have 2 commands, I type any other and it's not recognised. 
Also I choose Create Project and it lets me select a Folder, and then it creates another folder with a json but doesn't do anything else, no credentials, no anything.
The Windows Console is open and sfdx is install and force:auth:web:login it does open a web page to login of SF

**To Reproduce**
1. Go to VS Code aplication
2. Press Ctrl+shift+P for the command line
3. Type ForceCode
4. See only 2 options and ignore the rest

**Expected behavior**
1 - All the commands of ForceCode
2 - Open a webpage to log in

**Screenshots**
![image](https://user-images.githubusercontent.com/13418147/70065776-ec0d1680-15eb-11ea-94ae-7fe150eb22af.png)

**Desktop (please complete the following information):**
 - OS:  Windows
 - VSCode version 1.40.2
 - ForceCode Version 3.20.0

**Additional context**
May be I got everything wrong, and everything is manual with the JSON, but the other commands are still missing.

**Comment by daishi4u** [comment]
Yes, you should create a project first then wait for a while to let Forcecode start. If it fails to start then close vscode and reopen (with the project folder still open). Let me know if that works for you.

**Comment by daishi4u** [comment]
As a side note, once it does load you will get a Forcecode Menu in the bottom bar that you can click to open the menu and access Forcecode functionality.
