### ISSUE TITLE
Can't use Lightning Message Service with Aura when saving with Force Code

### ISSUE THREAD

**Issue by jgallagants** [celador/ForceCode#341]
**Describe the bug**

When creating a new LMS and deploying with ForceCode, the file upload correctly, but when trying to use it an error happens. For this report, I will call the LMS,  **MSChannel**.
To use this channel with Aura for example, the type must be pointed. This type will have this notation: **MSChannel__c**. When saving the Aura bundle, an error appears telling that this type
was not found.
If I deploy the Channel using DX I'm able to save the Aura bundle. It seem ForceCode is unable to create the "__c" object when deploying.

**EDIT:**
As I was doing the other point in the communitacion with a LWC, I noticed the same will happen when you try to use the LMS.

> import SAMPLEMC from "@salesforce/messageChannel/**MSChannel__c**";

**To Reproduce**
1. Go to VSCode
2. Create a new Lightning Message Service
3. Deploy to Developer ORG
4. Create new Aura component
5. Use the new LMS Channel
6. Deploy to developer ORG

**Expected behavior**
The bundle should save correctly..

**Screenshots**
![image](https://user-images.githubusercontent.com/44016735/70797159-38064b00-1da4-11ea-9ae4-7b3ecdaf45bd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.41.0
 - ForceCode Version 3.20.0

**Comment by daishi4u** [comment]
I took your example and couldn't reproduce this issue. Did you create a Lightning Message Channel via the Forcecode menu, then deploy it first, before trying to use with an Aura component?

**Comment by jgallagants** [comment]
I think I must apologize for this issue.

Today I needed another message channel in another ORG and it worked flawlessly. 
I guess I did something wrong in my previous attempt. I'm really sorry.

Thank you for your work.
