### ISSUE TITLE
Deploy only working after a save command

### ISSUE THREAD

**Issue by JoaoPucci** [celador/ForceCode#345]
**Describe the bug**
The "Save/Deploy/Compile" (Ctrl + Shift + S) command is not working on some cases.
After some test I was able to identify it is only working after a normal Save (Ctrl + S) command.
So, even if I did not modify the file I have to "Crtl + S" before "Ctrl + Dhift + S".
It also happens in the diff viewer using the arrow icons.

It is like it's considering only the save command to decide that there are new modifications and blocking the deploy.

**To Reproduce**
1. Open a file locally.
2. Do some changes to it but do not save.
3. Use Ctrl + Shift + S to deploy.
4. Deploy will not start.

**Expected behavior**
It should execute the pipeline normally as expected and not block it. 

**Desktop (please complete the following information):**
 - OS: Tested on Windows 10 and Ubuntu 18.04.3 LTS (x64)
 - VSCode version 1.41.1
 - ForceCode Version 3.21.0

**Comment by doug-episource** [comment]
Experiencing the same issue. I couldn't figure out why a freshly opened, and updated file from Github couldn't be deployed. Very confusing as the extension just does nothing...

OS: MacOS, Sierra, 10.12.6
VSCode: v 1.41.1
ForceCode: 3.21.0

**Comment by daishi4u** [comment]
This is fixed in 3.21.1
