### ISSUE TITLE
Theme absent the event and the application files in lightning component 

### ISSUE THREAD

**Issue by msrivastav13** [celador/ForceCode#35]
The .evt and .app files miss the color formatting like .cmp and .js files in lightning bundle .

![screen shot 2016-09-24 at 11 29 36 pm](https://cloud.githubusercontent.com/assets/2276156/18812847/291e7b32-82af-11e6-93ac-7733215221ed.png)

It will be awesome if color themes apply to .evt and the .app files

**Comment by celador** [comment]
Thanks for letting me know!  I've published ForceCode 0.2.19 to resolve this.  Please update your extension.  😄
