### ISSUE TITLE
Unable to deploy LWC with Test folder

### ISSUE THREAD

**Issue by jgallagants** [celador/ForceCode#350]
To test a LWC, the documentation says to create a __test__ folder inside the LWC component. Deploying it to the ORG will result in an error as is not allowed to be deployed, to prevent this, it suggests to add **/__tests__/** to the .forceignore file at the project root. Doing so, the SFDX is able to deploy with no issue.

If I try to save my LWC component with a test folder with ForceCode the deploy fails.

**To Reproduce**
1. Create a __tests__ folder in a LWC Component
2. Add a test class
3. Save any file of the LWC Component
4. The save will fail

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.41.1
 - ForceCode Version 3.21.3

**Additional context**
The ForceCode documentation says I can add at the settings.json a "files.exclude" property to exclude deployed files, but it didn't work either.

**Comment by daishi4u** [comment]
The setting you are thinking of is "force.filesExclude", but this will only work with static resource files at the moment. I am working on turning this setting into a global exclude for Forcecode and also making Forcecode recognize .forceIgnore files. I will let you know when these features have been released.

**Comment by daishi4u** [comment]
Forcecode will now allow you to use either the force.filesExclude setting or the .forceignore file to ignore for all deployment/save types, not just static resources. This functionality is in 3.22.0
