### ISSUE TITLE
Cannot Deploy After Comparing

### ISSUE THREAD

**Issue by doug-episource** [celador/ForceCode#354]
**Describe the bug**
When attempting to "Save/Deploy/Compile" an Apex file and a difference is found in the Org, after doing a "Diff" and closing the compare window, an error occurs when attempting to "Save/Deploy/Compile" again.

The Error is **Record id is not found in record. [1, 1]**. 

The only way to recover is to close VSCode and Re-open the project.

**To Reproduce**
1.  Open an Apex Class file
2. Make a change in the Salesforce Org to that file
3. Attempt to "Save/Deploy/Compile" the file from VSCode
4. When the Diff/Overwrite dialog pops up, select Diff
5. Close the Diff Window
6. Attempt to "Save/Deploy/Compile" the file again

**Expected behavior**
The file should save with the prompt again, allowing Overwrite.

**Desktop (please complete the following information):**
 - OS: macos, 10.12.6
 - VSCode Version: 1.41.1
 - ForceCode Version: 3.21.4

**Comment by daishi4u** [comment]
Fixed in 3.22.0
