### ISSUE TITLE
Slack link no longer works

### ISSUE THREAD

**Issue by jameskbw** [celador/ForceCode#357]
I was hoping to join the slack channel as I have a "How to" question, but the link no longer works:
https://forcecodeworkspace.slack.com/join/shared_invite/enQtNDczMDg3Nzg2ODcxLWRhYWM2NmI3MGNmMmE1MmRkOTFkMGQzZmQ1YjlhMDhjY2YzNmU0NDEyNDU4OGM1NzdlZjU2NTg3Y2FkNTdhMjA

<img width="300" alt="2020-01-16 11_53_33-Create account _ Slack" src="https://user-images.githubusercontent.com/59923636/72545339-dfb8e200-3856-11ea-9b7c-c857d74732a3.png">

Any other place to post a how to type question?

**Comment by daishi4u** [comment]
@celador when you get a chance, could you generate a new link to join the slack channel? Thanks

**Comment by daishi4u** [comment]
Fixed in 3.22.2
