### ISSUE TITLE
Specify how to include password and security token

### ISSUE THREAD

**Issue by btskyy** [celador/ForceCode#36]
In documentation, it would be helpful to specify how to provide both password and security token in the password field. I have tried the following key values to force.json without success:

`"password": "passwordtoken"`
`"password": "password token"`
`"password": "password,token"`
`"password": "password:token"`
`"password": "password;token"`

**Comment by mgarf** [comment]
It's the first

**Comment by celador** [comment]
@btskyy I have updated the Readme to clarify the password format.

**Comment by btskyy** [comment]
@celador works, must have entered something wrong the first time. Thanks!
