### ISSUE TITLE
ForceCode: Deploy Errors. No package.xml found

### ISSUE THREAD

**Issue by kabrice** [celador/ForceCode#360]
I cannot deploy my project from VS Code to my org anymore.
Everytime I tried to deploy, I get this error message: 
`ForceCode: Deploy Errors. View details ? No package.xml found`
Yet, retrieving project works very works very well.

Please what's happened ?

OS: MacOS Majove
VS Code version: 1.41.1
ForceCode version: 3.22.2

Please help !

**Comment by kabrice** [comment]
uninstalled and then reinstalled, and now it works perfectly

**Comment by kennethkim1221** [comment]
I am having this issue right now. I tried all options from ForceCode menu like trying to create a package.xml file inside src folder then using the ForceCode menu to deploy using a package. Also tried using the "Choose files" option. Upon checking the target org, the error says **No package.xml found** Its so buggy. Wondering how you resolve the issue on your end.

**Comment by johnsonhsu** [comment]
I had the same issue with just LWC packages. I checked the .forceignore file and commented out the line with package.xml
