### ISSUE TITLE
Record id is not found in record after timeout on class save to org occurred

### ISSUE THREAD

**Issue by hugocharbonneau** [celador/ForceCode#361]
**Describe the bug**
When doing Save/Deploy/Compile, on a cls, sometimes I will have a timeout with my Org
If I retry the Save/Deploy/Compile, I immediately get a 'Record id is not found in record [1,1]'. There is no way to get it working again. I have to close VS Code and restart

Using ForceCode 3.22.2 with on Windows 10
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by daishi4u** [comment]
Fixed in 3.22.3
