### ISSUE TITLE
Illegal value for 'line' when getting code coverage on file.

### ISSUE THREAD

**Issue by Caio-Carvalho** [celador/ForceCode#362]
**Describe the bug**
When I perform a run on a class test, percentage of code coverage are updated on ForceCode tab but my covered class does not shows coverage info.

**To Reproduce**
Open a test class;
Run all tests;
When tests finish, click on test class name at ForceCode tab;
Error message shows up.

**Expected behavior**
After clicking on test class name at ForceCode tab, the class covered should be opened with coverage information (red color at notcovered lines)

**Screenshots**
![image](https://user-images.githubusercontent.com/46748699/74186102-bc503f80-4c28-11ea-8d56-1c3e74b8c3fa.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - VSCode version 1.41.1
 - ForceCode Version 3.22.2

**Additional context**
Sometimes the message appears and the coverage info does not, sometimes message does not appears and coverage info shows up.

**Comment by daishi4u** [comment]
Can you provide a sample test class that produces this error?
