### ISSUE TITLE
Retrieve from package.xml feature doesn't retrieve settings metadata

### ISSUE THREAD

**Issue by gvgramazio** [celador/ForceCode#368]
**Describe the bug**
Retrieve from package.xml command doesn't retrieve settings metadata. It works using sfdx, ant or ForceCode retrieve metadata by type command.

**To Reproduce**
1. Open a project with a valid package.xml with either the wildcard character * or with a list of settings
2. Retrieve metadata with ForceCode retrieve from package.xml command.

**Expected behavior**
To be able to retrieve settings specified in package.xml using retrieve from package command.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - VSCode version 1.43.1
 - ForceCode Version 3.22.5

**Comment by matteo-daccordo** [comment]
Is this issue still open? I'm having the same problem and I haven't noticed since I start working with SF Knowledge. 
Please, update the issue if it is closed.

**Comment by daishi4u** [comment]
This is resolved in 3.22.6
