### ISSUE TITLE
Retrieve specific metadata

### ISSUE THREAD

**Issue by caiogrc** [celador/ForceCode#370]
Hello!

This is not a Bug or a request, is just a question at the moment.
Is it possible to download specific metadata using ForceCode?

To ilustrate this better, I will tell some examples.
If I need to download all the classes I can use Retrieve Package/Metadata -> Get All Apex classes from org.
But what if I need to download only flows? Or only Lightning Web Components?

I am working in a project with some specific configurations which don't let me download all the files, so if I try Get All Files from org I can not get it. But if I could update the package.xml telling which metadata I want to download, this could solve my problem.
I am mentioning package.xml because I am using another extension and on that extension I can configure which metadata I can download.

Is there something similar on ForceCode?
Thank you!

**Comment by itsmeakash888** [comment]
Hi caiogrc,
There is an option in Force code menu -> Retrieve Package/Metadata -> Retrieve Package.xml.
You must put your package.xml in source folder in your local project.Use below in your package.

 <types>
    <members>*</members>
    <name>Workflow</name>
  </types>
