### ISSUE TITLE
Getting an error " errMsg.indexOf is not a function"

### ISSUE THREAD

**Issue by itsmeakash888** [celador/ForceCode#371]
**Describe the bug**
While merging two branches using VS Code, we getting an error " errMsg.indexOf is not a function" by resolving merge conflict in case of Profile and Permission Set

**To Reproduce**
1. Go to VS Code.
2.  Ctrl + Shift + P -> Git:merge Branch
3. Select branch to merge.
4. There are merge conflicts of profiles and permission set.
5. Accept all current .
6. Ctrl + S
7. Ctrl + Shift + S -> to save data to server.
8. Then getting an error errMsg.indexOf is not a function

Please refer attached screenshot.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - VSCode version [e.g. 1.44.2
[Doc1.docx](https://github.com/celador/ForceCode/files/4520084/Doc1.docx)

 - ForceCode Version -> 3.16.0

**Comment by daishi4u** [comment]
I believe I fixed this issue a while back, but if it's still an issue then let me know and I'll look into it more.
