### ISSUE TITLE
Please allow default / empty value for the testLevel in the ORG Setting

### ISSUE THREAD

**Issue by Shababsoft** [celador/ForceCode#373]
**Is your feature request related to a problem? Please describe.**
Please allow default / empty value for the testLevel in the ORG Setting, as this helps to deploy to Production and the prod org should automatically decide to run or don't run test classes. Currently, we have to select one of the three test levels valid for Prod.

**Describe the solution you'd like**
Ideally, there should be an option 'default' which should not pass the testLevel param when deploying metadata to an org.

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshot
![image](https://user-images.githubusercontent.com/4686730/83359883-29711780-a375-11ea-9f8f-9034a8a65a3e.png)
.

**Comment by daishi4u** [comment]
This was enabled in 3.22.7
