### ISSUE TITLE
Allow to retrieve code coverage on demand

### ISSUE THREAD

**Issue by toretz** [celador/ForceCode#377]
Hi, 

we have around 4500 classes in our org (around 2000 are test classes). Each time i open VS Code, the RAM and CPU usage skyrocket for several minutes, making the laptop totally unusable. Even when finished, RAM usage is still around 2Gb.
If it can help, I am using OpenJDK 14.0.1 with Eclipse OpenJ9 VM.

Would be possible to add an option to NOT retrieve test coverage on startup and another option to retrieve it on demand?

Thanks!

**Comment by daishi4u** [comment]
This will be released in 3.22.9. There are two package settings. One for auto retrieving code coverage on start and another to auto retrieve when a file is retrieved from the org. They are defaulted to on, but if you turn them off it should solve your issue. A button has been added in the code coverage section of the ForceCode view to allow for a manual update of coverage.
