### ISSUE TITLE
force code not opening SF debug log

### ISSUE THREAD

**Issue by manthrayilsubin** [celador/ForceCode#386]
Hi Getting below error after running test

pls help

cannot open sflog://salesforce.com/2020-11-13T09%3A31%3A24.214Z.log?q%3DdebugLog. Detail: 
 Status from ApexLog Order By StartTimeDESC LIMIT 1
                              ^
ERROR at Row:1:Column:142
No such column 'StartTimeDESC' on entity 'ApexLog'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.

**Comment by daishi4u** [comment]
This should have been resolved by now. Closing, but let me know if for some reason this is still an issue.

**Comment by manthrayilsubin** [comment]
Yes its working now
. Appreciate your help

Thank you
Subin Babu
