### ISSUE TITLE
Details on Metadata deployment failure

### ISSUE THREAD

**Issue by jim3692** [celador/ForceCode#387]
**Is your feature request related to a problem? Please describe.**
When I try to deploy a bad Metadata XML file (ie. a layout with XML syntax errors), I get 
`Deployment failed. Please view the details in the deployment status section in Salesforce.`

**Describe the solution you'd like**
That error is thrown from `compile.ts`
```js
// capture a failed deployment there is no message returned, so guide user to view in Salesforce
errMessages.push(
  'Deployment failed. Please view the details in the deployment status section in Salesforce.'
);
```

However, in the context of this code, there is a `res` variable which holds the Id of the deployment job. This Id can then be fed to SFDX with `sfdx force:source:deploy:report -i 0Af090000030r39CAA --json` to get details about the error and show them to the user.

**Describe alternatives you've considered**
I also checked if it can be done using SOQL or Metadata API, but it looks like it's not supported.

**Comment by daishi4u** [comment]
This has been added to 3.22.10. Thanks for the suggestion!
