### ISSUE TITLE
Generate Package-xml function does not generate a package.xml

### ISSUE THREAD

**Issue by rock-pile** [celador/ForceCode#39]
OS: Windows 10
I have a project with 1 Lightning Aura bundle downloaded.
I try to use the 'Generate Package-xml' function from the ForceCode Menu and nothing happens.

**Comment by celador** [comment]
Thanks for the reminder.  I need to finish that feature

**Comment by celador** [comment]
In the meantime, I have created an npm package named `package-xml` that you can use to generate your package.xml file.  I just need to integrate that package with my extension.

**Comment by celador** [comment]
This should be part of the next release.  The dependency is on package-xml to get updated to use non-native modules.  The command is there, but does not currently work, so will likely be removed in any upcoming bigfixes.  But, as mentioned before, there are alternatives readily available until that time.
