### ISSUE TITLE
invalid cross reference Id

### ISSUE THREAD

**Issue by Rihan9** [celador/ForceCode#390]
**Describe the bug**
Unable to save any apexclass on some orgs.

The apexclass actually is updated on org, but forceCode get the error on subject

**To Reproduce**
1. edit an apex class
2. save it

**Expected behavior**
Save on orgs and get OK if it is saved correctly

**Desktop (please complete the following information):**
 - OS: Windows 10 enterprise latest update installed
 - VSCode version 1.52.1
 - ForceCode Version 3.22.9

**Additional context**
output message:
{
	"resource": "<REMOVED>/src/classes/CartDetailsController.cls",
	"owner": "fcDiagCol",
	"severity": 8,
	"message": "invalid cross reference id",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 3
}

**Comment by Rihan9** [comment]
Any news? maybe this query in "containerService" file?

> SELECT Id, MetadataContainerId, MetadataContainerMemberId, State, IsCheckOnly, ` +
        `DeployDetails, ErrorMsg FROM ContainerAsyncRequest WHERE Id='${this.containerAsyncRequestId}'

**Comment by SergioXp** [comment]
Same problem

**Comment by Rihan9** [comment]
It seems that it was a problem in the latest salesforce update. It seems that it is now fixed.
