### ISSUE TITLE
Error setting up connection: setOrgInfo

### ISSUE THREAD

**Issue by Shababsoft** [celador/ForceCode#391]
**Describe the bug**
I am not able to create a project in VS Code using the ForceCode: Create Project. I am getting the following error message

"Error setting up connection: setOrgInfo"

**Desktop (please complete the following information):**
 - OS: MAC
 - VSCode version 1.53.2
 - ForceCode Version 3.22.9

**Additional context**
`Starting connection service...
Starting Code Coverage Service...
Initializing ForceCode service
Starting ForceCode service
about to run ForceCode.switchUser

{
}

{
	status: 1,
	name: NoOrgFound,
	message: No org configuration found for name undefined,
	exitCode: 1,
	commandName: OrgDisplayCommand,
	stack: NoOrgFound: No org configuration found for name undefined
    at Function.create (/Users/shababfarhat/.local/share/sfdx/client/7.85.1-2fb9e41053/node_modules/@salesforce/core/lib/sfdxError.js:160:16)
    at AuthInfo.loadAuthFromConfig (/Users/shababfarhat/.local/share/sfdx/client/7.85.1-2fb9e41053/node_modules/@salesforce/core/lib/authInfo.js:684:49),
	warnings: 
	{
		0: The error message "NoOrgFound" has been deprecated and will be removed in v46 or later.  It will become "NamedOrgNotFound".,
	},
}
Error setting up connection: setOrgInfo
`

**Comment by metkeon** [comment]
Same problem with Windows 10. SFDX works but vscode always displays that error

**Comment by daishi4u** [comment]
This should have been fixed a while back, closing.
