### ISSUE TITLE
Check For File Changes runs on startup, even with setting disabled

### ISSUE THREAD

**Issue by talz13** [celador/ForceCode#397]
**Describe the bug**
The CheckForFileChanges function runs on every project startup, even when the corresponding setting is disabled.  

On my i7-8650U / 32gb laptop, it takes over 4 minutes to start, and over 4 minutes to switch org connections.  On other developers VM workstations, it takes over 15 minutes to finish executing tasks on startup, and over 17 minutes to switch org connection.

After making the change in PR #396, timings went down to 0:51 to start and 0:13 to switch org on my laptop, and down to 1:57 to start and 0:19 to switch org on developer VM workstation.

Fix is posted as Pull Request #396 

**To Reproduce**
1. Create a project
2. Clone 30k+ file repository into src folder
3. Restart VS Code
4. Time how long to complete "ForceCode Executing Tasks..."

**Expected behavior**
CheckForFileChanges (a.k.a. Getting workspace information) should not be run if the corresponding setting is disabled:

> Force: Check For File Changes
>  This option, when checked, will allow ForceCode to check for file changes against the server on startup of ForceCode.

**Screenshots**
![image](https://user-images.githubusercontent.com/3825115/115065844-af7a4c00-9ebc-11eb-9370-c752e5474fbe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.55.2
 - ForceCode Version 3.22.9

**Additional context**

**Comment by daishi4u** [comment]
So...The check for file changes works as intended. What you're seeing is ForceCode gathering file information that is used when:
- running apex tests
- displaying code coverage
- opening a file in the org

This breaks all of the above functionality. The good news is I'm trying to work on some performance improvements with startup dealing with the issues you discussed. Thank you for pointing out the issue.

**Comment by daishi4u** [comment]
Apologies as I meant to close the pull request.

**Comment by daishi4u** [comment]
The performance should have been greatly improved with recent updates. Let me know if you still have issues.
