### ISSUE TITLE
Unable to use ForceCode

### ISSUE THREAD

**Issue by w0ndersp00n** [celador/ForceCode#4]
Hi,

Has anyone been able to successfully use this extension in VScode? I've installed the Visualforce and Apex extensions and set the username and password in settings.json within the .vscode folder.

I however always get these errors when I try to use one of ForceCode's functions:

`No handler found for the command: 'ForceCode.xxx'. An extension might be missing an activation event.`

Anyone know how to fix this and get the extension working?

**Comment by w0ndersp00n** [comment]
@celador Am I missing something when configuring this extension?

**Comment by celador** [comment]
@w0ndersp00n  Sorry all.  I will try to keep better track of these issues.  Currently the app is built for Mac only.  Are you, by chance, using Windows?  I plan to switch out xkeychain for another a cross-platform keychain tool soon.  I will keep you posted.

**Comment by w0ndersp00n** [comment]
Yes, I'm using Windows. Would be great is this extension would also be cross platform, I'd be happy to test.

**Comment by mgarf** [comment]
@w0ndersp00n It should be fixed.

**Comment by w0ndersp00n** [comment]
I have done some quick testing with my dev org and ForceCode seems to work with Windows! Great!
