### ISSUE TITLE
Would like ability to refresh all project files from the server.

### ISSUE THREAD

**Issue by rock-pile** [celador/ForceCode#40]
Similar to "Refresh from Server..." in Mavens Mate, the ability to do the same thing in ForceCode would be very helpful.

**Comment by DougJod** [comment]
This might have functional overlap with #7 in that a refresh may be necessary if server side changes are detected.

**Comment by celador** [comment]
Agreed. Work already in progress

**Comment by celador** [comment]
I have finished this feature.  It will be available with the next release
