### ISSUE TITLE
Cannot read property 'attributes' of null

### ISSUE THREAD

**Issue by manthrayilsubin** [celador/ForceCode#403]
**Describe the bug**
Getting this error on force code extension loading

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - VSCode version latest version
 - ForceCode Version [latest version

**Additional context**

**Comment by manthrayilsubin** [comment]
https://paste.pics/CLMQD
pls find the screenshot above

**Comment by manthrayilsubin** [comment]
also unable to find the test coverage after running the tests.pls assist

**Comment by manthrayilsubin** [comment]
Hi May I know when we can see this in live? Still getting the error thank you.

**Comment by daishi4u** [comment]
You're more than welcome to test out the change by installing the test version manually from here https://daishi4u.visualstudio.com/Forcecode/_build/results?buildId=337&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by manthrayilsubin** [comment]
Hi Sir Installed the vsix..but getting the same error??Can you please helo

**Comment by daishi4u** [comment]
This should have been fixed with 3.22.12. Going to close the issue, but let me know if you still have problems.
