### ISSUE TITLE
Cannot create a trigger file. 

### ISSUE THREAD

**Issue by DougJod** [celador/ForceCode#41]
Currently, all new classes are appended with ".cls" file extension.
Need an option to create a file with a ".trigger" extension.

**Comment by celador** [comment]
One of the things I really like about ForceCode is that it's not necessary to have a command to create each different kind of file.  If you know what the file extension is supposed to be, just create the file.  When you compile it, the extension will figure out if it needs to be created or updated.  

So, just create your trigger file with the regular ol' VSCode file create button, name it however you want it to be named with the trigger extension.  This doesn't provide the metadata file, but that is simple enough to copy/paste from another file.  

I am planning on integrating "refresh from server" functionality soon, and I'll be sure to include retrieving the metadata file with that.  In the meantime, an easy way to simulate that is to have a package created, and retrieve the package from the org, which will bring down all the metadata files

**Comment by DougJod** [comment]
I kinda like the ability to create a file via the ForceCode menu and have the -meta.xml automatically generated. Seems like extra effort to manually create/copy an existing metadata file... especially if you are starting a project on a new org and don't have access to some other metadata file.

What if we simplified the ForceCode file create options. Instead of showing different class types (repository/controller/model/service/etc) which are all just basically apex classes, we combined those into one option, then added options for other file types (triggers, aura bundles, etc.) So the Create Class options would looks something like:

- Apex Class
- Trigger
- Aura Definition Bundle
- ...

**Comment by celador** [comment]
I like it.  Lets do it.  Want to take a stab the code for it?  If not, it may be a little while before I can get to it.

**Comment by DougJod** [comment]
I can work on it... I'm swamped though, so it might be a couple weeks before I get to it.

**Comment by DougJod** [comment]
I've been trying to get this working, but I can't build the latest source anymore. 
@celador  Do you have any time to help me work through some of the build errors that I'm getting? We can take this discussion offline if you want, just let me know the best way to contact you.

**Comment by celador** [comment]
I have pushed a beta version to this repo at https://github.com/celador/ForceCode/raw/beta/ForceCode-0.4.3.vsix  
Please install it and let me know how it works.

To manually install it, you'll need to run 
`code --install-extension ForceCode-0.4.2.vsix` in the folder you downloaded the extension to
