### ISSUE TITLE
Windows CLI not found after reinstall

### ISSUE THREAD

**Issue by krasseboehmer** [celador/ForceCode#426]
**Describe the bug**
Unable to use ForceCode in the version 4.1.1 under windows. 4.0.5 is working fine.

**To Reproduce**
Trying to load the new version 4.1.1 after update. Even after reinstalling the CLI it doesn't seem to work. Had to switch back to an older version.

**Expected behavior**
CLI is found and used.

**Desktop (please complete the following information):**
 - OS: Windows
 - VSCode version 1.81.0
 - ForceCode Version 4.1.1

**Additional context**
I don't know what would cause this, because the environment variables aren't changed.

**Comment by daishi4u** [comment]
@krasseboehmer you need to update your Salesforce CLI to the newer SF version. Please see instructions here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm

**Comment by urara4** [comment]
@krasseboehmer 
I had the same problem.

ForceCode 4.1.1 seems to be looking for the sf command.
Is there an sf command in a higher priority path than where you installed the sfdx CLI?

In my case, I found the sf command in this directory
C:\Users\*\AppData\Roaming\npm\

I adjusted the sfdx CLI sf command to be found first and that solved the problem.

**Comment by krasseboehmer** [comment]
fixed by reinstalling

> @krasseboehmer you need to update your Salesforce CLI to the newer SF version. Please see instructions here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm
