### ISSUE TITLE
Use Github/releases or tags to keep track of versioning.

### ISSUE THREAD

**Issue by mlattuada** [celador/ForceCode#45]
It would be awesome if you use github releases/tags to keep track of versioning, so it's going to be easier to look for resolved issues and new features.

**Comment by celador** [comment]
Good suggestion. I will keep that in mind going forward. Still learning. 👌😀

**Comment by celador** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add tagged releases](https://trello.com/c/kQXFlyVu/3-add-tagged-releases)
