### ISSUE TITLE
Running the contributed command:'ForceCode.showMenu' failed.

### ISSUE THREAD

**Issue by carlosabella** [celador/ForceCode#46]
Hi,

I can't open any command.  Everytime I try to open any command I get the same message: 

"Running the contributed command:'ForceCode ..."FAILED

![image](https://cloud.githubusercontent.com/assets/4191627/20462437/474684ce-af1e-11e6-8c07-08a11338e91e.png)

![image](https://cloud.githubusercontent.com/assets/4191627/20462445/5c166234-af1e-11e6-8185-60686d6d933b.png)

Thanks!

**Comment by celador** [comment]
🙈 I'll take a look at it today

**Comment by molsi01** [comment]
I'm also experiencing this - I've installed VSCode, and the ForceCode plugin, but opening the menu to try and set the login credentials shows this error.  Thanks :-)

**Comment by celador** [comment]
Can you paste your force.json file in here. Obviously without your
credentials.

**Comment by molsi01** [comment]
Forgive me, I'm new to this - where would I find my force.json file, on a Mac?  I've tried to use the Command Panel (ForceCode: Menu) as per the instructions, but I get the error mentioned above.
Should I _have_ a force.json file yet, if I've not managed to configure it?

**Comment by celador** [comment]
That's what I needed to know! Try creating a force.json file as per the
instructions in the readme. That might resolve your issue. I will check to
see what's causing the error when you don't have a force.json file. Sorry
about the troubles. I'll work to remedy them ASAP

**Comment by molsi01** [comment]
OK, so I have a force.json in the route of where the application is, AND in the base folder of one of the project folders I created.  It's a copy of the one in the readme just with the credentials set to my own (username, password & token, custom URL) but I still get the same error running Command Panel | ForceCode: Menu

**Comment by celador** [comment]
I'll take a look soon. Can you please paste your force.json file. Also,
describe your project folder structure a bit, and what OS you are using and
what version of ForceCode you have installed.

**Comment by molsi01** [comment]
I have installed the Visual Studio Code app, and placed it in my 'Applications' folder.
I have created a main folder ("VSCode"), and then a sub folder for a project (using the name of the Sandbox I want to connect to) under my user name folder. (so USER_NAME/VSCode/SANDBOX_FOLDER)
My force.json file is in the sub folder for the Sandbox.  The file itself is as follows:
{
    "username": "USERNAME REMOVED",
    "password": "PASSWORD REMOVED",
    "url": "URL REMOVED"
    "autoCompile": true,
    "autoRefresh": true,
    "browser": "Google Chrome Canary",
    "poll": 1500,
    "pollTimeout": 120,
    "debugOnly": false,
    "apiVersion": "37.0",
    "prefix": "namespace",
    "src": "src",
    "deployOptions": {
        "checkOnly": false,
        "testLevel": "RunLocalTests",
        "verbose": false,
        "ignoreWarnings": false
    }
}

**Comment by celador** [comment]
I've just published a new version (0.3.5) that should resolve this issue.  Please give it another shot and let me know how it goes.

**Comment by celador** [comment]
Also, make sure your prefix property matches the namespace of your org.

Actually, just remove the prefix property.  I've updated the extension to get the namespace from the org automatically.

**Comment by molsi01** [comment]
Updated to 0.3.5, and it all worked as expected - menu opens, collects credential information & compile & save preferences.  Thank you for looking at this so quickly!

**Comment by carlosabella** [comment]
For it's ok also. 

I don't get the message we reported. Thanks!
