### ISSUE TITLE
Server class version newer thn local

### ISSUE THREAD

**Issue by carlosabella** [celador/ForceCode#47]
Hi,

This is not an issue, is a question.

What happen having different versions of the same class local and remote?. I mean, suppose I change a class in the Server and afterwards I open vscode with the same class but an older version. If a save with vscode Will I overwrite remote class? Or by the time I open vscode It downloads latest version of the class?

Thanks a lot, I am concern about this.

**Comment by celador** [comment]
It overwrites the file. I've added diffing support this week, so you can
get changes between the server and local versions now. Also, if you want
the most recent version of a file from the server, use the Open command and
find the file you want to open. It will overwrite the local one.

**Comment by carlosabella** [comment]
Thanks!
