### ISSUE TITLE
'Retrieve Package' does not seem to work.

### ISSUE THREAD

**Issue by rock-pile** [celador/ForceCode#49]
OS: Windows 10
ForceCode: 0.3.10

Project layout looks like this.
![image](https://cloud.githubusercontent.com/assets/6289042/20897051/5233e5f8-bad5-11e6-88c7-9ffd06693819.png)

\src\package.xml
\force.json

My force.json and package.xml are good.

When I go to 'ForceCode Menu > Retrieve Package' I get 'There are no entries to pick from'
![image](https://cloud.githubusercontent.com/assets/6289042/20897138/b557acbe-bad5-11e6-98fd-af2915e6b227.png)

Same thing happens if I copy the package.xml to my project root folder.

**Comment by rock-pile** [comment]
I will add, I dont know if this worked in the past, I just recently have tried to use it. 
Normal fetching of files using 'Open Salesforce file' 'Get class, page or trigger' work fine.

**Comment by celador** [comment]
I have pushed a beta version to this repo at https://github.com/celador/ForceCode/raw/beta/ForceCode-0.4.3.vsix  
Please install it and let me know how it works.

To manually install it, you'll need to run 
`code --install-extension ForceCode-0.4.2.vsix` in the folder you downloaded the extension to

**Comment by celador** [comment]
rereading this issue right now, I understand what the issue is.  I renamed the command to Retrieve Metadata as you can now retrieve all unpackaged metadata from your org
