### ISSUE TITLE
Retrieve Package may throw an error

### ISSUE THREAD

**Issue by MattTurnure** [celador/ForceCode#51]
I am not sure what caused this. Could have been a stale session. Maybe I did not restart my browser before install installing BETA 4.11.

## This

<img width="637" alt="screen shot 2016-12-21 at 2 11 42 pm" src="https://cloud.githubusercontent.com/assets/9272963/21402863/7b7cdec8-c788-11e6-8475-2c9dbc0489ff.png">

## Caused this

<img width="338" alt="screen shot 2016-12-21 at 2 11 27 pm" src="https://cloud.githubusercontent.com/assets/9272963/21402847/66a0a822-c788-11e6-9f88-0c65165d0494.png">

**Comment by celador** [comment]
resolved in 0.5.27
