### ISSUE TITLE
Retrieve all classes, triggers, visualforce pages, etc... at once?

### ISSUE THREAD

**Issue by cnaccio** [celador/ForceCode#54]
Is there a way to download all subscribed metadata at once?

**Comment by celador** [comment]
I need to release the next version I've been working on. If you check the
"beta" branch in the repo, there is a recent version you can try. Or wait
till it's released. I'll try to do some final testing on it this weekend
and release it for the new year.

**Comment by celador** [comment]
@cnaccio I've just released a new version.  Please let me know if you have further questions
