### ISSUE TITLE
Class name not matching file name warning

### ISSUE THREAD

**Issue by mgarf** [celador/ForceCode#6]
Getting the following warning: 

Class Name (RDTransactionDAO) is not the same as the File Name(c:\Users\##########\Documents\sfdc-service-cloud\src\classes\RDTransactionDAO). Please fix this.

But the class name matches the file name. It might be because of the interface?

See except of file:

    public with sharing class RDTransactionDAO implements IRDTransactionDAO {

        public interface IRDTransactionDAO {
            List<RD_Transaction__c> ##############(set<Id> ###);
            List<RD_Transaction__c> ##############(Id ###, Id ###);
            List<RD_Transaction__c> ##############(Id ###);
        }`

**Comment by indyHarcourt** [comment]
I'm receiving the same issue. The class name is not matching the File Name.

But the File Name includes the entire path of the file on my drive, (drive + dir + filename) rather than just filename.

**Comment by mgarf** [comment]
@indyHarcourt See my pull request and make the same changes to your plugin locally on your machine and the message will go away.
