### ISSUE TITLE
No warning when server has changes

### ISSUE THREAD

**Issue by jutxle** [celador/ForceCode#7]
In its current state ForceCode deploys over whatever is on the server, this is going to prevent me from using the extension alongside my team for fear of overwriting remote changes without the ability to complete a merge

**Comment by DougJod** [comment]
Bump.

**Comment by DougJod** [comment]
I'm an advocate of ForceCode on my team, but this issue is a show-stopper. Can we bump the priority of this issue please?

**Comment by celador** [comment]
Thanks for the support! I will put it at the top of the list.

It's somewhat of a big feature as it requires storing metadata about your
org locally. Providing diffing support with in memory files, message boxes
with choices to overwrite or refresh, etc...

The goal of the extension is to be as minimalistic with as little
configuration as possible and to break down impediments to saving your
work. It was kind of a design decision at the start to not be concerned
with the state of the file on the server, just save it the way it is.

All developers on my team use personal dev orgs, so we don't run into the
problem often.

In case you didn't see it, I've recently added diffing support.

**Comment by DougJod** [comment]
I see the new diff feature. Looks great!
How much work would it be to just check the last modified timestamp on the server before saving, then raising a warning with (cancel | overwrite) options if the server is newer? The user can manually diff/merge/overwrite before saving again. I guess this would require storing the last known timestamp locally, but would prevent blind overwrites.

**Comment by mgarf** [comment]
I see this in the documentation but how do I enable it or utilize it? 

I think @DougJod idea would be a really good future feature.

**Comment by dimitrisuls** [comment]
+1 My team really needs this as well!

**Comment by ctinghino** [comment]
+1 It is very important for my team too, actually one of the biggest blocking-reasons.
FYI we're talking about this feature in  #119, so it may be duplicate.
