### ISSUE TITLE
No Syntax Highlighting in Linux

### ISSUE THREAD

**Issue by wabbott-veeva** [celador/ForceCode#70]
I have all of the JohnAaronNelson extensions installed: ForceCode, Apex, VisualForce.   Have restarted VSCode, but still no syntax highlighting shows up.
![forcecode](https://cloud.githubusercontent.com/assets/2293594/22356120/fd4e6468-e3fc-11e6-8536-4e4c96bbb5f2.png)

OS: Ubuntu 16.10f

**Comment by celador** [comment]
Try using this configuration in your user settings (cmd + ,) 
<img width="239" alt="screen shot 2017-01-26 at 10 15 51 pm" src="https://cloud.githubusercontent.com/assets/4984798/22359431/157fc654-e415-11e6-860a-7d5e326fa2a9.png">

**Comment by celador** [comment]
Not sure why it doesn't work automatically, someone else on Linux reported that before...

If you could assist me in debugging it on Linux, I would be greatly in your debt.

https://github.com/celador/vscode-apex-extension/issues is the more appropriate place to post this issue as that is the extension that provides the syntax highlighting.

**Comment by celador** [comment]
Please let me know if that works for you or not so I can close this ticket.

**Comment by wabbott-veeva** [comment]
Celador, it did not work.  I'll post the results on the other thread you linked.
