### ISSUE TITLE
Cannot read property 'length' of undefined error after test ran (successfully)

### ISSUE THREAD

**Issue by kpstolk** [celador/ForceCode#73]
When I ran a test this error is shown:
`Cannot read property 'length' of undefined`

But when I retrieve the log of the test it did run successfully so I guess it is not the test itself.
So it's not an issue for me directly but maybe you can look into it, let me know if I can get some extension logs somewhere.

Windows 8.1
VS Code 1.9.0
ForceCode 0.5.4

**Comment by celador** [comment]
Thanks KP, I made some improvements to testing recently.  
Check out the updated Readme for information on new features.
Let me know how you like them.

**Comment by celador** [comment]
I also recently added coverage information in the editor.

**Comment by kpstolk** [comment]
Works very nice now, thanks!
