### ISSUE TITLE
command 'ForceCode.showMenu' not found

### ISSUE THREAD

**Issue by Manzanit0** [celador/ForceCode#77]
Hi!
I just installed Forcecode in my computer running Ubuntu MATE and I got the message 

> command 'ForceCode.showMenu' not found

 when trying to start the plugin. Do you know what the issue could be?

Thanks,
Javier

**Comment by rock-pile** [comment]
Realted to https://github.com/celador/ForceCode/issues/42

**Comment by ankit1421** [comment]
Even I am facing the same issue.

**Comment by jimheru** [comment]
I have the same issue.

**Comment by divaaker** [comment]
command 'ForceCode.showMenu' not found

**Comment by crimmings** [comment]
Also just updated and receiving same error as @widowmaker110

**Comment by TimothyHuesmann** [comment]
I too am experiencing this issue

**Comment by TimothyHuesmann** [comment]
Alternatively a temporary solution is to get the branch off of the main project that someone has been keeping up to date has a working most-recent build installed via vsix here: 

https://github.com/daishi4u/ForceCode
