### ISSUE TITLE
Retrieve by package.xml , retrives files from org to a new foled "unpackaged"

### ISSUE THREAD

**Issue by tounsiMedKhaled** [celador/ForceCode#78]
ForceCode : 0.5.13
OS : Win 10

When try to retrieve data to src folder using the package.xml,  files are retrieved to a new folder unpackaged

![2017-02-22_16-02-56](https://cloud.githubusercontent.com/assets/12414592/23217158/9b601a90-f918-11e6-9897-52a2b3b5010c.png)

**Comment by celador** [comment]
Please don't post your user credentials.

**Comment by celador** [comment]
I did a little rework to that recently, and probably screwed something up.  I'll take a look as soon as I can get some spare time.

**Comment by amitkumarj1979** [comment]
Hi @celador, Did you get a chance to look at this issue. Since we refresh all files again then its an issue. Thanks

**Comment by julianACL** [comment]
Getting this error again on vscode 1.14.2, and latest forcecode 0.5.33

**Comment by pauloavelar** [comment]
Yeah, still happening. But I suppose it won't change now that this extension was deprecated.

**Comment by celador** [comment]
This bug does not happen for other users. Please follow the instructions at
the bottom of the readme to debug the extension and ascertain what the real
issue is. Additionally, It would be awesome if you could provide a PR to
fix the issue.

**Comment by amitkumarj1979** [comment]
This happens on a windows machine, mac is fine. I looked at the code there is an issue in the retrieve file under the processResult, if you add name = path.normalize(name); before saving the file that should fix the issue

**Comment by celador** [comment]
https://github.com/celador/ForceCode/pull/123
I created that Pull Request.  Please reply if this is what you were talking
about and if it resolves your issue.

**Comment by celador** [comment]
ForceCode v0.5.35 has been published.  Please update and evaluate if that has solved your issue.
