### ISSUE TITLE
Cannot retrieve packaged when having proxy setup

### ISSUE THREAD

**Issue by wings1801** [celador/ForceCode#81]
Request to https://...../ApexCSIAPI failed, reason: connect ETIMEDOUT xxx.xx.xx.xx:xxxx

Please try a look at this.

**Comment by celador** [comment]
This should be fixed in 0.5.27  Can you check again?

**Comment by wings1801** [comment]
It worked now.
Thanks.

**Comment by arturjsfCGI** [comment]
How did you config proxy?
Im having the ETIMEDOUT error:
![sf](https://user-images.githubusercontent.com/35462687/35435879-3e207af2-0284-11e8-8680-9db04f48f4d1.jpg)
