### ISSUE TITLE
INVALID_LOGIN on deploy to sandbox

### ISSUE THREAD

**Issue by eriksiewert** [celador/ForceCode#86]
force.json file is appropriately pointed to test.salesforce.com with correct username/passwordtoken, but deploy returns INVALID_LOGIN. Same package deploys successfully in force.com IDE. 
Windows 10 install with VS Code, _not_ Mac-- not sure if this is related!

**Comment by celador** [comment]
Can you add any more detail to this? Has this happened again?

**Comment by dapearce** [comment]
Hi @celador, I am having this issue on new Mac. I just downloaded and installed ForceCode today, so it is the latest version. When I start up ForceCode it successfully connects to my Salesforce sandbox (I can see the API login in my login history), however, when I go to deploy the package it shows an error of `ForceCode: INVALID_LOGIN: Invalid username, password, security token; or user locked out.`

I have confirmed all of the credentials are correct and I am not locked out (again, it also connects successfully on startup). 

Any ideas what's going on?

**Comment by dapearce** [comment]
@celador After poking around the code I resolved this by adding `loginUrl: "https://test.salesforce.com"` to `deployOptions` in the config file. I might be overlooking the impact somewhere else but the PR above is potentially a better solution.
