### ISSUE TITLE
Saving Class With Code Formatting In Comment Header Shows Confusing Message

### ISSUE THREAD

**Issue by btamburrino** [celador/ForceCode#87]
When you attempt to save an Apex class with the following at the top of the file:
```
/**
 * This class is amazing.
 * <p></p>
 * To call:
 * <pre>
 * {@code
 * AmazingClass ac = new AmazingClass(Trigger.new);
 * System.enqueueJob(ac);
 * }
 * </pre>
 */
public with sharing class AmazingClass implements Queueable, Database.AllowsCallouts {
}
```
You get the message `It appears to me that the Class Name (*) is not the same as the File Name (AmazingClass).  You may want to fix this.  Be warned, I am saving it as *`

However, it saves as AmazingClass.cls locally and does update in my org as AmazingClass.

If I remove the { from before the word `@code` in the comment, it correctly parses AmazingClass.

I'm guessing this is because getNameFromClass in getName.ts looks for a { and then tries to figure out the class name from what comes before it, and the first { occurs before the class definition inside a comment.

**Comment by celador** [comment]
fixed in 0.5.28
