### ISSUE TITLE
Cannot read property 'length' of undefined error after tests run successfully

### ISSUE THREAD

**Issue by DougThompson** [celador/ForceCode#88]
When I run tests that all complete successfully, I get the following error in the output:
```
SUCCESS: Test_VelocifyConversationRest:TestBothNotifyOpenAndClickLink - in 632ms
SUCCESS: Test_VelocifyConversationRest:TestNotifyBadRequest - in 314ms
SUCCESS: Test_VelocifyConversationRest:TestNotifyClickLink - in 393ms
SUCCESS: Test_VelocifyConversationRest:TestNotifyEmailOpen - in 394ms
================================     ERROR     ================================
Cannot read property 'length' of undefined
```
I am using:
```
Windows 8.1 Pro
VS Code 1.10.0 and 1.11.0
ForceCode 0.5.13
```

I see a closed issue (https://github.com/celador/ForceCode/issues/73) for the exact error, but no details on how it was resolved or if it was simply resolved by a new version.

**Comment by celador** [comment]
I will be releasing an update soon.

**Comment by DougThompson** [comment]
Excellent!  And thanks for an excellent extension.

**Comment by celador** [comment]
I have released some updates, modifying the way tests and logs work.  Does this problem still occur?

**Comment by DougThompson** [comment]
I no longer get that error, and it properly shows success and failure line numbers. However, the toggle test coverage does not work (no lines are highlighted), and there is a discrepancy between the test coverage summary in the "Problems" pane. The class itself is 92% covered, but the summary says 6%. I made sure to clear all test history and only ran the one test class.  This is on 0.5.28, btw.
