### ISSUE TITLE
sfdx support

### ISSUE THREAD

**Issue by pelim** [celador/ForceCode#89]
as a developer i want to use the new features from salesforce sfdx tool currently in pilot phase

https://www.salesforce.com/products/platform/products/salesforce-dx/

**Comment by dapearce** [comment]
+1

This goes to public beta tomorrow. Any plans to support?

**Comment by celador** [comment]
Yes.  I plan to add support for it.  I need to get some time to work on the extension though.  

I have already included the SalesforceDX modules in the extension and added the commands to the menu.  I need to hook up the commands with running them in a terminal, and it should be good to go.

**Comment by torynet** [comment]
celador,

Is there something special that must be done for auth against a scratch org? I gathered that one would need to use the instance url, username, and password generated by sfdx, but I'm not sure how that can cover the security token. I would imagine that all of that should be unnecessary should sfdx be fully supported as you could just use the access token, correct? Do we just have to log in and get the security token manually? Maybe I'm just missing something obvious.

Thanks,
Tory

**Comment by celador** [comment]
I have decided against adding SalesforceDX to my extension as there is an official version from Salesforce now.

https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode
