### ISSUE TITLE
Using Force:Save/Deploy does not deploy file to server - (Lightning Aura bundles)

### ISSUE THREAD

**Issue by rock-pile** [celador/ForceCode#9]
OS: Windows 10
File: Lightning .cmp file
Issue:  I make a change to my .cmp file.  I use the Force: Save/Deploy/Compile command.
Status at the bottom looks like it connects then says 'ForceCode: Compile/Deploy of undefined COMPONENT was successful'

Check my org and my changes are not there
I have checked my force.json file and the username, password, url are all correct.

**Comment by mgarf** [comment]
@rock-pile this I believe has happened to me. What usually works is rerunning the compile command after getting undefined successful. But I haven't worked with lightning only .cls

**Comment by rock-pile** [comment]
@mgarf Yes I tried the command multiple times and it does not seem to want to push the changes to the org.

**Comment by mgarf** [comment]
@rock-pile hmm the other issues I ran into with classes that might apply. Is that forcecode doesn't create classes for me. It always says successful but nothing is shown. Is it possible your lightning component is a new component? if so try creating an empty shell in your org first then try compiling.

**Comment by rock-pile** [comment]
@mgarf Yes tried that as well.  Started from a new folder, created the force.json file.  I was able to pull the lightning components from the org without issue!  However, any change I made, did not get pushed back into the org.

**Comment by rock-pile** [comment]
@mgarf Just to add, changes to something not Lightning (ie Apex Class) would save back to the org without issues, All lightning components, apps, controllers, helpers etc seem to not be working.

**Comment by celador** [comment]
@rock-pile seeing that undefined as the filename indicates to me that there's an issue getting the filename of the component.  You said you retrieved it down using the open dialog?  Is your component named like ./src/aura/{component name}/{component name}.cmp   the extension currently depends on the file structure to retrieve information about the component, which it then uses to save the component.

**Comment by rock-pile** [comment]
@celador Yes component is named ./src/aura/{component name}/{component name}.cmp, except its windows so it is .\src\aura\{component name}\{component name}.cmp

However, I did also see the filename issue mentioned in ticket https://github.com/celador/ForceCode/issues/6  so I wonder if these issues are related.

**Comment by mgarf** [comment]
@rock-pile I fixed the file name issue but maybe only for classes. I'll try to take a look this weekend and see if I can figure it out and submit a pull request on it.

**Comment by mgarf** [comment]
@rock-pile Did some quick perusing and it probably has to do with the following field. I'll play with it this weekend.

```
export function getAuraNameFromFileName(fileName: string): string {
    'use strict';
    var parts: string[] = fileName.split('src/aura/');
    var auraNameParts: string[] = (parts && parts.length) > 1 ? parts[1].split('/') : undefined;
    var auraName: string = (auraNameParts && auraNameParts.length) > 0 ? auraNameParts[0] : undefined;
    return auraName;
}
```

**Comment by rock-pile** [comment]
@mgarf Thanks, I just tested again with the latest and confirmed it is not working yet.

**Comment by mgarf** [comment]
Unfortunately didn't have time to finish this weekend. My apologies. I'll should be finished testing and with a pull request sometime this week.

**Comment by mgarf** [comment]
@rock-pile see referenced pull request. It fixes the lightning compile issue on windows. You can checkout the branch. Compile the code and copy the "out" folder and overwrite the out folder in your VS code extensions folder.

**Comment by rock-pile** [comment]
Still not working, I'll open a new issue as the error message has changed.
