### ISSUE TITLE
Move force.json configuration in to VSCode configuration folder

### ISSUE THREAD

**Issue by owenfarrell** [celador/ForceCode#91]
In order to configure a ForceCode project, a force.json configuration must be in the root of the project folder (vscode.workspace.rootPath).

In support of best practices, this configuration file should reside in VSCode's configuration folder (.vscode).

**Comment by krissmilne** [comment]
Agree with this issue, when I initially installed the extension I manually created my force.json file in the .VSCode root folder, only to find that the extension expected the file to be in the root.

Following VSCode standards, configuration files should be in the same location as the workspace and user settings files, beneath .VSCode
