### ISSUE TITLE
ver: 0.5.22 [svc.newContainer is not a function]

### ISSUE THREAD

**Issue by harddisk** [celador/ForceCode#97]
Hi,

I'm getting authentication error after updating extension to version 0.5.22. Tried resetting my token (Sandbox) yet it doesn't work.

I'm getting this error: ForceCode: Invalid URI "/services/Soap/s/37.0" when running Execute Anonymous.

Please advise.

Thank you.

**Comment by celador** [comment]
Can you debug the issue at all?  Can you run any other commands? What is your development environment like?

**Comment by harddisk** [comment]
Hi,

I made a mistake in the version. It was 0.5.21 which causes problem. I just noticed I have updated ForceCode to 0.5.22 and it's working fine now.

Thanks again for the great work.
